import { v } from "convex/values";

export const posRecoveryCredentialSchema = v.object({
  codeHash: v.optional(v.string()),
  codeSalt: v.optional(v.string()),
  codeVersion: v.optional(v.number()),
  createdAt: v.number(),
  createdByUserId: v.optional(v.id("athenaUser")),
  failedAttemptCount: v.number(),
  failureAuditBucket: v.optional(v.number()),
  failureWindowAttemptCount: v.optional(v.number()),
  failureWindowStartedAt: v.optional(v.number()),
  lastFailedAt: v.optional(v.number()),
  lastUsedAt: v.optional(v.number()),
  lockedAt: v.optional(v.number()),
  lockedUntil: v.optional(v.number()),
  organizationId: v.id("organization"),
  plaintextCode: v.optional(v.string()),
  posAccountId: v.id("athenaUser"),
  servicePrincipalId: v.optional(v.id("servicePrincipal")),
  credentialRevision: v.optional(v.number()),
  verifierKind: v.optional(
    v.union(
      v.literal("legacy_sha256"),
      v.literal("deployment_keyed_pbkdf2_sha256"),
    ),
  ),
  keyedVerifierDigest: v.optional(v.string()),
  keyedVerifierSalt: v.optional(v.string()),
  keyedVerifierIterations: v.optional(v.number()),
  keyedVerifierPepperVersion: v.optional(v.number()),
  keyedVerifierVersion: v.optional(v.number()),
  plaintextRemovedAt: v.optional(v.number()),
  legacyMigrationStatus: v.optional(
    v.union(
      v.literal("pending"),
      v.literal("migrated"),
      v.literal("rotation_required"),
    ),
  ),
  legacyMigrationAt: v.optional(v.number()),
  rotationRequiredAt: v.optional(v.number()),
  lastCorrelationId: v.optional(v.string()),
  revokedAt: v.optional(v.number()),
  revokedByUserId: v.optional(v.id("athenaUser")),
  rotatedAt: v.number(),
  rotatedByUserId: v.optional(v.id("athenaUser")),
  status: v.union(v.literal("active"), v.literal("locked"), v.literal("revoked")),
  storeId: v.id("store"),
});
