import { v } from "convex/values";

export const posServicePrincipalMigrationModeValidator = v.union(
  v.literal("compatibility"),
  v.literal("shadow"),
  v.literal("enforced"),
);

export const posServicePrincipalMigrationConflictValidator = v.union(
  v.literal("store_organization_missing"),
  v.literal("principal_missing"),
  v.literal("principal_duplicate"),
  v.literal("principal_inactive"),
  v.literal("pos_grant_missing"),
  v.literal("pos_grant_duplicate"),
  v.literal("pos_grant_cross_principal"),
  v.literal("pos_grant_inactive"),
  v.literal("transport_binding_missing"),
  v.literal("transport_binding_duplicate"),
  v.literal("transport_binding_cross_principal"),
  v.literal("transport_binding_inactive"),
  v.literal("transport_auth_user_missing"),
  v.literal("transport_auth_user_not_neutral"),
  v.literal("transport_binding_legacy_identity"),
  v.literal("credential_missing"),
  v.literal("credential_duplicate"),
  v.literal("credential_cross_organization"),
  v.literal("credential_principal_mismatch"),
  v.literal("credential_legacy_sha_only"),
  v.literal("credential_keyed_verifier_missing"),
  v.literal("credential_plaintext_exposed"),
  v.literal("terminal_duplicate_fingerprint"),
  v.literal("terminal_cross_store_binding"),
  v.literal("terminal_organization_mismatch"),
  v.literal("terminal_proof_missing"),
  v.literal("terminal_recovery_pending"),
  v.literal("legacy_pos_account_missing"),
  v.literal("legacy_pos_account_duplicate"),
  v.literal("legacy_auth_user_missing"),
  v.literal("legacy_auth_user_duplicate"),
  v.literal("legacy_membership_missing"),
  v.literal("legacy_membership_duplicate"),
  v.literal("legacy_membership_wrong_role"),
  v.literal("secret_exposure"),
  v.literal("census_overflow"),
);

export const posServicePrincipalMigrationRunSchema = v.object({
  operation: v.union(v.literal("preview"), v.literal("apply")),
  automationIdentity: v.string(),
  previewRunId: v.optional(v.id("posServicePrincipalMigrationRun")),
  status: v.union(
    v.literal("running"),
    v.literal("completed"),
    v.literal("blocked"),
  ),
  cursor: v.optional(v.string()),
  scannedCount: v.number(),
  changedCount: v.number(),
  conflictCount: v.number(),
  coverageComplete: v.boolean(),
  startedAt: v.number(),
  updatedAt: v.number(),
  completedAt: v.optional(v.number()),
});

export const posServicePrincipalMigrationCandidateSchema = v.object({
  runId: v.id("posServicePrincipalMigrationRun"),
  storeId: v.id("store"),
  organizationId: v.id("organization"),
  action: v.union(
    v.literal("unchanged"),
    v.literal("reconcile"),
    v.literal("rotation_required"),
    v.literal("conflict"),
    v.literal("applied"),
  ),
  censusFingerprint: v.string(),
  conflicts: v.array(posServicePrincipalMigrationConflictValidator),
  terminalCount: v.number(),
  pendingTerminalCount: v.number(),
  humanPosOnlyMembershipCount: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
  appliedAt: v.optional(v.number()),
});

export const posServicePrincipalMigrationStoreStateSchema = v.object({
  storeId: v.id("store"),
  organizationId: v.id("organization"),
  mode: posServicePrincipalMigrationModeValidator,
  recordedCompatibilityMode: v.literal("compatibility"),
  legacyFallbackAllowed: v.boolean(),
  revision: v.number(),
  lastAppliedPreviewRunId: v.optional(v.id("posServicePrincipalMigrationRun")),
  shadowStartedAt: v.optional(v.number()),
  enforcedAt: v.optional(v.number()),
  rollbackDeadlineAt: v.optional(v.number()),
  retiredAt: v.optional(v.number()),
  updatedAt: v.number(),
});

export const posServicePrincipalMigrationTerminalEvidenceSchema = v.object({
  storeId: v.id("store"),
  organizationId: v.id("organization"),
  terminalId: v.id("posTerminal"),
  servicePrincipalId: v.id("servicePrincipal"),
  status: v.union(
    v.literal("pending"),
    v.literal("recovered"),
    v.literal("dispositioned"),
  ),
  terminalLifecycleRevision: v.number(),
  terminalProofRevision: v.number(),
  recoveryVersion: v.optional(v.number()),
  credentialRevision: v.optional(v.number()),
  servicePrincipalSessionId: v.optional(v.id("servicePrincipalSession")),
  successfulRecoveryAt: v.optional(v.number()),
  disposition: v.optional(v.string()),
  createdAt: v.number(),
  updatedAt: v.number(),
});
