/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as JoinTeamIndexImport } from './routes/join-team.index'
import { Route as LoginLayoutImport } from './routes/login/_layout'
import { Route as LoginLayoutIndexImport } from './routes/login/_layout.index'
import { Route as AuthedOrgUrlSlugIndexImport } from './routes/_authed/$orgUrlSlug/index'
import { Route as AuthedOrgUrlSlugStoreIndexImport } from './routes/_authed/$orgUrlSlug/store/index'
import { Route as AuthedOrgUrlSlugSettingsIndexImport } from './routes/_authed/$orgUrlSlug/settings/index'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugIndexImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/index'
import { Route as AuthedOrgUrlSlugSettingsOrganizationIndexImport } from './routes/_authed/$orgUrlSlug/settings/organization/index'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugHomeImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/home'
import { Route as AuthedOrgUrlSlugSettingsStoresStoreUrlSlugImport } from './routes/_authed/$orgUrlSlug/settings/stores/$storeUrlSlug'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/products/index'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/index'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/members.index'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/configuration.index'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/products/new'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/index'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/index'
import { Route as AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditImport } from './routes/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit'

// Create Virtual Routes

const LoginImport = createFileRoute('/login')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const JoinTeamIndexRoute = JoinTeamIndexImport.update({
  id: '/join-team/',
  path: '/join-team/',
  getParentRoute: () => rootRoute,
} as any)

const LoginLayoutRoute = LoginLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LoginRoute,
} as any)

const LoginLayoutIndexRoute = LoginLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginLayoutRoute,
} as any)

const AuthedOrgUrlSlugIndexRoute = AuthedOrgUrlSlugIndexImport.update({
  id: '/$orgUrlSlug/',
  path: '/$orgUrlSlug/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedOrgUrlSlugStoreIndexRoute = AuthedOrgUrlSlugStoreIndexImport.update(
  {
    id: '/$orgUrlSlug/store/',
    path: '/$orgUrlSlug/store/',
    getParentRoute: () => AuthedRoute,
  } as any,
)

const AuthedOrgUrlSlugSettingsIndexRoute =
  AuthedOrgUrlSlugSettingsIndexImport.update({
    id: '/$orgUrlSlug/settings/',
    path: '/$orgUrlSlug/settings/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugIndexRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugIndexImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/',
    path: '/$orgUrlSlug/store/$storeUrlSlug/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugSettingsOrganizationIndexRoute =
  AuthedOrgUrlSlugSettingsOrganizationIndexImport.update({
    id: '/$orgUrlSlug/settings/organization/',
    path: '/$orgUrlSlug/settings/organization/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugHomeRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugHomeImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/home',
    path: '/$orgUrlSlug/store/$storeUrlSlug/home',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugSettingsStoresStoreUrlSlugRoute =
  AuthedOrgUrlSlugSettingsStoresStoreUrlSlugImport.update({
    id: '/$orgUrlSlug/settings/stores/$storeUrlSlug',
    path: '/$orgUrlSlug/settings/stores/$storeUrlSlug',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/products/',
    path: '/$orgUrlSlug/store/$storeUrlSlug/products/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/orders/',
    path: '/$orgUrlSlug/store/$storeUrlSlug/orders/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/members/',
    path: '/$orgUrlSlug/store/$storeUrlSlug/members/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/configuration/',
    path: '/$orgUrlSlug/store/$storeUrlSlug/configuration/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/products/new',
    path: '/$orgUrlSlug/store/$storeUrlSlug/products/new',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/',
    path: '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/',
    path: '/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/',
    getParentRoute: () => AuthedRoute,
  } as any)

const AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditRoute =
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditImport.update({
    id: '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit',
    path: '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit',
    getParentRoute: () => AuthedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/login/_layout': {
      id: '/login/_layout'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLayoutImport
      parentRoute: typeof LoginRoute
    }
    '/join-team/': {
      id: '/join-team/'
      path: '/join-team'
      fullPath: '/join-team'
      preLoaderRoute: typeof JoinTeamIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed/$orgUrlSlug/': {
      id: '/_authed/$orgUrlSlug/'
      path: '/$orgUrlSlug'
      fullPath: '/$orgUrlSlug'
      preLoaderRoute: typeof AuthedOrgUrlSlugIndexImport
      parentRoute: typeof AuthedImport
    }
    '/login/_layout/': {
      id: '/login/_layout/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginLayoutIndexImport
      parentRoute: typeof LoginLayoutImport
    }
    '/_authed/$orgUrlSlug/settings/': {
      id: '/_authed/$orgUrlSlug/settings/'
      path: '/$orgUrlSlug/settings'
      fullPath: '/$orgUrlSlug/settings'
      preLoaderRoute: typeof AuthedOrgUrlSlugSettingsIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/': {
      id: '/_authed/$orgUrlSlug/store/'
      path: '/$orgUrlSlug/store'
      fullPath: '/$orgUrlSlug/store'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/settings/stores/$storeUrlSlug': {
      id: '/_authed/$orgUrlSlug/settings/stores/$storeUrlSlug'
      path: '/$orgUrlSlug/settings/stores/$storeUrlSlug'
      fullPath: '/$orgUrlSlug/settings/stores/$storeUrlSlug'
      preLoaderRoute: typeof AuthedOrgUrlSlugSettingsStoresStoreUrlSlugImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/home': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/home'
      path: '/$orgUrlSlug/store/$storeUrlSlug/home'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/home'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugHomeImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/settings/organization/': {
      id: '/_authed/$orgUrlSlug/settings/organization/'
      path: '/$orgUrlSlug/settings/organization'
      fullPath: '/$orgUrlSlug/settings/organization'
      preLoaderRoute: typeof AuthedOrgUrlSlugSettingsOrganizationIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/'
      path: '/$orgUrlSlug/store/$storeUrlSlug'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/new': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/new'
      path: '/$orgUrlSlug/store/$storeUrlSlug/products/new'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/products/new'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/configuration/': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/configuration/'
      path: '/$orgUrlSlug/store/$storeUrlSlug/configuration'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/configuration'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/members/': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/members/'
      path: '/$orgUrlSlug/store/$storeUrlSlug/members'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/members'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/'
      path: '/$orgUrlSlug/store/$storeUrlSlug/orders'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/orders'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/'
      path: '/$orgUrlSlug/store/$storeUrlSlug/products'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/products'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit'
      path: '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/'
      path: '/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/': {
      id: '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/'
      path: '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug'
      fullPath: '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug'
      preLoaderRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedOrgUrlSlugIndexRoute: typeof AuthedOrgUrlSlugIndexRoute
  AuthedOrgUrlSlugSettingsIndexRoute: typeof AuthedOrgUrlSlugSettingsIndexRoute
  AuthedOrgUrlSlugStoreIndexRoute: typeof AuthedOrgUrlSlugStoreIndexRoute
  AuthedOrgUrlSlugSettingsStoresStoreUrlSlugRoute: typeof AuthedOrgUrlSlugSettingsStoresStoreUrlSlugRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugHomeRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugHomeRoute
  AuthedOrgUrlSlugSettingsOrganizationIndexRoute: typeof AuthedOrgUrlSlugSettingsOrganizationIndexRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugIndexRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugIndexRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexRoute
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexRoute: typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrgUrlSlugIndexRoute: AuthedOrgUrlSlugIndexRoute,
  AuthedOrgUrlSlugSettingsIndexRoute: AuthedOrgUrlSlugSettingsIndexRoute,
  AuthedOrgUrlSlugStoreIndexRoute: AuthedOrgUrlSlugStoreIndexRoute,
  AuthedOrgUrlSlugSettingsStoresStoreUrlSlugRoute:
    AuthedOrgUrlSlugSettingsStoresStoreUrlSlugRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugHomeRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugHomeRoute,
  AuthedOrgUrlSlugSettingsOrganizationIndexRoute:
    AuthedOrgUrlSlugSettingsOrganizationIndexRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugIndexRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugIndexRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexRoute,
  AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexRoute:
    AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LoginLayoutRouteChildren {
  LoginLayoutIndexRoute: typeof LoginLayoutIndexRoute
}

const LoginLayoutRouteChildren: LoginLayoutRouteChildren = {
  LoginLayoutIndexRoute: LoginLayoutIndexRoute,
}

const LoginLayoutRouteWithChildren = LoginLayoutRoute._addFileChildren(
  LoginLayoutRouteChildren,
)

interface LoginRouteChildren {
  LoginLayoutRoute: typeof LoginLayoutRouteWithChildren
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginLayoutRoute: LoginLayoutRouteWithChildren,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginLayoutRouteWithChildren
  '/join-team': typeof JoinTeamIndexRoute
  '/$orgUrlSlug': typeof AuthedOrgUrlSlugIndexRoute
  '/login/': typeof LoginLayoutIndexRoute
  '/$orgUrlSlug/settings': typeof AuthedOrgUrlSlugSettingsIndexRoute
  '/$orgUrlSlug/store': typeof AuthedOrgUrlSlugStoreIndexRoute
  '/$orgUrlSlug/settings/stores/$storeUrlSlug': typeof AuthedOrgUrlSlugSettingsStoresStoreUrlSlugRoute
  '/$orgUrlSlug/store/$storeUrlSlug/home': typeof AuthedOrgUrlSlugStoreStoreUrlSlugHomeRoute
  '/$orgUrlSlug/settings/organization': typeof AuthedOrgUrlSlugSettingsOrganizationIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug': typeof AuthedOrgUrlSlugStoreStoreUrlSlugIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/products/new': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewRoute
  '/$orgUrlSlug/store/$storeUrlSlug/configuration': typeof AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/members': typeof AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/orders': typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/products': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditRoute
  '/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug': typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginLayoutIndexRoute
  '/join-team': typeof JoinTeamIndexRoute
  '/$orgUrlSlug': typeof AuthedOrgUrlSlugIndexRoute
  '/$orgUrlSlug/settings': typeof AuthedOrgUrlSlugSettingsIndexRoute
  '/$orgUrlSlug/store': typeof AuthedOrgUrlSlugStoreIndexRoute
  '/$orgUrlSlug/settings/stores/$storeUrlSlug': typeof AuthedOrgUrlSlugSettingsStoresStoreUrlSlugRoute
  '/$orgUrlSlug/store/$storeUrlSlug/home': typeof AuthedOrgUrlSlugStoreStoreUrlSlugHomeRoute
  '/$orgUrlSlug/settings/organization': typeof AuthedOrgUrlSlugSettingsOrganizationIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug': typeof AuthedOrgUrlSlugStoreStoreUrlSlugIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/products/new': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewRoute
  '/$orgUrlSlug/store/$storeUrlSlug/configuration': typeof AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/members': typeof AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/orders': typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/products': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditRoute
  '/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug': typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexRoute
  '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/login/_layout': typeof LoginLayoutRouteWithChildren
  '/join-team/': typeof JoinTeamIndexRoute
  '/_authed/$orgUrlSlug/': typeof AuthedOrgUrlSlugIndexRoute
  '/login/_layout/': typeof LoginLayoutIndexRoute
  '/_authed/$orgUrlSlug/settings/': typeof AuthedOrgUrlSlugSettingsIndexRoute
  '/_authed/$orgUrlSlug/store/': typeof AuthedOrgUrlSlugStoreIndexRoute
  '/_authed/$orgUrlSlug/settings/stores/$storeUrlSlug': typeof AuthedOrgUrlSlugSettingsStoresStoreUrlSlugRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/home': typeof AuthedOrgUrlSlugStoreStoreUrlSlugHomeRoute
  '/_authed/$orgUrlSlug/settings/organization/': typeof AuthedOrgUrlSlugSettingsOrganizationIndexRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/': typeof AuthedOrgUrlSlugStoreStoreUrlSlugIndexRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/new': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsNewRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/configuration/': typeof AuthedOrgUrlSlugStoreStoreUrlSlugConfigurationIndexRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/members/': typeof AuthedOrgUrlSlugStoreStoreUrlSlugMembersIndexRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/': typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersIndexRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsIndexRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugEditRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/': typeof AuthedOrgUrlSlugStoreStoreUrlSlugOrdersOrderSlugIndexRoute
  '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/': typeof AuthedOrgUrlSlugStoreStoreUrlSlugProductsProductSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/join-team'
    | '/$orgUrlSlug'
    | '/login/'
    | '/$orgUrlSlug/settings'
    | '/$orgUrlSlug/store'
    | '/$orgUrlSlug/settings/stores/$storeUrlSlug'
    | '/$orgUrlSlug/store/$storeUrlSlug/home'
    | '/$orgUrlSlug/settings/organization'
    | '/$orgUrlSlug/store/$storeUrlSlug'
    | '/$orgUrlSlug/store/$storeUrlSlug/products/new'
    | '/$orgUrlSlug/store/$storeUrlSlug/configuration'
    | '/$orgUrlSlug/store/$storeUrlSlug/members'
    | '/$orgUrlSlug/store/$storeUrlSlug/orders'
    | '/$orgUrlSlug/store/$storeUrlSlug/products'
    | '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit'
    | '/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug'
    | '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/join-team'
    | '/$orgUrlSlug'
    | '/$orgUrlSlug/settings'
    | '/$orgUrlSlug/store'
    | '/$orgUrlSlug/settings/stores/$storeUrlSlug'
    | '/$orgUrlSlug/store/$storeUrlSlug/home'
    | '/$orgUrlSlug/settings/organization'
    | '/$orgUrlSlug/store/$storeUrlSlug'
    | '/$orgUrlSlug/store/$storeUrlSlug/products/new'
    | '/$orgUrlSlug/store/$storeUrlSlug/configuration'
    | '/$orgUrlSlug/store/$storeUrlSlug/members'
    | '/$orgUrlSlug/store/$storeUrlSlug/orders'
    | '/$orgUrlSlug/store/$storeUrlSlug/products'
    | '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit'
    | '/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug'
    | '/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/login/_layout'
    | '/join-team/'
    | '/_authed/$orgUrlSlug/'
    | '/login/_layout/'
    | '/_authed/$orgUrlSlug/settings/'
    | '/_authed/$orgUrlSlug/store/'
    | '/_authed/$orgUrlSlug/settings/stores/$storeUrlSlug'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/home'
    | '/_authed/$orgUrlSlug/settings/organization/'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/new'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/configuration/'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/members/'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/'
    | '/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  JoinTeamIndexRoute: typeof JoinTeamIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  JoinTeamIndexRoute: JoinTeamIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login",
        "/join-team/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/$orgUrlSlug/",
        "/_authed/$orgUrlSlug/settings/",
        "/_authed/$orgUrlSlug/store/",
        "/_authed/$orgUrlSlug/settings/stores/$storeUrlSlug",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/home",
        "/_authed/$orgUrlSlug/settings/organization/",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/products/new",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/configuration/",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/members/",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/products/",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/",
        "/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/"
      ]
    },
    "/login": {
      "filePath": "login",
      "children": [
        "/login/_layout"
      ]
    },
    "/login/_layout": {
      "filePath": "login/_layout.tsx",
      "parent": "/login",
      "children": [
        "/login/_layout/"
      ]
    },
    "/join-team/": {
      "filePath": "join-team.index.tsx"
    },
    "/_authed/$orgUrlSlug/": {
      "filePath": "_authed/$orgUrlSlug/index.tsx",
      "parent": "/_authed"
    },
    "/login/_layout/": {
      "filePath": "login/_layout.index.tsx",
      "parent": "/login/_layout"
    },
    "/_authed/$orgUrlSlug/settings/": {
      "filePath": "_authed/$orgUrlSlug/settings/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/": {
      "filePath": "_authed/$orgUrlSlug/store/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/settings/stores/$storeUrlSlug": {
      "filePath": "_authed/$orgUrlSlug/settings/stores/$storeUrlSlug.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/home": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/home.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/settings/organization/": {
      "filePath": "_authed/$orgUrlSlug/settings/organization/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/products/new": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/products/new.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/configuration/": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/configuration.index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/members/": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/members.index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/orders/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/products/": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/products/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/edit.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/orders/$orderSlug/index.tsx",
      "parent": "/_authed"
    },
    "/_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/": {
      "filePath": "_authed/$orgUrlSlug/store/$storeUrlSlug/products/$productSlug/index.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
