/* eslint-disable @convex-dev/no-collect-in-query -- Repair only collects bounded pages and affected metadata fanout; product search uses exact/search indexes. */
import { paginationOptsValidator } from "convex/server";
import { v } from "convex/values";

import type { Doc, Id } from "../_generated/dataModel";
import { mutation, query } from "../_generated/server";
import type { MutationCtx, QueryCtx } from "../_generated/server";
import {
  requireAuthenticatedAthenaUserWithCtx,
  requireOrganizationMemberRoleWithCtx,
} from "../lib/athenaUserAuth";

const DEFAULT_LIMIT = 25;
const MAX_LIMIT = 50;
const EXACT_READ_LIMIT = 10;
const TEXT_CANDIDATE_READ_LIMIT = 61;
const SEARCH_TEXT_MAX_LENGTH = 3000;
const ATTRIBUTE_VALUE_MAX_LENGTH = 120;

const productAvailabilityValidator = v.union(
  v.literal("archived"),
  v.literal("draft"),
  v.literal("live")
);

const scalarAttributeValidator = v.union(
  v.string(),
  v.number(),
  v.boolean(),
  v.null()
);

const nullableStringValidator = v.union(v.string(), v.null());
const nullableNumberValidator = v.union(v.number(), v.null());
const nullableBooleanValidator = v.union(v.boolean(), v.null());

const productSkuSearchMatchValidator = v.object({
  kind: v.union(
    v.literal("productSkuId"),
    v.literal("sku"),
    v.literal("barcode"),
    v.literal("text"),
  ),
  matchedValue: nullableStringValidator,
  rank: v.number(),
});

export const productSkuSearchResultValidator = v.object({
  attributes: v.optional(v.record(v.string(), scalarAttributeValidator)),
  barcode: nullableStringValidator,
  barcodeAutoGenerated: nullableBooleanValidator,
  category: v.union(
    v.object({
      categoryId: v.id("category"),
      description: nullableStringValidator,
      id: v.id("category"),
      name: v.string(),
      showOnStorefront: nullableBooleanValidator,
      slug: nullableStringValidator,
    }),
    v.null(),
  ),
  categoryId: v.union(v.id("category"), v.null()),
  categoryName: nullableStringValidator,
  categorySlug: nullableStringValidator,
  color: v.union(
    v.object({
      hexCode: nullableStringValidator,
      id: v.id("color"),
      name: v.string(),
    }),
    v.null(),
  ),
  colorHexCode: nullableStringValidator,
  colorId: v.union(v.id("color"), v.null()),
  colorName: nullableStringValidator,
  currency: nullableStringValidator,
  images: v.array(v.string()),
  inventoryCount: v.number(),
  isVisible: nullableBooleanValidator,
  length: nullableNumberValidator,
  match: productSkuSearchMatchValidator,
  netPrice: nullableNumberValidator,
  price: v.number(),
  primaryImageUrl: nullableStringValidator,
  product: v.union(
    v.object({
      areProcessingFeesAbsorbed: nullableBooleanValidator,
      availability: productAvailabilityValidator,
      categoryId: v.id("category"),
      currency: nullableStringValidator,
      description: nullableStringValidator,
      id: v.id("product"),
      inventoryCount: v.number(),
      isVisible: nullableBooleanValidator,
      name: v.string(),
      quantityAvailable: nullableNumberValidator,
      slug: nullableStringValidator,
      subcategoryId: v.id("subcategory"),
    }),
    v.null(),
  ),
  productAvailability: productAvailabilityValidator,
  productId: v.id("product"),
  productIsVisible: nullableBooleanValidator,
  productName: v.string(),
  productSkuCreationTime: v.number(),
  productSlug: nullableStringValidator,
  productSkuId: v.id("productSku"),
  quantityAvailable: v.number(),
  size: nullableStringValidator,
  sku: nullableStringValidator,
  skuIsVisible: nullableBooleanValidator,
  storeId: v.id("store"),
  subcategory: v.union(
    v.object({
      categoryId: v.id("category"),
      description: nullableStringValidator,
      id: v.id("subcategory"),
      name: v.string(),
      subcategoryId: v.id("subcategory"),
      slug: nullableStringValidator,
    }),
    v.null(),
  ),
  subcategoryId: v.union(v.id("subcategory"), v.null()),
  subcategoryName: nullableStringValidator,
  subcategorySlug: nullableStringValidator,
  unitCost: nullableNumberValidator,
  weight: nullableStringValidator,
});

export const productSkuSearchResponseValidator = v.object({
  candidateOverflow: v.boolean(),
  limit: v.number(),
  results: v.array(productSkuSearchResultValidator),
  truncated: v.boolean(),
});

export const repairProductSkuSearchResultValidator = v.object({
  continueCursor: v.union(v.string(), v.null()),
  duplicatesCollapsed: v.number(),
  isDone: v.boolean(),
  scanned: v.number(),
  sourceOrphans: v.number(),
  staleOrphansRemoved: v.number(),
  unchanged: v.number(),
  upserted: v.number(),
});

type DatabaseCtx = Pick<QueryCtx, "db"> | Pick<MutationCtx, "db">;
type AccessCtx = QueryCtx | MutationCtx;
type ProductSkuSearchProjection = Omit<
  Doc<"productSkuSearch">,
  "_id" | "_creationTime"
>;

async function requireProductSkuSearchAdmin(
  ctx: AccessCtx,
  storeId: Id<"store">,
  failureMessage: string,
) {
  return requireProductSkuSearchAccess(ctx, storeId, failureMessage, [
    "full_admin",
  ]);
}

export async function requireProductSkuSearchReadAccess(
  ctx: AccessCtx,
  storeId: Id<"store">,
  failureMessage: string,
) {
  return requireProductSkuSearchAccess(ctx, storeId, failureMessage, [
    "full_admin",
    "pos_only",
  ]);
}

async function requireProductSkuSearchAccess(
  ctx: AccessCtx,
  storeId: Id<"store">,
  failureMessage: string,
  allowedRoles: Array<"full_admin" | "pos_only">,
) {
  const store = await ctx.db.get("store", storeId);
  if (!store) {
    throw new Error("Store not found.");
  }

  const athenaUser = await requireAuthenticatedAthenaUserWithCtx(ctx);
  await requireOrganizationMemberRoleWithCtx(ctx, {
    allowedRoles,
    failureMessage,
    organizationId: store.organizationId,
    userId: athenaUser._id,
  });

  return { athenaUser, store };
}

function normalizeLookup(value: string | undefined): string | undefined {
  const normalized = value?.trim().toLowerCase();
  return normalized ? normalized : undefined;
}

function capped(value: string | undefined, maxLength = ATTRIBUTE_VALUE_MAX_LENGTH) {
  if (!value) return undefined;
  const trimmed = value.trim();
  if (!trimmed) return undefined;
  return trimmed.slice(0, maxLength);
}

function normalizeAttributes(
  attributes: Doc<"productSku">["attributes"],
): ProductSkuSearchProjection["attributes"] {
  if (!attributes) return undefined;

  const normalized: NonNullable<ProductSkuSearchProjection["attributes"]> = {};
  for (const [key, value] of Object.entries(attributes)) {
    if (typeof value === "string") {
      normalized[key] = value.slice(0, ATTRIBUTE_VALUE_MAX_LENGTH);
    } else if (
      typeof value === "number" ||
      typeof value === "boolean" ||
      value === null
    ) {
      normalized[key] = value;
    }
  }

  return Object.keys(normalized).length > 0 ? normalized : undefined;
}

function buildSearchText(args: {
  attributes?: ProductSkuSearchProjection["attributes"];
  category?: Doc<"category"> | null;
  color?: Doc<"color"> | null;
  product: Doc<"product">;
  sku: Doc<"productSku">;
  subcategory?: Doc<"subcategory"> | null;
}) {
  const tokens = [
    args.sku.sku,
    args.sku.barcode,
    args.sku.productName,
    args.product.name,
    args.product.slug,
    args.product.description,
    args.category?.name,
    args.category?.slug,
    args.subcategory?.name,
    args.subcategory?.slug,
    args.color?.name,
    args.color?.hexCode,
    args.sku.size,
    args.sku.weight,
    args.sku.length === undefined ? undefined : String(args.sku.length),
    ...(args.attributes
      ? Object.entries(args.attributes).flatMap(([key, value]) => [
          key,
          value === null ? undefined : String(value),
        ])
      : []),
  ];

  return tokens
    .flatMap((token) => capped(token)?.split(/\s+/) ?? [])
    .join(" ")
    .slice(0, SEARCH_TEXT_MAX_LENGTH);
}

export async function buildProductSkuSearchProjection(
  ctx: DatabaseCtx,
  productSkuId: Id<"productSku">,
): Promise<ProductSkuSearchProjection | null> {
  const sku = await ctx.db.get("productSku", productSkuId);
  if (!sku) return null;

  const product = await ctx.db.get("product", sku.productId);
  if (!product || product.storeId !== sku.storeId) {
    return null;
  }

  const [category, subcategory, color] = await Promise.all([
    ctx.db.get("category", product.categoryId),
    ctx.db.get("subcategory", product.subcategoryId),
    sku.color ? ctx.db.get("color", sku.color) : Promise.resolve(null),
  ]);
  const storeCategory = category?.storeId === sku.storeId ? category : null;
  const storeSubcategory =
    subcategory?.storeId === sku.storeId &&
    storeCategory &&
    subcategory.categoryId === storeCategory._id
      ? subcategory
      : null;
  const storeColor = color?.storeId === sku.storeId ? color : null;
  const attributes = normalizeAttributes(sku.attributes);
  const now = Date.now();

  return {
    attributes,
    barcode: sku.barcode,
    barcodeAutoGenerated: sku.barcodeAutoGenerated,
    categoryDescription: storeCategory?.description,
    categoryId: storeCategory?._id,
    categoryName: storeCategory?.name,
    categorySlug: storeCategory?.slug,
    categoryShowOnStorefront: storeCategory?.showOnStorefront,
    colorHexCode: storeColor?.hexCode,
    colorId: storeColor?._id,
    colorName: storeColor?.name,
    currency: product.currency,
    images: sku.images,
    inventoryCount: sku.inventoryCount,
    isVisible: sku.isVisible,
    length: sku.length,
    netPrice: sku.netPrice,
    normalizedBarcode: normalizeLookup(sku.barcode),
    normalizedSku: normalizeLookup(sku.sku),
    price: sku.price,
    productAvailability: product.availability,
    productCategoryId: product.categoryId,
    productDescription: product.description,
    productId: product._id,
    productInventoryCount: product.inventoryCount,
    productIsVisible: product.isVisible,
    productName: product.name,
    productProcessingFeesAbsorbed: product.areProcessingFeesAbsorbed,
    productQuantityAvailable: product.quantityAvailable,
    productSlug: product.slug,
    productSkuCreationTime: sku._creationTime,
    productSkuId: sku._id,
    productSubcategoryId: product.subcategoryId,
    quantityAvailable: sku.quantityAvailable,
    searchText: buildSearchText({
      attributes,
      category: storeCategory,
      color: storeColor,
      product,
      sku,
      subcategory: storeSubcategory,
    }),
    size: sku.size,
    sku: sku.sku,
    storeId: sku.storeId,
    subcategoryDescription: storeSubcategory?.description,
    subcategoryId: storeSubcategory?._id,
    subcategoryName: storeSubcategory?.name,
    subcategorySlug: storeSubcategory?.slug,
    unitCost: sku.unitCost,
    weight: sku.weight,
    sourceUpdatedAt: now,
    updatedAt: now,
  };
}

function projectionsEqual(
  existing: Doc<"productSkuSearch">,
  next: ProductSkuSearchProjection,
) {
  const {
    _id: _existingId,
    _creationTime: _existingCreationTime,
    sourceUpdatedAt: _existingSourceUpdatedAt,
    updatedAt: _existingUpdatedAt,
    ...existingComparable
  } = existing;
  const {
    sourceUpdatedAt: _nextSourceUpdatedAt,
    updatedAt: _nextUpdatedAt,
    ...nextComparable
  } = next;

  return JSON.stringify(existingComparable) === JSON.stringify(nextComparable);
}

export async function upsertProductSkuSearchProjection(
  ctx: Pick<MutationCtx, "db">,
  productSkuId: Id<"productSku">,
): Promise<"upserted" | "unchanged" | "source_orphan"> {
  const projection = await buildProductSkuSearchProjection(ctx, productSkuId);
  const existingRows = await ctx.db
    .query("productSkuSearch")
    .withIndex("by_productSkuId", (q) => q.eq("productSkuId", productSkuId))
    .collect();

  if (!projection) {
    await Promise.all(
      existingRows.map((row) => ctx.db.delete("productSkuSearch", row._id)),
    );
    return "source_orphan";
  }

  const [firstRow, ...duplicates] = existingRows;
  await Promise.all(
    duplicates.map((row) => ctx.db.delete("productSkuSearch", row._id)),
  );

  if (!firstRow) {
    await ctx.db.insert("productSkuSearch", projection);
    return "upserted";
  }

  if (projectionsEqual(firstRow, projection) && duplicates.length === 0) {
    return "unchanged";
  }

  await ctx.db.patch("productSkuSearch", firstRow._id, projection);
  return "upserted";
}

export async function removeProductSkuSearchProjection(
  ctx: Pick<MutationCtx, "db">,
  productSkuId: Id<"productSku">,
) {
  const rows = await ctx.db
    .query("productSkuSearch")
    .withIndex("by_productSkuId", (q) => q.eq("productSkuId", productSkuId))
    .collect();

  await Promise.all(
    rows.map((row) => ctx.db.delete("productSkuSearch", row._id)),
  );
}

export async function refreshProductSkuSearchForProduct(
  ctx: Pick<MutationCtx, "db">,
  productId: Id<"product">,
) {
  const skus = await ctx.db
    .query("productSku")
    .withIndex("by_productId", (q) => q.eq("productId", productId))
    .collect();

  await Promise.all(
    skus.map((sku) => upsertProductSkuSearchProjection(ctx, sku._id)),
  );
}

export async function refreshProductSkuSearchForCategory(
  ctx: Pick<MutationCtx, "db">,
  categoryId: Id<"category">,
) {
  const products = await ctx.db
    .query("product")
    .withIndex("by_categoryId", (q) => q.eq("categoryId", categoryId))
    .collect();

  await Promise.all(
    products.map((product) =>
      refreshProductSkuSearchForProduct(ctx, product._id),
    ),
  );
}

export async function refreshProductSkuSearchForSubcategory(
  ctx: Pick<MutationCtx, "db">,
  subcategoryId: Id<"subcategory">,
) {
  const products = await ctx.db
    .query("product")
    .withIndex("by_subcategoryId", (q) =>
      q.eq("subcategoryId", subcategoryId),
    )
    .collect();

  await Promise.all(
    products.map((product) =>
      refreshProductSkuSearchForProduct(ctx, product._id),
    ),
  );
}

export async function refreshProductSkuSearchForColor(
  ctx: Pick<MutationCtx, "db">,
  colorId: Id<"color">,
) {
  const skus = await ctx.db
    .query("productSku")
    .withIndex("by_color", (q) => q.eq("color", colorId))
    .collect();

  await Promise.all(
    skus.map((sku) => upsertProductSkuSearchProjection(ctx, sku._id)),
  );
}

type ProductSkuSearchMatch = {
  kind: "productSkuId" | "sku" | "barcode" | "text";
  matchedValue: string | null;
  rank: number;
};

function mapProjectionToResult(
  projection: ProductSkuSearchProjection,
  match: ProductSkuSearchMatch,
) {
  return {
    attributes: projection.attributes,
    barcode: projection.barcode ?? null,
    barcodeAutoGenerated: projection.barcodeAutoGenerated ?? null,
    category: projection.categoryId
      ? {
          categoryId: projection.categoryId,
          description: projection.categoryDescription ?? null,
          id: projection.categoryId,
          name: projection.categoryName ?? "",
          showOnStorefront: projection.categoryShowOnStorefront ?? null,
          slug: projection.categorySlug ?? null,
        }
      : null,
    categoryId: projection.categoryId ?? null,
    categoryName: projection.categoryName ?? null,
    categorySlug: projection.categorySlug ?? null,
    color: projection.colorId
      ? {
          hexCode: projection.colorHexCode ?? null,
          id: projection.colorId,
          name: projection.colorName ?? "",
        }
      : null,
    colorHexCode: projection.colorHexCode ?? null,
    colorId: projection.colorId ?? null,
    colorName: projection.colorName ?? null,
    currency: projection.currency ?? null,
    images: projection.images,
    inventoryCount: projection.inventoryCount,
    isVisible: projection.isVisible ?? null,
    length: projection.length ?? null,
    match,
    netPrice: projection.netPrice ?? null,
    price: projection.price,
    primaryImageUrl: projection.images[0] ?? null,
    product: {
      areProcessingFeesAbsorbed:
        projection.productProcessingFeesAbsorbed ?? null,
      availability: projection.productAvailability,
      categoryId: projection.productCategoryId,
      currency: projection.currency ?? null,
      description: projection.productDescription ?? null,
      id: projection.productId,
      inventoryCount: projection.productInventoryCount,
      isVisible: projection.productIsVisible ?? null,
      name: projection.productName,
      quantityAvailable: projection.productQuantityAvailable ?? null,
      slug: projection.productSlug ?? null,
      subcategoryId: projection.productSubcategoryId,
    },
    productAvailability: projection.productAvailability,
    productId: projection.productId,
    productIsVisible: projection.productIsVisible ?? null,
    productName: projection.productName,
    productSkuCreationTime: projection.productSkuCreationTime,
    productSlug: projection.productSlug ?? null,
    productSkuId: projection.productSkuId,
    quantityAvailable: projection.quantityAvailable,
    size: projection.size ?? null,
    sku: projection.sku ?? null,
    skuIsVisible: projection.isVisible ?? null,
    storeId: projection.storeId,
    subcategory: projection.subcategoryId && projection.categoryId
      ? {
          categoryId: projection.categoryId,
          description: projection.subcategoryDescription ?? null,
          id: projection.subcategoryId,
          name: projection.subcategoryName ?? "",
          subcategoryId: projection.subcategoryId,
          slug: projection.subcategorySlug ?? null,
        }
      : null,
    subcategoryId: projection.subcategoryId ?? null,
    subcategoryName: projection.subcategoryName ?? null,
    subcategorySlug: projection.subcategorySlug ?? null,
    unitCost: projection.unitCost ?? null,
    weight: projection.weight ?? null,
  };
}

async function hydrateCanonicalProjection(
  ctx: Pick<QueryCtx, "db">,
  candidate: Pick<Doc<"productSkuSearch">, "productSkuId" | "storeId">,
) {
  if (!candidate.productSkuId) return null;

  const projection = await buildProductSkuSearchProjection(
    ctx,
    candidate.productSkuId,
  );

  if (!projection || projection.storeId !== candidate.storeId) {
    return null;
  }

  return projection;
}

export const searchProductSkus = query({
  args: {
    limit: v.optional(v.number()),
    query: v.string(),
    storeId: v.id("store"),
  },
  returns: productSkuSearchResponseValidator,
  handler: async (ctx, args) => {
    await requireProductSkuSearchReadAccess(
      ctx,
      args.storeId,
      "You do not have access to search product SKUs.",
    );

    const queryText = args.query.trim();
    const normalizedQuery = normalizeLookup(queryText);
    const limit = Math.min(Math.max(1, args.limit ?? DEFAULT_LIMIT), MAX_LIMIT);

    if (!normalizedQuery) {
      return {
        candidateOverflow: false,
        limit,
        results: [],
        truncated: false,
      };
    }

    const canonicalSkuLookupValues = [
      queryText,
      queryText.toUpperCase(),
      queryText.toLowerCase(),
    ].filter((value, index, values) => values.indexOf(value) === index);

    const exactCandidates = await Promise.all([
      (async () => {
        const productSkuId = ctx.db.normalizeId("productSku", queryText);
        if (!productSkuId) return [];

        const sku = await ctx.db.get("productSku", productSkuId);
        if (!sku || sku.storeId !== args.storeId) return [];

        return [
          {
            _creationTime: sku._creationTime,
            productSkuId: sku._id,
            storeId: sku.storeId,
          },
        ];
      })(),
      (async () => {
        const matches = await Promise.all(
          canonicalSkuLookupValues.map((lookupValue) =>
            ctx.db
              .query("productSku")
              .withIndex("by_storeId_sku", (q) =>
                q.eq("storeId", args.storeId).eq("sku", lookupValue),
              )
              .take(EXACT_READ_LIMIT),
          ),
        );

        return matches.flat();
      })(),
      ctx.db
        .query("productSku")
        .withIndex("by_storeId_barcode", (q) =>
          q.eq("storeId", args.storeId).eq("barcode", queryText),
        )
        .take(EXACT_READ_LIMIT),
      ctx.db
        .query("productSkuSearch")
        .withIndex("by_storeId_productSkuId", (q) =>
          q
            .eq("storeId", args.storeId)
            .eq("productSkuId", queryText as Id<"productSku">),
        )
        .take(EXACT_READ_LIMIT),
      ctx.db
        .query("productSkuSearch")
        .withIndex("by_storeId_sku", (q) =>
          q.eq("storeId", args.storeId).eq("normalizedSku", normalizedQuery),
        )
        .take(EXACT_READ_LIMIT),
      ctx.db
        .query("productSkuSearch")
        .withIndex("by_storeId_barcode", (q) =>
          q
            .eq("storeId", args.storeId)
            .eq("normalizedBarcode", normalizedQuery),
        )
        .take(EXACT_READ_LIMIT),
    ]);

    const textCandidates = await ctx.db
      .query("productSkuSearch")
      .withSearchIndex("searchText", (q) =>
        q.search("searchText", queryText).eq("storeId", args.storeId),
      )
      .take(TEXT_CANDIDATE_READ_LIMIT);

    const candidateRows = [
      ...exactCandidates[0].map((row) => ({
        row,
        match: {
          kind: "productSkuId" as const,
          matchedValue: String(row.productSkuId),
          rank: 0,
        },
      })),
      ...exactCandidates[1].map((row) => ({
        row: {
          productSkuId: row._id,
          storeId: row.storeId,
        },
        match: {
          kind: "sku" as const,
          matchedValue: row.sku ?? null,
          rank: 1,
        },
      })),
      ...exactCandidates[2].map((row) => ({
        row: {
          productSkuId: row._id,
          storeId: row.storeId,
        },
        match: {
          kind: "barcode" as const,
          matchedValue: row.barcode ?? null,
          rank: 2,
        },
      })),
      ...exactCandidates[3].map((row) => ({
        row,
        match: {
          kind: "productSkuId" as const,
          matchedValue: String(row.productSkuId),
          rank: 0,
        },
      })),
      ...exactCandidates[4].map((row) => ({
        row,
        match: {
          kind: "sku" as const,
          matchedValue: row.sku ?? null,
          rank: 1,
        },
      })),
      ...exactCandidates[5].map((row) => ({
        row,
        match: {
          kind: "barcode" as const,
          matchedValue: row.barcode ?? null,
          rank: 2,
        },
      })),
      ...textCandidates.map((row, index) => ({
        row,
        match: {
          kind: "text" as const,
          matchedValue: queryText,
          rank: 3 + index,
        },
      })),
    ];
    const results: Array<ReturnType<typeof mapProjectionToResult>> = [];
    const seenSkuIds = new Set<string>();

    for (const candidate of candidateRows) {
      const row = candidate.row;
      const key = String(row.productSkuId);
      if (seenSkuIds.has(key)) continue;

      const projection = await hydrateCanonicalProjection(ctx, row);
      if (!projection) continue;

      seenSkuIds.add(key);
      results.push(mapProjectionToResult(projection, candidate.match));
    }

    const truncated = results.length > limit;
    const candidateOverflow = textCandidates.length >= TEXT_CANDIDATE_READ_LIMIT;

    return {
      candidateOverflow,
      limit,
      results: results.slice(0, limit),
      truncated,
    };
  },
});

export const repairProductSkuSearchPage = mutation({
  args: {
    paginationOpts: paginationOptsValidator,
    storeId: v.id("store"),
  },
  returns: repairProductSkuSearchResultValidator,
  handler: async (ctx, args) => {
    await requireProductSkuSearchAdmin(
      ctx,
      args.storeId,
      "You do not have access to repair product SKU search.",
    );

    const page = await ctx.db
      .query("productSku")
      .withIndex("by_storeId", (q) => q.eq("storeId", args.storeId))
      .paginate({
        ...args.paginationOpts,
        numItems: Math.min(args.paginationOpts.numItems, 100),
      });

    const stats = {
      duplicatesCollapsed: 0,
      scanned: page.page.length,
      sourceOrphans: 0,
      staleOrphansRemoved: 0,
      unchanged: 0,
      upserted: 0,
    };

    for (const sku of page.page) {
      const existingRows = await ctx.db
        .query("productSkuSearch")
        .withIndex("by_productSkuId", (q) => q.eq("productSkuId", sku._id))
        .collect();
      const result = await upsertProductSkuSearchProjection(ctx, sku._id);
      if (result === "upserted") stats.upserted += 1;
      if (result === "unchanged") stats.unchanged += 1;
      if (result === "source_orphan") stats.sourceOrphans += 1;
      stats.duplicatesCollapsed += Math.max(0, existingRows.length - 1);
    }

    return {
      ...stats,
      continueCursor: page.continueCursor,
      isDone: page.isDone,
    };
  },
});

export const removeStaleProductSkuSearchPage = mutation({
  args: {
    paginationOpts: paginationOptsValidator,
    storeId: v.id("store"),
  },
  returns: repairProductSkuSearchResultValidator,
  handler: async (ctx, args) => {
    await requireProductSkuSearchAdmin(
      ctx,
      args.storeId,
      "You do not have access to repair product SKU search.",
    );

    const page = await ctx.db
      .query("productSkuSearch")
      .withIndex("by_storeId", (q) => q.eq("storeId", args.storeId))
      .paginate({
        ...args.paginationOpts,
        numItems: Math.min(args.paginationOpts.numItems, 100),
      });

    const stats = {
      duplicatesCollapsed: 0,
      scanned: page.page.length,
      sourceOrphans: 0,
      staleOrphansRemoved: 0,
      unchanged: 0,
      upserted: 0,
    };

    for (const row of page.page) {
      const source = await ctx.db.get("productSku", row.productSkuId);

      if (!source || source.storeId !== args.storeId) {
        await ctx.db.delete("productSkuSearch", row._id);
        stats.sourceOrphans += 1;
        stats.staleOrphansRemoved += 1;
        continue;
      }

      const duplicates = await ctx.db
        .query("productSkuSearch")
        .withIndex("by_productSkuId", (q) =>
          q.eq("productSkuId", row.productSkuId),
        )
        .collect();
      const [canonicalRow, ...duplicateRows] = duplicates.sort((left, right) =>
        left._creationTime - right._creationTime,
      );

      if (canonicalRow && canonicalRow._id !== row._id) {
        stats.unchanged += 1;
        continue;
      }

      await Promise.all(
        duplicateRows.map((duplicate) =>
          ctx.db.delete("productSkuSearch", duplicate._id),
        ),
      );
      stats.duplicatesCollapsed += duplicateRows.length;
      stats.staleOrphansRemoved += duplicateRows.length;
      stats.unchanged += 1;
    }

    return {
      ...stats,
      continueCursor: page.continueCursor,
      isDone: page.isDone,
    };
  },
});
