import { v } from "convex/values";

export const skuActivityEventSchema = v.object({
  storeId: v.id("store"),
  organizationId: v.optional(v.id("organization")),
  productSkuId: v.id("productSku"),
  productId: v.optional(v.id("product")),
  activityType: v.string(),
  status: v.optional(v.string()),
  occurredAt: v.number(),
  createdAt: v.number(),
  sourceType: v.string(),
  sourceId: v.string(),
  sourceLineId: v.optional(v.string()),
  idempotencyKey: v.string(),
  quantityDelta: v.optional(v.number()),
  reservationQuantity: v.optional(v.number()),
  stockQuantityDelta: v.optional(v.number()),
  actorUserId: v.optional(v.id("athenaUser")),
  actorStaffProfileId: v.optional(v.id("staffProfile")),
  customerProfileId: v.optional(v.id("customerProfile")),
  workItemId: v.optional(v.id("operationalWorkItem")),
  registerSessionId: v.optional(v.id("registerSession")),
  terminalId: v.optional(v.id("posTerminal")),
  onlineOrderId: v.optional(v.id("onlineOrder")),
  posTransactionId: v.optional(v.id("posTransaction")),
  checkoutSessionId: v.optional(v.id("checkoutSession")),
  inventoryMovementId: v.optional(v.id("inventoryMovement")),
  inventoryHoldId: v.optional(v.id("inventoryHold")),
  workflowTraceId: v.optional(v.string()),
  operationalEventId: v.optional(v.id("operationalEvent")),
  sourceLabel: v.optional(v.string()),
  metadata: v.optional(v.record(v.string(), v.any())),
});
