import View from "../View";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "../ui/table";
import { Label } from "../ui/label";
import { Input } from "../ui/input";
import { Button } from "../ui/button";
import { Badge } from "../ui/badge";
import {
  DotsHorizontalIcon,
  PlusCircledIcon,
  TrashIcon,
} from "@radix-ui/react-icons";
import { getErrorForField } from "@/lib/utils";
import { CardFooter } from "../ui/card";
import { useProduct } from "@/contexts/ProductContext";
import { ImageFile } from "../ui/image-uploader";
import {
  Barcode,
  Check,
  Eye,
  EyeOff,
  Image,
  Info,
  RefreshCw,
  RotateCcw,
  ShieldCheck,
  ShoppingCart,
  TriangleAlert,
  X,
  ScanBarcode,
} from "lucide-react";
import useGetActiveProduct from "@/hooks/useGetActiveProduct";
import useGetActiveStore from "~/src/hooks/useGetActiveStore";
import { BarcodeQRViewer } from "./BarcodeQRViewer";
import { useMutation, useQuery } from "convex/react";
import { api } from "~/convex/_generated/api";
import { Id } from "~/convex/_generated/dataModel";
import { toast } from "sonner";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "../ui/tooltip";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "../ui/dropdown-menu";
import { useSheet } from "./SheetProvider";
import { Fragment, useEffect, useRef, useState } from "react";
import { CopyImagesView } from "./copy-images/CopyImagesView";
import { useSkusReservedInCheckout } from "@/hooks/useSkusReservedInCheckout";
import { useSkusReservedInPosSession } from "@/hooks/useSkusReservedInPosSession";
import { AlertModal } from "../ui/modals/alert-modal";
import { presentUnexpectedErrorToast } from "~/src/lib/errors/presentUnexpectedErrorToast";
import { currencyDisplaySymbol } from "~/shared/currencyFormatter";
import type { Product } from "~/types";
import type { FunctionReference } from "convex/server";
import type { CommandResult } from "~/shared/commandResult";
import {
  buildTrustedInventoryFinalizationPayload,
  parseVariantInputValue,
  resolveTrustedInventoryCommandError,
  resolveTrustedInventoryFinalizationPricingPolicy,
  resolveTrustedInventoryRefreshReviewState,
  resolveTrustedInventoryReviewClickAction,
  resolveTrustedInventoryReviewState,
  resolveStockInputUpdate,
  type ProductPageProvisionalSkuBinding,
  type ProductVariantInputField,
  type TrustedInventoryFinalizationPayload,
} from "./ProductStockInput";

export type ProductVariant = {
  id: string;
  sku?: string;
  barcode?: string;
  barcodeAutoGenerated?: boolean;
  barcodePersistedInDb?: boolean;
  stock?: number;
  quantityAvailable?: number;
  isVisible?: boolean;
  cost?: number;
  price?: number;
  netPrice?: number;
  length?: number;
  color?: Id<"color"> | string;
  colorName?: string;
  size?: string;
  weight?: string;
  attributes?: Record<string, unknown>;
  markedForDeletion?: boolean;
  existsInDB?: boolean;
  images: ImageFile[];
};

type ProductPageTrustedInventoryFinalizationResult = {
  finalTrustedQuantity: number;
  productId: Id<"product">;
  productSkuId: Id<"productSku">;
  provisionalSkuId: Id<"inventoryImportProvisionalSku">;
  provisionalSoldQuantity: number;
  quantityAvailable: number;
};

type ProductPageProvisionalSkuBindingQuery = FunctionReference<
  "query",
  "public",
  {
    productSkuId: Id<"productSku">;
    refreshNonce?: number;
    storeId: Id<"store">;
  },
  ProductPageProvisionalSkuBinding
>;

type ProductPageTrustedInventoryFinalizationMutation = FunctionReference<
  "mutation",
  "public",
  TrustedInventoryFinalizationPayload,
  CommandResult<ProductPageTrustedInventoryFinalizationResult>
>;

const catalogImportApi = api.inventory.catalogImport as unknown as {
  finalizeTrustedInventoryFromProductPage: ProductPageTrustedInventoryFinalizationMutation;
  listProductPageProvisionalSkuBinding: ProductPageProvisionalSkuBindingQuery;
};

const StockHeader = ({
  isSkuReserved,
}: {
  isSkuReserved: (sku?: string) => boolean;
}) => {
  const { updateProductVariants, productVariants } = useProduct();

  const { toggleSheet, setSheetContent } = useSheet();

  useEffect(() => {
    setSheetContent(
      <div className="h-[90vh] overflow-y-auto">
        <CopyImagesView />
      </div>,
    );
  }, []);

  const restock = () => {
    updateProductVariants((prevVariants) =>
      prevVariants.map(
        (variant) =>
          !isSkuReserved(variant.sku)
            ? {
                ...variant,
                stock: 5,
                quantityAvailable: 5,
              }
            : variant, // Keep reserved variants unchanged
      ),
    );
  };

  return (
    <div className="flex items-center justify-between">
      <p className="text-sm">Variants</p>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="ghost"
            className="flex h-8 w-8 p-0 data-[state=open]:bg-muted"
          >
            <DotsHorizontalIcon className="w-4 h-4" />
            <span className="sr-only">Open menu</span>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-[160px]">
          <DropdownMenuItem onClick={restock}>
            <div className="flex items-center gap-2">
              <RefreshCw className="w-4 h-4 text-muted-foreground" />
              {productVariants.length > 1 && <p>Restock all</p>}
              {productVariants.length == 1 && <p>Restock</p>}
            </div>
          </DropdownMenuItem>

          {productVariants.length > 1 && (
            <>
              <DropdownMenuSeparator />

              <DropdownMenuItem onClick={() => toggleSheet(true)}>
                <div className="flex items-center gap-2">
                  <Image className="w-4 h-4 text-muted-foreground" />
                  <p>Copy images</p>
                </div>
              </DropdownMenuItem>
            </>
          )}
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
};

export function ProductStockView() {
  const { productVariants } = useProduct();

  // Check which SKUs are reserved in active checkout sessions
  const skusToCheck = productVariants.map((variant) => variant.sku);
  const { isSkuReserved: isSkuReservedInCheckout } =
    useSkusReservedInCheckout(skusToCheck);
  const { isSkuReserved: isSkuReservedInPosSession } =
    useSkusReservedInPosSession(skusToCheck);

  // Combined check for both checkout and POS sessions
  const isSkuReserved = (sku?: string) =>
    isSkuReservedInCheckout(sku) || isSkuReservedInPosSession(sku);

  // Helper to determine which type of reservation
  const getReservationType = (sku?: string): "checkout" | "pos" | null => {
    if (!sku) return null;
    if (isSkuReservedInCheckout(sku)) return "checkout";
    if (isSkuReservedInPosSession(sku)) return "pos";
    return null;
  };

  return (
    <View
      hideBorder
      hideHeaderBottomBorder
      fullHeight={false}
      lockDocumentScroll={false}
      header={<StockHeader isSkuReserved={isSkuReserved} />}
    >
      <Stock
        isSkuReserved={isSkuReserved}
        getReservationType={getReservationType}
      />
    </View>
  );
}

function isLegacyImportDraftProduct(activeProduct?: Product | null) {
  return (
    activeProduct?.availability === "draft" &&
    activeProduct?.categorySlug === "legacy-import"
  );
}

function LegacyImportTrustPreview({
  activeProduct,
  areProcessingFeesAbsorbed,
  finalized,
  isContextRefreshing,
  onFinalized,
  onMakeVisible,
  reservationType,
  storeId,
  variant,
}: {
  activeProduct?: Product | null;
  areProcessingFeesAbsorbed?: boolean;
  finalized?: boolean;
  isContextRefreshing?: boolean;
  onFinalized: (result: {
    sku: {
      id: string;
      stock: number;
      quantityAvailable: number;
      cost?: number;
      price?: number;
      netPrice?: number;
      isVisible?: boolean;
    };
  }) => void;
  onMakeVisible: (id: string) => void;
  reservationType: "checkout" | "pos" | null;
  storeId?: Id<"store">;
  variant: ProductVariant;
}) {
  const rowRef = useRef<HTMLTableRowElement | null>(null);
  const [conversionRequestIds, setConversionRequestIds] = useState<
    Record<string, string>
  >({});
  const [isFinalizing, setIsFinalizing] = useState(false);
  const [commandMessage, setCommandMessage] = useState<string | null>(null);
  const [requiresReviewRefresh, setRequiresReviewRefresh] = useState(false);
  const [bindingRefreshNonce, setBindingRefreshNonce] = useState(0);

  const binding = useQuery(
    catalogImportApi.listProductPageProvisionalSkuBinding,
    activeProduct && storeId && variant.existsInDB
      ? {
          productSkuId: variant.id as Id<"productSku">,
          refreshNonce: bindingRefreshNonce,
          storeId,
        }
      : "skip",
  );

  const finalizeTrustedInventory = useMutation(
    catalogImportApi.finalizeTrustedInventoryFromProductPage,
  );

  const reviewState = resolveTrustedInventoryReviewState({
    binding,
    finalized,
    isFinalizing,
    isRefreshing: isContextRefreshing,
    reservationType,
    variant,
  });

  useEffect(() => {
    setRequiresReviewRefresh(false);
    setCommandMessage(null);
  }, [
    binding?.state === "unique" ? binding.saleEvidenceFingerprint : binding?.state,
    binding?.state === "unique" ? binding.trustedSkuFingerprint : undefined,
  ]);

  const getConversionRequestId = () => {
    const existing = conversionRequestIds[variant.id];
    if (existing) {
      return existing;
    }

    const next =
      typeof crypto !== "undefined" && "randomUUID" in crypto
        ? crypto.randomUUID()
        : `product-edit-${variant.id}-${Date.now()}`;

    setConversionRequestIds((prev) => ({ ...prev, [variant.id]: next }));
    return next;
  };

  const normalizeCommandMessage = (
    result: Exclude<CommandResult<unknown>, { kind: "ok" }>,
  ) => {
    const resolved = resolveTrustedInventoryCommandError(result);
    setRequiresReviewRefresh(resolved.requiresReviewRefresh);
    return resolved.message;
  };

  const handleFinalize = async () => {
    if (!activeProduct || !storeId || binding?.state !== "unique") {
      return;
    }

    setIsFinalizing(true);
    setCommandMessage(null);
    setRequiresReviewRefresh(false);

    try {
      const payload = buildTrustedInventoryFinalizationPayload({
        areProcessingFeesAbsorbed,
        binding,
        conversionRequestId: getConversionRequestId(),
        productId: activeProduct._id,
        storeId,
        variant,
      });

      const result = await finalizeTrustedInventory(payload);
      if (result.kind === "user_error") {
        setCommandMessage(normalizeCommandMessage(result));
        window.requestAnimationFrame(() => rowRef.current?.focus());
        return;
      }

      onFinalized({
        sku: {
          id: result.data.productSkuId,
          stock: result.data.finalTrustedQuantity,
          quantityAvailable: result.data.quantityAvailable,
          cost: variant.cost,
          price: variant.price,
          netPrice: variant.netPrice,
          isVisible: variant.isVisible,
        },
      });
      setCommandMessage(
        "Inventory finalized. Save remaining product changes separately.",
      );
    } catch (error) {
      console.error(error);
      setCommandMessage("Trusted inventory was not finalized. Try again.");
      presentUnexpectedErrorToast("Trusted inventory was not finalized");
      window.requestAnimationFrame(() => rowRef.current?.focus());
    } finally {
      setIsFinalizing(false);
    }
  };

  const handleClick = () => {
    const action = resolveTrustedInventoryReviewClickAction({
      requiresReviewRefresh,
      reviewState,
    });

    if (action === "make_visible") {
      onMakeVisible(variant.id);
      return;
    }

    if (action === "refresh_review") {
      const nextState = resolveTrustedInventoryRefreshReviewState({
        conversionRequestIds,
        refreshNonce: bindingRefreshNonce,
        variantId: variant.id,
      });
      setRequiresReviewRefresh(false);
      setCommandMessage(null);
      setBindingRefreshNonce(nextState.refreshNonce);
      setConversionRequestIds(nextState.conversionRequestIds);
      return;
    }

    if (action === "finalize") {
      void handleFinalize();
    }
  };

  const statusMessage = commandMessage ?? reviewState.message;
  const ctaLabel = requiresReviewRefresh
    ? "Refresh review"
    : reviewState.ctaLabel;
  const isCtaDisabled = requiresReviewRefresh ? false : reviewState.disabled;
  const isFinalized = reviewState.status === "success";

  return (
    <TableRow
      ref={rowRef}
      tabIndex={-1}
      className="focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
    >
      <TableCell colSpan={8} className="px-4 py-3">
        <div
          className={`flex flex-col gap-3 rounded-md border bg-background px-3 py-3 transition-[border-color,box-shadow] duration-150 ease-out sm:flex-row sm:items-center sm:justify-between ${
            isFinalized
              ? "border-action-workflow-border shadow-sm"
              : "border-border"
          }`}
        >
          <div className="min-w-0 space-y-2">
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant="outline" className="gap-1.5 text-foreground">
                <ShieldCheck className="h-3.5 w-3.5" />
                Trusted inventory review
              </Badge>
              <Badge
                variant="outline"
                className="border-border bg-muted/40 text-muted-foreground"
              >
                Provisional SKU
              </Badge>
              {isFinalized ? (
                <Badge
                  variant="outline"
                  className="gap-1.5 border-action-workflow-border bg-background text-action-workflow"
                >
                  <Check className="h-3.5 w-3.5" />
                  Finalized
                </Badge>
              ) : null}
            </div>
            <p
              className="max-w-3xl text-pretty text-xs leading-5 text-muted-foreground"
              role="status"
              aria-live="polite"
            >
              {statusMessage}
            </p>
            {binding?.state === "unique" && (
              <p className="text-[11px] leading-4 text-muted-foreground">
                Linked import row {binding.row.rowNumber}
                {binding.row.provisionalSoldQuantity !== undefined
                  ? ` · provisional sales ${binding.row.provisionalSoldQuantity}`
                  : ""}
              </p>
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2 sm:justify-end">
            {isFinalized ? (
              <div
                className="inline-flex min-h-10 items-center gap-2 rounded-md px-3 text-xs font-medium text-muted-foreground"
                role="status"
                aria-live="polite"
              >
                <Check className="h-3.5 w-3.5 text-action-workflow" />
                Trusted SKU ready
              </div>
            ) : (
              <Button
                type="button"
                size="sm"
                variant="workflow-soft"
                className="min-h-10 active:scale-[0.96] transition-transform"
                disabled={isCtaDisabled}
                onClick={handleClick}
              >
                {ctaLabel}
              </Button>
            )}
          </div>
        </div>
      </TableCell>
    </TableRow>
  );
}

function Stock({
  isSkuReserved,
  getReservationType,
}: {
  isSkuReserved: (sku?: string) => boolean;
  getReservationType: (sku?: string) => "checkout" | "pos" | null;
}) {
  const {
    error,
    isLoading,
    mergeTrustedInventoryFinalization,
    removeProductVariant,
    productVariants,
    updateProductVariants,
    activeProductVariant,
    setActiveProductVariant,
    showLoaderForProduct,
  } = useProduct();

  const { activeProduct } = useGetActiveProduct();

  const { activeStore } = useGetActiveStore();

  const [qrViewerOpen, setQrViewerOpen] = useState(false);
  const [selectedVariant, setSelectedVariant] = useState<ProductVariant | null>(
    null,
  );
  const [isGeneratingBarcode, setIsGeneratingBarcode] = useState(false);
  const [clearBarcodeModalOpen, setClearBarcodeModalOpen] = useState(false);
  const [variantToClear, setVariantToClear] = useState<string | null>(null);
  const [isClearingBarcode, setIsClearingBarcode] = useState(false);
  const [finalizedTrustedInventorySkuIds, setFinalizedTrustedInventorySkuIds] =
    useState<Set<string>>(() => new Set());
  const generateBarcodeMutation = useMutation(
    api.inventory.products.generateUniqueBarcode,
  );
  const updateSkuMutation = useMutation(api.inventory.products.updateSku);

  const handleGenerateBarcode = async (variantId: string) => {
    const variant = productVariants.find((v) => v.id === variantId);
    if (!variant || !variant.existsInDB || !activeStore || !activeProduct)
      return;

    setIsGeneratingBarcode(true);
    try {
      const result = await generateBarcodeMutation({
        storeId: activeStore._id,
        productId: activeProduct._id,
        skuId: variantId as Id<"productSku">,
      });

      if (result.success && result.barcode) {
        updateProductVariants((prevVariants) =>
          prevVariants.map((v) =>
            v.id === variantId
              ? {
                  ...v,
                  barcode: result.barcode,
                  barcodeAutoGenerated: true,
                  barcodePersistedInDb: true,
                }
              : v,
          ),
        );
        toast.success("Barcode generated");

        // Open the QR viewer after successful generation
        setSelectedVariant({
          ...variant,
          barcode: result.barcode,
          barcodeAutoGenerated: true,
          barcodePersistedInDb: true,
        });
      } else {
        toast.error(result.error || "Failed to generate barcode");
      }
    } catch (error) {
      presentUnexpectedErrorToast("Error generating barcode");
      console.error(error);
    } finally {
      setIsGeneratingBarcode(false);
    }
  };

  const handleSaveBarcode = async (variantId: string) => {
    const variant = productVariants.find((v) => v.id === variantId);
    if (!variant || !variant.barcode) return;

    try {
      const result = await updateSkuMutation({
        id: variantId as Id<"productSku">,
        barcode: variant.barcode,
      });

      const mutationResult = result as { error?: string };
      if (mutationResult.error) {
        toast.error(mutationResult.error || "Failed to save barcode");
      }
    } catch (error) {
      presentUnexpectedErrorToast("Failed to save barcode");
      console.error(error);
    }
  };

  const handleViewBarcode = (variantId: string) => {
    const variant = productVariants.find((v) => v.id === variantId);
    if (!variant || !variant.barcode) return;

    setSelectedVariant(variant);
    setQrViewerOpen(true);
  };

  const handleClearBarcodeClick = (variantId: string) => {
    setVariantToClear(variantId);
    setClearBarcodeModalOpen(true);
  };

  const handleClearBarcodeConfirm = async () => {
    if (!variantToClear) return;

    const variant = productVariants.find((v) => v.id === variantToClear);

    console.log("variant", variant);
    if (!variant || !variant.existsInDB) {
      // If variant doesn't exist in DB, just update local state
      updateProductVariants((prevVariants) =>
        prevVariants.map((v) =>
          v.id === variantToClear
            ? {
                ...v,
                barcode: "",
                barcodeAutoGenerated: false,
                barcodePersistedInDb: false,
              }
            : v,
        ),
      );
      toast.success("Barcode cleared");
      setClearBarcodeModalOpen(false);
      setVariantToClear(null);
      return;
    }

    setIsClearingBarcode(true);

    try {
      // Persist to backend
      const result = (await updateSkuMutation({
        id: variantToClear as Id<"productSku">,
        barcode: "",
        barcodeAutoGenerated: false,
      })) as { error?: string; success?: boolean };

      if (result?.success === false) {
        toast.error(result?.error || "Failed to clear barcode");
        return;
      }

      // Update local state on success
      // updateProductVariants((prevVariants) =>
      //   prevVariants.map((v) =>
      //     v.id === variantToClear
      //       ? {
      //           ...v,
      //           barcode: "",
      //           barcodeAutoGenerated: false,
      //           barcodePersistedInDb: false,
      //         }
      //       : v
      //   )
      // );

      toast.success("Barcode cleared");
      setClearBarcodeModalOpen(false);
      setVariantToClear(null);
    } catch (error) {
      presentUnexpectedErrorToast("Error clearing barcode");
      console.error(error);
    } finally {
      setIsClearingBarcode(false);
    }
  };

  const handleClearBarcodeCancel = () => {
    setClearBarcodeModalOpen(false);
    setVariantToClear(null);
  };

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement>,
    variantId: string,
    field: ProductVariantInputField,
  ) => {
    const value = parseVariantInputValue(field, e.target.value);

    updateProductVariants((prevVariants) =>
      prevVariants.map((variant) => {
        if (variant.id !== variantId) return variant;

        if (field === "stock") {
          return {
            ...variant,
            ...resolveStockInputUpdate(value as ProductVariant["stock"]),
          };
        } else {
          // For all other fields, use default behavior
          return { ...variant, [field]: value };
        }
      }),
    );
  };

  const addRow = () => {
    const newVariant: ProductVariant = {
      id: Date.now().toString(),
      sku: undefined,
      stock: undefined,
      quantityAvailable: undefined,
      cost: undefined,
      price: undefined,
      images: [],
    };

    updateProductVariants((prevVariants) => [...prevVariants, newVariant]);
    setActiveProductVariant(newVariant);
  };

  const handleDeleteAction = (
    variantId: string,
    markedForDeletion?: boolean,
  ) => {
    if (markedForDeletion) {
      updateProductVariants((prevVariants) =>
        prevVariants.map((variant) =>
          variant.id === variantId
            ? { ...variant, markedForDeletion: false }
            : variant,
        ),
      );
    } else {
      removeProductVariant(variantId);
    }
  };

  const setOutOfStock = (id: string) => {
    updateProductVariants((prevVariants) =>
      prevVariants.map((variant) =>
        variant.id === id
          ? { ...variant, quantityAvailable: 0, stock: 0 }
          : variant,
      ),
    );
  };

  const setVisibility = (id: string) => {
    updateProductVariants((prevVariants) =>
      prevVariants.map((variant) =>
        variant.id === id
          ? {
              ...variant,
              isVisible:
                variant.isVisible == undefined ? false : !variant.isVisible,
            }
          : variant,
      ),
    );
  };

  const isLastActiveVariant = (index: number) => {
    return productVariants.every(
      (v, idx) => index == idx || v.markedForDeletion,
    );
  };

  const isLastVisibleVariant = (index: number) => {
    return productVariants.every(
      (v, idx) => index == idx || v.isVisible == false,
    );
  };

  const shouldDisable = (variant: ProductVariant) => {
    return (
      variant.markedForDeletion ||
      variant.isVisible == false ||
      isSkuReserved(variant.sku)
    );
  };

  const hasQuantityError = (variant: ProductVariant) => {
    return (
      variant.quantityAvailable !== undefined &&
      variant.stock !== undefined &&
      variant.quantityAvailable > variant.stock
    );
  };

  const shouldShowTrustPreview = isLegacyImportDraftProduct(activeProduct);

  const handleTrustedInventoryFinalized = (result: {
    sku: {
      id: string;
      stock: number;
      quantityAvailable: number;
      cost?: number;
      price?: number;
      netPrice?: number;
      isVisible?: boolean;
    };
  }) => {
    mergeTrustedInventoryFinalization(result);
    setFinalizedTrustedInventorySkuIds((prev) => {
      const next = new Set(prev);
      next.add(result.sku.id);
      return next;
    });
  };

  const hasPriceError = (variant: ProductVariant) => {
    return (
      (variant.price === 0 || variant.price === undefined) && variant.existsInDB
    );
  };

  return (
    <>
      {productVariants.length > 0 && (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Variant</TableHead>
              <TableHead>
                <div className="flex items-center gap-1">
                  <p>SKU</p>
                  {!activeProduct && (
                    <TooltipProvider>
                      <Tooltip>
                        <TooltipTrigger>
                          <Info className="w-3.5 h-3.5 text-muted-foreground" />
                        </TooltipTrigger>
                        <TooltipContent>
                          <p>auto-generated</p>
                        </TooltipContent>
                      </Tooltip>
                    </TooltipProvider>
                  )}
                </div>
              </TableHead>
              <TableHead>Barcode</TableHead>
              <TableHead>Stock</TableHead>
              <TableHead>Quantity available</TableHead>
              <TableHead>
                Price ({currencyDisplaySymbol(activeStore?.currency ?? "GHS")})
              </TableHead>
              <TableHead>
                Cost ({currencyDisplaySymbol(activeStore?.currency ?? "GHS")})
              </TableHead>
            </TableRow>
          </TableHeader>

          <TableBody>
            {productVariants.map((variant, index) => (
              <Fragment key={variant.id}>
                <TableRow
                  onClick={() => setActiveProductVariant(variant)}
                  className={variant.markedForDeletion ? "opacity-50" : ""}
                >
                  <TableCell>
                    <p>{index + 1}</p>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <div className="flex-1">
                        {showLoaderForProduct ? null : !activeProduct ? (
                          <Input
                            id={`sku-${index}`}
                            type="text"
                            placeholder="SKU"
                            onChange={(e) => handleChange(e, variant.id, "sku")}
                            value={variant.sku || ""}
                            readOnly
                            disabled={shouldDisable(variant)}
                          />
                        ) : (
                          <p
                            className={`${variant.id == activeProductVariant.id ? "font-bold" : "text-muted-foreground"}`}
                          >
                            {variant.sku}
                          </p>
                        )}
                      </div>
                      {isSkuReserved(variant.sku) && (
                        <TooltipProvider>
                          <Tooltip>
                            <TooltipTrigger>
                              {getReservationType(variant.sku) ===
                              "checkout" ? (
                                <ShoppingCart className="w-4 h-4 text-green-500" />
                              ) : (
                                <ScanBarcode className="w-4 h-4 text-blue-500" />
                              )}
                            </TooltipTrigger>
                            <TooltipContent>
                              <p>
                                {getReservationType(variant.sku) === "checkout"
                                  ? "SKU is reserved in an active checkout session"
                                  : "SKU is reserved in an active POS session"}
                              </p>
                            </TooltipContent>
                          </Tooltip>
                        </TooltipProvider>
                      )}
                    </div>
                    {error && getErrorForField(error, "sku") && (
                      <p className="text-red-500 text-sm font-medium">
                        {getErrorForField(error, "sku")?.message}
                      </p>
                    )}
                  </TableCell>

                  <TableCell>
                    <Label htmlFor={`barcode-${index}`} className="sr-only">
                      Barcode
                    </Label>
                    <div className="flex items-center gap-2">
                      {showLoaderForProduct ? null : (
                        <>
                          <Input
                            id={`barcode-${index}`}
                            type="text"
                            placeholder="Barcode"
                            onChange={(e) =>
                              handleChange(e, variant.id, "barcode")
                            }
                            value={variant.barcode || ""}
                            readOnly={variant.barcodePersistedInDb === true}
                            disabled={shouldDisable(variant)}
                            className={
                              variant.barcodePersistedInDb === true
                                ? "bg-muted"
                                : ""
                            }
                          />
                          {!variant.barcode && variant.existsInDB && (
                            <TooltipProvider>
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <Button
                                    size="sm"
                                    variant="outline"
                                    onClick={() =>
                                      handleGenerateBarcode(variant.id)
                                    }
                                    disabled={
                                      isGeneratingBarcode ||
                                      shouldDisable(variant)
                                    }
                                  >
                                    <Barcode className="w-4 h-4" />
                                  </Button>
                                </TooltipTrigger>
                                <TooltipContent>
                                  <p>Generate barcode</p>
                                </TooltipContent>
                              </Tooltip>
                            </TooltipProvider>
                          )}
                          {variant.barcode &&
                            variant.barcodePersistedInDb === false && (
                              <TooltipProvider>
                                <Tooltip>
                                  <TooltipTrigger asChild>
                                    <Button
                                      size="sm"
                                      variant="outline"
                                      onClick={() =>
                                        handleSaveBarcode(variant.id)
                                      }
                                      disabled={
                                        isGeneratingBarcode ||
                                        shouldDisable(variant)
                                      }
                                    >
                                      <Check className="w-4 h-4" />
                                    </Button>
                                  </TooltipTrigger>
                                  <TooltipContent>
                                    <p>Save barcode</p>
                                  </TooltipContent>
                                </Tooltip>
                              </TooltipProvider>
                            )}
                          {variant.barcode && variant.barcodePersistedInDb && (
                            <>
                              <TooltipProvider>
                                <Tooltip>
                                  <TooltipTrigger asChild>
                                    <Button
                                      size="sm"
                                      variant="outline"
                                      onClick={() =>
                                        handleClearBarcodeClick(variant.id)
                                      }
                                      disabled={isSkuReserved(variant.sku)}
                                    >
                                      <X className="w-4 h-4" />
                                    </Button>
                                  </TooltipTrigger>
                                  <TooltipContent>
                                    <p>Clear barcode</p>
                                  </TooltipContent>
                                </Tooltip>
                              </TooltipProvider>
                              <TooltipProvider>
                                <Tooltip>
                                  <TooltipTrigger asChild>
                                    <Button
                                      size="sm"
                                      variant="outline"
                                      onClick={() =>
                                        handleViewBarcode(variant.id)
                                      }
                                    >
                                      <Barcode className="w-4 h-4" />
                                    </Button>
                                  </TooltipTrigger>
                                  <TooltipContent>
                                    <p>View barcode QR</p>
                                  </TooltipContent>
                                </Tooltip>
                              </TooltipProvider>
                            </>
                          )}
                        </>
                      )}
                    </div>
                    {error && getErrorForField(error, "barcode") && (
                      <p className="text-red-500 text-sm font-medium">
                        {getErrorForField(error, "barcode")?.message}
                      </p>
                    )}
                  </TableCell>

                  <TableCell>
                    <Label htmlFor={`stock-${index}`} className="sr-only">
                      Stock
                    </Label>
                    {showLoaderForProduct ? null : (
                      <Input
                        id={`stock-${index}`}
                        type="number"
                        placeholder="0"
                        onChange={(e) => handleChange(e, variant.id, "stock")}
                        value={variant.stock || ""}
                        disabled={shouldDisable(variant)}
                      />
                    )}
                    {error && getErrorForField(error, "inventoryCount") && (
                      <p className="text-red-500 text-sm font-medium">
                        {getErrorForField(error, "inventoryCount")?.message}
                      </p>
                    )}
                  </TableCell>

                  <TableCell>
                    <Label htmlFor={`stock-${index}`} className="sr-only">
                      Quantity available
                    </Label>
                    {showLoaderForProduct ? null : (
                      <Input
                        id={`quantity-available-${index}`}
                        type="number"
                        placeholder="0"
                        onChange={(e) =>
                          handleChange(e, variant.id, "quantityAvailable")
                        }
                        value={variant.quantityAvailable || ""}
                        disabled={shouldDisable(variant)}
                        className={
                          hasQuantityError(variant) ? "border-red-500" : ""
                        }
                      />
                    )}
                    {error && getErrorForField(error, "quantityAvailable") && (
                      <p className="text-red-500 text-sm font-medium">
                        {getErrorForField(error, "quantityAvailable")?.message}
                      </p>
                    )}
                  </TableCell>

                  <TableCell>
                    <Label htmlFor={`price-${index}`} className="sr-only">
                      Price{" "}
                      {currencyDisplaySymbol(activeStore?.currency ?? "GHS")}
                    </Label>
                    {showLoaderForProduct ? null : (
                      <Input
                        id={`price-${index}`}
                        type="number"
                        placeholder="999"
                        onChange={(e) =>
                          handleChange(e, variant.id, "netPrice")
                        }
                        value={variant.netPrice || ""}
                        disabled={shouldDisable(variant)}
                        className={
                          hasPriceError(variant) ? "border-red-500" : ""
                        }
                      />
                    )}
                    {error && getErrorForField(error, "price") && (
                      <p className="text-red-500 text-sm font-medium">
                        {getErrorForField(error, "price")?.message}
                      </p>
                    )}
                  </TableCell>

                  <TableCell>
                    <Label htmlFor={`cost-${index}`} className="sr-only">
                      Cost
                    </Label>
                    {showLoaderForProduct ? null : (
                      <Input
                        id={`cost-${index}`}
                        type="number"
                        placeholder="999"
                        onChange={(e) => handleChange(e, variant.id, "cost")}
                        value={variant.cost || ""}
                        disabled={shouldDisable(variant)}
                      />
                    )}
                  </TableCell>

                  <TableCell>
                    <div className="flex items-center gap-2">
                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => setVisibility(variant.id)}
                              disabled={
                                (productVariants.length > 1 &&
                                  (isLastActiveVariant(index) ||
                                    isLastVisibleVariant(index))) ||
                                isSkuReserved(variant.sku)
                              }
                            >
                              {(variant.isVisible == undefined ||
                                variant.isVisible) && (
                                <EyeOff className="w-4 h-4" />
                              )}

                              {variant.isVisible == false && (
                                <Eye className="w-4 h-4 text-muted-foreground" />
                              )}
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                            {(variant.isVisible == undefined ||
                              variant.isVisible) && <p>Hide</p>}

                            {variant.isVisible == false && <p>Make visible</p>}
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>

                      <TooltipProvider>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Button
                              size="sm"
                              variant="ghost"
                              onClick={() => setOutOfStock(variant.id)}
                              disabled={
                                (variant.quantityAvailable == 0 &&
                                  variant.stock == 0) ||
                                shouldDisable(variant)
                              }
                            >
                              <TriangleAlert className="w-4 h-4 text-yellow-500" />
                            </Button>
                          </TooltipTrigger>
                          <TooltipContent>
                            <p>Set to out of stock</p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>

                      {productVariants.length > 1 && (
                        <TooltipProvider>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                size="sm"
                                variant="ghost"
                                onClick={() =>
                                  handleDeleteAction(
                                    variant.id,
                                    variant.markedForDeletion,
                                  )
                                }
                                disabled={
                                  isLastActiveVariant(index) ||
                                  isSkuReserved(variant.sku)
                                }
                              >
                                {variant.markedForDeletion ? (
                                  <RotateCcw className="w-4 h-4" />
                                ) : (
                                  <TrashIcon className="h-4 w-4 text-red-500" />
                                )}
                              </Button>
                            </TooltipTrigger>
                            {!variant.markedForDeletion && (
                              <TooltipContent>
                                <p>Delete</p>
                              </TooltipContent>
                            )}
                          </Tooltip>
                        </TooltipProvider>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
                {shouldShowTrustPreview && activeProduct && variant.existsInDB && (
                  <LegacyImportTrustPreview
                    activeProduct={activeProduct}
                    areProcessingFeesAbsorbed={
                      resolveTrustedInventoryFinalizationPricingPolicy({
                        persistedAreProcessingFeesAbsorbed:
                          activeProduct.areProcessingFeesAbsorbed,
                      })
                    }
                    finalized={finalizedTrustedInventorySkuIds.has(variant.id)}
                    isContextRefreshing={isLoading || showLoaderForProduct}
                    onFinalized={handleTrustedInventoryFinalized}
                    onMakeVisible={setVisibility}
                    reservationType={getReservationType(variant.sku)}
                    storeId={activeStore?._id}
                    variant={variant}
                  />
                )}
              </Fragment>
            ))}
          </TableBody>
        </Table>
      )}
      <CardFooter className="justify-center pt-4">
        <Button
          size="sm"
          variant="ghost"
          className="gap-1 text-muted-foreground"
          onClick={addRow}
        >
          <PlusCircledIcon className="h-3.5 w-3.5" />
          Add Variant
        </Button>
      </CardFooter>

      <BarcodeQRViewer
        open={qrViewerOpen}
        onOpenChange={setQrViewerOpen}
        barcode={selectedVariant?.barcode || ""}
        sku={selectedVariant?.sku || ""}
        productName={activeProduct?.name}
        productId={activeProduct?._id}
      />

      <AlertModal
        isOpen={clearBarcodeModalOpen}
        onClose={handleClearBarcodeCancel}
        onConfirm={handleClearBarcodeConfirm}
        loading={isClearingBarcode}
        title="Clear Barcode?"
        description="Are you sure you want to clear this barcode? This action will remove the barcode value"
        ctaText="Clear"
      />
    </>
  );
}
