import { ImageFile } from "../ui/image-uploader";

export type ProductVariant = {
  id: string;
  sku?: string;
  barcode?: string;
  barcodeAutoGenerated?: boolean;
  barcodePersistedInDb?: boolean;
  stock?: number;
  quantityAvailable?: number;
  isVisible?: boolean;
  cost?: number;
  price?: number;
  netPrice?: number;
  length?: number;
  color?: string;
  colorName?: string;
  size?: string;
  weight?: string;
  markedForDeletion?: boolean;
  existsInDB?: boolean;
  images: ImageFile[];
};
