import { v } from "convex/values";

export const reportingSourceDomainSchema = v.union(
  v.literal("pos"),
  v.literal("storefront"),
  v.literal("service"),
  v.literal("payments"),
  v.literal("inventory"),
  v.literal("procurement"),
  v.literal("daily_close"),
);

export const reportingFactTypeSchema = v.union(
  v.literal("sale"),
  v.literal("discount"),
  v.literal("refund"),
  v.literal("void"),
  v.literal("correction"),
  v.literal("payment"),
  v.literal("return"),
  v.literal("inventory_receipt"),
  v.literal("inventory_issue"),
  v.literal("inventory_adjustment"),
  v.literal("procurement_commitment"),
  v.literal("procurement_receipt"),
  v.literal("close_snapshot"),
  v.literal("post_close_adjustment"),
);

export const reportingCompletenessSchema = v.union(
  v.literal("complete"),
  v.literal("provisional"),
  v.literal("partial"),
  v.literal("stale"),
  v.literal("unavailable"),
);

export const reportingLimitingReasonSchema = v.union(
  v.literal("unauthorized"),
  v.literal("cross_store_reference"),
  v.literal("duplicate_conflict"),
  v.literal("source_incomplete"),
  v.literal("source_unsynchronized"),
  v.literal("pre_cutover_unknown"),
  v.literal("uncosted"),
  v.literal("processing_delayed"),
  v.literal("processing_failed"),
  v.literal("reconciliation_drift"),
  v.literal("rebuild_in_progress"),
  v.literal("rebuild_failed"),
  v.literal("version_incompatible"),
  v.literal("mixed_currency"),
  v.literal("projection_stale"),
  v.literal("evidence_truncated"),
);

export const reportingIngressSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  sourceDomain: reportingSourceDomainSchema,
  sourceEventType: v.string(),
  businessEventKey: v.string(),
  linkedBusinessEventKey: v.optional(v.string()),
  adapterVersion: v.number(),
  factContractVersion: v.number(),
  occurredAt: v.number(),
  acceptedAt: v.number(),
  synchronizedAt: v.optional(v.number()),
  currencyCode: v.optional(v.string()),
  currencyMinorUnitScale: v.optional(v.number()),
  grossAmountMinor: v.optional(v.number()),
  discountAmountMinor: v.optional(v.number()),
  netAmountMinor: v.optional(v.number()),
  taxAmountMinor: v.optional(v.number()),
  settlementAmountMinor: v.optional(v.number()),
  priorSettlementMethod: v.optional(v.string()),
  correctedSettlementMethod: v.optional(v.string()),
  quantity: v.optional(v.number()),
  closeSnapshot: v.optional(
    v.object({
      acceptedDeficitAdjustmentMinor: v.number(),
      acceptedNetSalesMinor: v.number(),
      acceptedRefundsMinor: v.number(),
      completeness: v.union(v.literal("complete"), v.literal("partial")),
      snapshotVersion: v.number(),
      supersedesCloseId: v.optional(v.string()),
    }),
  ),
  contentFingerprint: v.string(),
  status: v.union(
    v.literal("pending"),
    v.literal("processing"),
    v.literal("processed"),
    v.literal("conflict"),
    v.literal("quarantined"),
  ),
  scheduledAt: v.number(),
  processedAt: v.optional(v.number()),
  conflictAt: v.optional(v.number()),
  attemptCount: v.optional(v.number()),
  firstFailureAt: v.optional(v.number()),
  latestFailureAt: v.optional(v.number()),
  latestFailureCode: v.optional(v.string()),
  lastRecoveryAttemptAt: v.optional(v.number()),
  recoveryDisposition: v.optional(
    v.union(
      v.literal("retry_pending"),
      v.literal("retry_scheduled"),
      v.literal("recovered"),
      v.literal("quarantined"),
      v.literal("waived"),
      v.literal("superseded"),
    ),
  ),
  projectionScheduledAt: v.optional(v.number()),
});

export const reportingIngressSourceReferenceSchema = v.object({
  ingressId: v.id("reportingIngress"),
  storeId: v.id("store"),
  sourceType: v.string(),
  sourceId: v.string(),
  relation: v.union(
    v.literal("owns"),
    v.literal("supports"),
    v.literal("corrects"),
    v.literal("reverses"),
    v.literal("supersedes"),
  ),
  createdAt: v.number(),
});

export const reportingIngressLineSchema = v.object({
  ingressId: v.id("reportingIngress"),
  storeId: v.id("store"),
  lineKey: v.string(),
  lineKind: v.union(
    v.literal("merchandise"),
    v.literal("service"),
    v.literal("delivery"),
    v.literal("tax"),
  ),
  productSkuId: v.optional(v.id("productSku")),
  canonicalProductSkuId: v.optional(v.id("productSku")),
  recognitionProductSkuId: v.optional(v.id("productSku")),
  originalProductSkuId: v.optional(v.id("productSku")),
  provisionalProductSkuId: v.optional(v.id("productSku")),
  productId: v.optional(v.id("product")),
  recognitionProductId: v.optional(v.id("product")),
  recognitionCategoryId: v.optional(v.id("category")),
  pendingCheckoutItemId: v.optional(v.id("posPendingCheckoutItem")),
  inventoryImportProvisionalSkuId: v.optional(
    v.id("inventoryImportProvisionalSku"),
  ),
  attributionKind: v.optional(
    v.union(
      v.literal("direct"),
      v.literal("pending_checkout"),
      v.literal("inventory_import"),
    ),
  ),
  attributionVersion: v.optional(v.number()),
  channel: v.optional(
    v.union(v.literal("pos"), v.literal("storefront"), v.literal("service")),
  ),
  serviceCaseId: v.optional(v.id("serviceCase")),
  categoryId: v.optional(v.id("category")),
  quantity: v.number(),
  originalQuantity: v.optional(v.number()),
  unitPriceMinor: v.optional(v.number()),
  allocatedDiscountMinor: v.optional(v.number()),
  recognizedNetAmountMinor: v.optional(v.number()),
  grossAmountMinor: v.optional(v.number()),
  discountAmountMinor: v.optional(v.number()),
  netAmountMinor: v.optional(v.number()),
  taxAmountMinor: v.optional(v.number()),
  cogsKnownMinor: v.optional(v.number()),
  valuationCurrencyCode: v.optional(v.string()),
  valuationCurrencyMinorUnitScale: v.optional(v.number()),
  cogsKnownQuantity: v.optional(v.number()),
  cogsUncoveredQuantity: v.optional(v.number()),
  costStatus: v.union(
    v.literal("known"),
    v.literal("partial"),
    v.literal("unknown"),
    v.literal("not_applicable"),
  ),
  sourceLabel: v.optional(v.string()),
  inventoryEffectId: v.optional(v.id("reportingInventoryEffect")),
  coveredRevenueMinor: v.optional(v.number()),
  adjustmentKind: v.optional(v.literal("deficit_cogs_revaluation")),
  expectedInboundAt: v.optional(v.number()),
  procurementSignal: v.optional(
    v.union(
      v.literal("commitment"),
      v.literal("receipt"),
      v.literal("short_receipt"),
    ),
  ),
  commitmentConfirmed: v.optional(v.boolean()),
  createdAt: v.number(),
});

export const reportingIngressConflictSchema = v.object({
  ingressId: v.id("reportingIngress"),
  storeId: v.id("store"),
  sourceDomain: reportingSourceDomainSchema,
  businessEventKey: v.string(),
  expectedFingerprint: v.string(),
  receivedFingerprint: v.string(),
  materialFields: v.array(v.string()),
  detectedAt: v.number(),
  status: v.union(v.literal("open"), v.literal("resolved")),
  resolvedAt: v.optional(v.number()),
  resolutionRunId: v.optional(v.id("reportingRun")),
});

export const reportingFactSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  ingressId: v.optional(v.id("reportingIngress")),
  factType: reportingFactTypeSchema,
  factContractVersion: v.number(),
  metricContractVersion: v.number(),
  sourceDomain: reportingSourceDomainSchema,
  businessEventKey: v.string(),
  linkedBusinessEventKey: v.optional(v.string()),
  sourceLineKey: v.optional(v.string()),
  productSkuId: v.optional(v.id("productSku")),
  canonicalProductSkuId: v.optional(v.id("productSku")),
  recognitionProductSkuId: v.optional(v.id("productSku")),
  originalProductSkuId: v.optional(v.id("productSku")),
  provisionalProductSkuId: v.optional(v.id("productSku")),
  productId: v.optional(v.id("product")),
  recognitionProductId: v.optional(v.id("product")),
  recognitionCategoryId: v.optional(v.id("category")),
  pendingCheckoutItemId: v.optional(v.id("posPendingCheckoutItem")),
  inventoryImportProvisionalSkuId: v.optional(
    v.id("inventoryImportProvisionalSku"),
  ),
  attributionKind: v.optional(
    v.union(
      v.literal("direct"),
      v.literal("pending_checkout"),
      v.literal("inventory_import"),
    ),
  ),
  attributionVersion: v.optional(v.number()),
  attributionConflictPriorCompleteness: v.optional(
    reportingCompletenessSchema,
  ),
  attributionConflictPriorLimitingReason: v.optional(
    reportingLimitingReasonSchema,
  ),
  channel: v.optional(
    v.union(v.literal("pos"), v.literal("storefront"), v.literal("service")),
  ),
  serviceCaseId: v.optional(v.id("serviceCase")),
  categoryId: v.optional(v.id("category")),
  revenueKind: v.optional(
    v.union(
      v.literal("merchandise"),
      v.literal("service"),
      v.literal("delivery"),
      v.literal("tax"),
      v.literal("refund"),
    ),
  ),
  priorSettlementMethod: v.optional(v.string()),
  correctedSettlementMethod: v.optional(v.string()),
  contentFingerprint: v.string(),
  occurrenceAt: v.number(),
  acceptedAt: v.number(),
  synchronizedAt: v.optional(v.number()),
  recognitionAt: v.number(),
  operatingDate: v.string(),
  timezoneVersionId: v.optional(v.id("storeTimezoneVersion")),
  timezoneVersionHash: v.optional(v.string()),
  scheduleContext: v.optional(
    v.union(
      v.literal("within_hours"),
      v.literal("outside_hours"),
      v.literal("closed"),
      v.literal("unavailable"),
    ),
  ),
  scheduleVersionId: v.optional(v.id("storeSchedule")),
  historicalInterpretationPolicyId: v.optional(
    v.id("reportingHistoricalInterpretationPolicy"),
  ),
  historicalInterpretationPolicyHash: v.optional(v.string()),
  currencyCode: v.optional(v.string()),
  currencyMinorUnitScale: v.optional(v.number()),
  revenueCurrencyCode: v.optional(v.string()),
  revenueCurrencyMinorUnitScale: v.optional(v.number()),
  valuationCurrencyCode: v.optional(v.string()),
  valuationCurrencyMinorUnitScale: v.optional(v.number()),
  amountMinor: v.optional(v.number()),
  cogsKnownMinor: v.optional(v.number()),
  cogsKnownQuantity: v.optional(v.number()),
  cogsUncoveredQuantity: v.optional(v.number()),
  costStatus: v.optional(
    v.union(
      v.literal("known"),
      v.literal("partial"),
      v.literal("unknown"),
      v.literal("not_applicable"),
    ),
  ),
  quantity: v.optional(v.number()),
  originalQuantity: v.optional(v.number()),
  unitPriceMinor: v.optional(v.number()),
  allocatedDiscountMinor: v.optional(v.number()),
  recognizedNetAmountMinor: v.optional(v.number()),
  inventoryEffectId: v.optional(v.id("reportingInventoryEffect")),
  coveredRevenueMinor: v.optional(v.number()),
  adjustmentKind: v.optional(v.literal("deficit_cogs_revaluation")),
  inventoryContributionKind: v.optional(
    v.union(
      v.literal("sellable_return_cogs_reversal"),
      v.literal("exchange_replacement_cogs"),
      v.literal("inventory_consumed"),
      v.literal("inventory_consumed_reversal"),
    ),
  ),
  closeSnapshot: v.optional(
    v.object({
      acceptedDeficitAdjustmentMinor: v.number(),
      acceptedNetSalesMinor: v.number(),
      acceptedRefundsMinor: v.number(),
      completeness: v.union(v.literal("complete"), v.literal("partial")),
      snapshotVersion: v.number(),
      supersedesCloseId: v.optional(v.string()),
    }),
  ),
  expectedInboundAt: v.optional(v.number()),
  procurementSignal: v.optional(
    v.union(
      v.literal("commitment"),
      v.literal("receipt"),
      v.literal("short_receipt"),
    ),
  ),
  commitmentConfirmed: v.optional(v.boolean()),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  status: v.union(
    v.literal("canonical"),
    v.literal("superseded"),
    v.literal("quarantined"),
  ),
  supersedesFactId: v.optional(v.id("reportingFact")),
  projectionStatus: v.optional(
    v.union(v.literal("pending"), v.literal("completed"), v.literal("failed")),
  ),
  projectionAttemptCount: v.optional(v.number()),
  projectionLastAttemptAt: v.optional(v.number()),
  projectionLatestFailureAt: v.optional(v.number()),
  projectionLatestFailureCode: v.optional(v.string()),
  projectedAt: v.optional(v.number()),
  createdAt: v.number(),
});

export const reportingFactSourceReferenceSchema = v.object({
  factId: v.id("reportingFact"),
  storeId: v.id("store"),
  sourceType: v.string(),
  sourceId: v.string(),
  relation: v.union(
    v.literal("owns"),
    v.literal("supports"),
    v.literal("corrects"),
    v.literal("reverses"),
    v.literal("supersedes"),
  ),
  createdAt: v.number(),
});

export const reportingFactProcessingAttemptSchema = v.object({
  ingressId: v.id("reportingIngress"),
  storeId: v.id("store"),
  attempt: v.number(),
  outcome: v.union(
    v.literal("started"),
    v.literal("succeeded"),
    v.literal("deferred"),
    v.literal("failed"),
  ),
  safeReason: v.optional(v.string()),
  safeCode: v.optional(v.string()),
  adapterVersion: v.optional(v.number()),
  factContractVersion: v.optional(v.number()),
  metricContractVersion: v.optional(v.number()),
  projectionContractVersion: v.optional(v.number()),
  recoveryDisposition: v.optional(
    v.union(
      v.literal("retry_pending"),
      v.literal("retry_scheduled"),
      v.literal("recovered"),
      v.literal("quarantined"),
    ),
  ),
  firstFailureAt: v.optional(v.number()),
  latestFailureAt: v.optional(v.number()),
  startedAt: v.number(),
  completedAt: v.optional(v.number()),
});

export const reportingSkuAttributionSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  pendingCheckoutItemId: v.id("posPendingCheckoutItem"),
  originalProductId: v.optional(v.id("product")),
  originalProductSkuId: v.id("productSku"),
  canonicalProductId: v.optional(v.id("product")),
  canonicalProductSkuId: v.id("productSku"),
  attributionKind: v.literal("pending_checkout"),
  attributionVersion: v.number(),
  materialSequence: v.optional(v.number()),
  conflictFingerprint: v.optional(v.string()),
  status: v.union(
    v.literal("pending"),
    v.literal("completed"),
    v.literal("conflict"),
  ),
  cursor: v.optional(v.string()),
  attemptCount: v.number(),
  firstFailureAt: v.optional(v.number()),
  latestFailureAt: v.optional(v.number()),
  latestFailureCode: v.optional(v.string()),
  recoveryDisposition: v.union(
    v.literal("retry_pending"),
    v.literal("retry_scheduled"),
    v.literal("recovered"),
  ),
  createdAt: v.number(),
  updatedAt: v.number(),
  completedAt: v.optional(v.number()),
});
