import { v } from "convex/values";
import {
  reportingLimitingReasonSchema,
  reportingSourceDomainSchema,
} from "./facts";
import { reportingProjectionKindSchema } from "./projections";

export const reportingRunSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  runType: v.union(
    v.literal("identity_backfill"),
    v.literal("backfill"),
    v.literal("rebuild"),
    v.literal("reconciliation"),
    v.literal("repair"),
    v.literal("activation"),
    v.literal("rollback"),
    v.literal("export"),
    v.literal("custom_range"),
    v.literal("cutover"),
  ),
  domain: v.string(),
  operation: v.string(),
  requestKey: v.optional(v.string()),
  generationId: v.optional(v.id("reportingProjectionGeneration")),
  sourceGenerationId: v.optional(v.id("reportingProjectionGeneration")),
  sourceGenerationIds: v.optional(
    v.array(v.id("reportingProjectionGeneration")),
  ),
  expectedPriorGenerationId: v.optional(v.id("reportingProjectionGeneration")),
  previewRunId: v.optional(v.id("reportingRun")),
  backfillApplyManifestId: v.optional(
    v.id("reportingBackfillApplyManifest"),
  ),
  rangeStartDate: v.optional(v.string()),
  rangeEndDate: v.optional(v.string()),
  expiresAt: v.optional(v.number()),
  resultStorageId: v.optional(v.id("_storage")),
  exportChunkCount: v.optional(v.number()),
  exportPageComplete: v.optional(v.boolean()),
  actorKind: v.union(v.literal("human"), v.literal("automation")),
  actorUserId: v.optional(v.id("athenaUser")),
  automationIdentity: v.optional(v.string()),
  factContractVersion: v.number(),
  metricContractVersion: v.number(),
  projectionContractVersion: v.number(),
  periodStart: v.optional(v.number()),
  periodEnd: v.optional(v.number()),
  frozenWatermark: v.optional(v.number()),
  cursor: v.optional(v.string()),
  status: v.union(
    v.literal("pending"),
    v.literal("running"),
    v.literal("paused"),
    v.literal("completed"),
    v.literal("failed"),
    v.literal("cancelled"),
    v.literal("expired"),
  ),
  processedCount: v.number(),
  failedCount: v.number(),
  plannedCount: v.optional(v.number()),
  createdCount: v.optional(v.number()),
  existingCount: v.optional(v.number()),
  excludedCount: v.optional(v.number()),
  conflictCount: v.optional(v.number()),
  quarantinedCount: v.optional(v.number()),
  eligibleCount: v.optional(v.number()),
  omittedCount: v.optional(v.number()),
  duplicateCount: v.optional(v.number()),
  unknownCount: v.optional(v.number()),
  unknownFieldCount: v.optional(v.number()),
  inferredCount: v.optional(v.number()),
  coverageBasisPoints: v.optional(v.number()),
  historicalInterpretationPolicyId: v.optional(
    v.id("reportingHistoricalInterpretationPolicy"),
  ),
  historicalInterpretationPolicyHash: v.optional(v.string()),
  createdAt: v.number(),
  startedAt: v.optional(v.number()),
  completedAt: v.optional(v.number()),
});

export const reportingExportChunkSchema = v.object({
  runId: v.id("reportingRun"),
  storeId: v.id("store"),
  generationId: v.id("reportingProjectionGeneration"),
  sequence: v.number(),
  inputCursor: v.optional(v.string()),
  nextCursor: v.string(),
  rowCount: v.number(),
  content: v.string(),
  createdAt: v.number(),
});

export const reportingRunEventSchema = v.object({
  runId: v.id("reportingRun"),
  storeId: v.id("store"),
  sequence: v.number(),
  eventType: v.string(),
  outcome: v.string(),
  safeReason: v.optional(v.string()),
  cursor: v.optional(v.string()),
  processedCount: v.optional(v.number()),
  failedCount: v.optional(v.number()),
  plannedCount: v.optional(v.number()),
  createdCount: v.optional(v.number()),
  existingCount: v.optional(v.number()),
  excludedCount: v.optional(v.number()),
  conflictCount: v.optional(v.number()),
  quarantinedCount: v.optional(v.number()),
  eligibleCount: v.optional(v.number()),
  omittedCount: v.optional(v.number()),
  duplicateCount: v.optional(v.number()),
  unknownCount: v.optional(v.number()),
  unknownFieldCount: v.optional(v.number()),
  inferredCount: v.optional(v.number()),
  coverageBasisPoints: v.optional(v.number()),
  sourceDomain: v.optional(reportingSourceDomainSchema),
  occurredAt: v.number(),
});

export const reportingBackfillSourceAuditSchema = v.object({
  runId: v.id("reportingRun"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  sourceDomain: reportingSourceDomainSchema,
  mode: v.union(v.literal("preview"), v.literal("apply")),
  outcome: v.union(
    v.literal("covered"),
    v.literal("partial"),
    v.literal("blocked"),
  ),
  plannedCount: v.number(),
  createdCount: v.number(),
  existingCount: v.number(),
  excludedCount: v.number(),
  conflictCount: v.number(),
  quarantinedCount: v.number(),
  eligibleCount: v.number(),
  omittedCount: v.number(),
  duplicateCount: v.number(),
  unknownCount: v.number(),
  unknownFieldCount: v.number(),
  coverageBasisPoints: v.number(),
  policyId: v.optional(v.id("reportingHistoricalInterpretationPolicy")),
  policyHash: v.optional(v.string()),
  inferredCount: v.optional(v.number()),
  updatedAt: v.number(),
});

export const reportingBackfillPreviewItemSchema = v.object({
  runId: v.id("reportingRun"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  sourceDomain: reportingSourceDomainSchema,
  businessEventKey: v.string(),
  candidateFingerprint: v.string(),
  outcome: v.union(
    v.literal("conflict"),
    v.literal("created"),
    v.literal("excluded"),
    v.literal("existing"),
    v.literal("quarantined"),
  ),
  createdAt: v.number(),
  policyId: v.optional(v.id("reportingHistoricalInterpretationPolicy")),
  policyHash: v.optional(v.string()),
  inferredFields: v.optional(v.array(v.string())),
  originallyMissingFields: v.optional(v.array(v.string())),
});

export const reportingHistoricalInterpretationPolicySchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  version: v.number(),
  status: v.union(
    v.literal("draft"),
    v.literal("approved"),
    v.literal("superseded"),
    v.literal("revoked"),
  ),
  intervalStart: v.number(),
  intervalEnd: v.number(),
  timezone: v.string(),
  weeklyWindowsJson: v.string(),
  dateExceptionsJson: v.string(),
  revenueCurrencyCode: v.string(),
  revenueCurrencyMinorUnitScale: v.number(),
  evidenceSummary: v.string(),
  contentHash: v.string(),
  approvalHash: v.optional(v.string()),
  createdByUserId: v.id("athenaUser"),
  approvedByUserId: v.optional(v.id("athenaUser")),
  createdAt: v.number(),
  approvedAt: v.optional(v.number()),
  supersededAt: v.optional(v.number()),
  revokedAt: v.optional(v.number()),
});

export const reportingHistoricalInterpretationEvidenceSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  policyId: v.optional(v.id("reportingHistoricalInterpretationPolicy")),
  policyHash: v.optional(v.string()),
  factId: v.optional(v.id("reportingFact")),
  sourceDomain: reportingSourceDomainSchema,
  businessEventKey: v.string(),
  inferredFields: v.array(v.string()),
  originallyMissingFields: v.array(v.string()),
  createdAt: v.number(),
});

export const reportingBackfillApplyManifestSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  runId: v.id("reportingRun"),
  previewRunId: v.id("reportingRun"),
  policyId: v.optional(v.id("reportingHistoricalInterpretationPolicy")),
  policyHash: v.optional(v.string()),
  status: v.union(
    v.literal("building"),
    v.literal("sealed"),
    v.literal("consuming"),
    v.literal("completed"),
    v.literal("failed"),
    v.literal("cancelled"),
  ),
  digest: v.optional(v.string()),
  entryCount: v.number(),
  createdAt: v.number(),
  updatedAt: v.number(),
  sealedAt: v.optional(v.number()),
  completedAt: v.optional(v.number()),
  cleanupEligibleAt: v.optional(v.number()),
});

export const reportingBackfillApplyManifestItemSchema = v.object({
  manifestId: v.id("reportingBackfillApplyManifest"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  sequence: v.number(),
  sourceDomain: reportingSourceDomainSchema,
  businessEventKey: v.string(),
  candidateFingerprint: v.string(),
  outcome: v.union(
    v.literal("conflict"),
    v.literal("created"),
    v.literal("excluded"),
    v.literal("existing"),
    v.literal("quarantined"),
  ),
  sanitizedCandidateJson: v.string(),
  inferredFields: v.array(v.string()),
  originallyMissingFields: v.array(v.string()),
  createdAt: v.number(),
});

export const reportingCutoverPreviewItemSchema = v.object({
  runId: v.id("reportingRun"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  productSkuId: v.id("productSku"),
  sourceWatermark: v.number(),
  onHandQuantity: v.number(),
  sellableQuantity: v.number(),
  currencyCode: v.optional(v.string()),
  unitCostMinor: v.optional(v.number()),
  costedQuantity: v.number(),
  uncostedQuantity: v.number(),
  knownCostPoolMinor: v.number(),
  unresolvedDeficitQuantity: v.number(),
  acceptedByRunId: v.optional(v.id("reportingRun")),
  acceptedAt: v.optional(v.number()),
  createdAt: v.number(),
});

export const reportingReconciliationAccumulatorSchema = v.object({
  runId: v.id("reportingRun"),
  generationId: v.id("reportingProjectionGeneration"),
  storeId: v.id("store"),
  source: v.union(
    v.literal("expected"),
    v.literal("candidate"),
    v.literal("active"),
    v.literal("evidence"),
    v.literal("expected_evidence"),
  ),
  logicalKey: v.string(),
  currencyKey: v.string(),
  metric: v.string(),
  operatingDate: v.optional(v.string()),
  productSkuId: v.optional(v.id("productSku")),
  value: v.number(),
  rowCount: v.number(),
  updatedAt: v.number(),
});

export const reportingProjectionHealthSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  sourceDomain: reportingSourceDomainSchema,
  projectionKind: reportingProjectionKindSchema,
  activeGenerationId: v.optional(v.id("reportingProjectionGeneration")),
  factContractVersion: v.number(),
  metricContractVersion: v.number(),
  projectionContractVersion: v.number(),
  processingWatermark: v.optional(v.number()),
  freshnessLagMs: v.optional(v.number()),
  quarantinedCount: v.number(),
  backfillState: v.optional(v.string()),
  latestSuccessfulReconciliationAt: v.optional(v.number()),
  limitingReason: v.optional(reportingLimitingReasonSchema),
  updatedAt: v.number(),
});

export const reportingQuarantineSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  sourceDomain: reportingSourceDomainSchema,
  ingressId: v.optional(v.id("reportingIngress")),
  factId: v.optional(v.id("reportingFact")),
  inventoryEffectId: v.optional(v.id("reportingInventoryEffect")),
  safeCode: v.string(),
  safeFingerprint: v.string(),
  status: v.union(v.literal("open"), v.literal("resolved")),
  detectedAt: v.number(),
  resolvedAt: v.optional(v.number()),
  resolutionRunId: v.optional(v.id("reportingRun")),
});

export const reportingIntegrityAttemptSchema = v.object({
  storeId: v.optional(v.id("store")),
  requestedStoreRef: v.optional(v.string()),
  operation: v.string(),
  outcome: v.union(
    v.literal("denied"),
    v.literal("conflict"),
    v.literal("invalid_version"),
  ),
  safeReason: v.string(),
  actorRef: v.optional(v.string()),
  occurredAt: v.number(),
});

export const reportingIdentityMigrationRunSchema = v.object({
  operation: v.union(
    v.literal("preview"),
    v.literal("apply"),
    v.literal("rollback"),
  ),
  automationIdentity: v.string(),
  previewRunId: v.optional(v.id("reportingIdentityMigrationRun")),
  status: v.union(
    v.literal("running"),
    v.literal("completed"),
    v.literal("blocked"),
  ),
  cursor: v.optional(v.string()),
  scannedCount: v.number(),
  changedCount: v.number(),
  conflictCount: v.number(),
  coverageComplete: v.optional(v.boolean()),
  startedAt: v.number(),
  updatedAt: v.number(),
  completedAt: v.optional(v.number()),
});

export const reportingIdentityMigrationCandidateSchema = v.object({
  runId: v.id("reportingIdentityMigrationRun"),
  userId: v.id("athenaUser"),
  normalizedIdentityFingerprint: v.string(),
  action: v.union(
    v.literal("unchanged"),
    v.literal("update"),
    v.literal("conflict"),
  ),
  createdAt: v.number(),
  updatedAt: v.number(),
});
