import { v } from "convex/values";
import {
  reportingCompletenessSchema,
  reportingFactTypeSchema,
  reportingLimitingReasonSchema,
  reportingSourceDomainSchema,
} from "./facts";

export const reportingProjectionKindSchema = v.union(
  v.literal("store_day"),
  v.literal("sku_day"),
  v.literal("current_inventory"),
  v.literal("custom_range"),
  v.literal("attention"),
  v.literal("storefront_engagement"),
);

export const reportingAttentionCodeSchema = v.union(
  v.literal("source_integrity"),
  v.literal("missing_cost"),
  v.literal("refund_void_correction"),
  v.literal("late_inbound"),
  v.literal("short_receipt"),
  v.literal("missing_inbound_cover"),
  v.literal("low_cover"),
  v.literal("cash_variance"),
);

export const reportingAttentionRouteSchema = v.union(
  v.literal("terminal_health"),
  v.literal("product_edit"),
  v.literal("sku_activity"),
  v.literal("transactions"),
  v.literal("procurement"),
  v.literal("cash_controls"),
);

const reportingAttentionInputValueSchema = v.union(
  v.number(),
  v.boolean(),
  v.string(),
  v.null(),
);

const reportingAttentionThresholdValueSchema = v.union(v.number(), v.boolean());

export const reportingAttentionReasonSchema = v.object({
  code: reportingAttentionCodeSchema,
  inputs: v.record(v.string(), reportingAttentionInputValueSchema),
  limitation: v.union(v.string(), v.null()),
  route: reportingAttentionRouteSchema,
  ruleVersion: v.number(),
  threshold: v.record(v.string(), reportingAttentionThresholdValueSchema),
});

export const reportingProjectionGenerationSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  projectionKind: reportingProjectionKindSchema,
  projectionContractVersion: v.number(),
  factContractVersion: v.number(),
  metricContractVersion: v.number(),
  sourceWatermark: v.number(),
  stableWatermark: v.optional(v.number()),
  rangeStartDate: v.optional(v.string()),
  rangeEndDate: v.optional(v.string()),
  status: v.union(
    v.literal("building"),
    v.literal("catching_up"),
    v.literal("reconciling"),
    v.literal("verified"),
    v.literal("active"),
    v.literal("superseded"),
    v.literal("failed"),
  ),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  runId: v.id("reportingRun"),
  createdAt: v.number(),
  verifiedAt: v.optional(v.number()),
  activatedAt: v.optional(v.number()),
  supersededAt: v.optional(v.number()),
});

export const reportingProjectionActivationSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  projectionKind: reportingProjectionKindSchema,
  generationId: v.id("reportingProjectionGeneration"),
  priorGenerationId: v.optional(v.id("reportingProjectionGeneration")),
  expectedPriorGenerationId: v.optional(v.id("reportingProjectionGeneration")),
  projectionContractVersion: v.number(),
  factContractVersion: v.number(),
  metricContractVersion: v.number(),
  activatedByUserId: v.optional(v.id("athenaUser")),
  activationRunId: v.id("reportingRun"),
  activatedAt: v.number(),
  supersededAt: v.optional(v.number()),
});

const projectionValueFields = {
  generationId: v.id("reportingProjectionGeneration"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  metric: v.string(),
  metricContractVersion: v.number(),
  currencyCode: v.optional(v.string()),
  currencyMinorUnitScale: v.optional(v.number()),
  knownValue: v.optional(v.number()),
  unknownQuantity: v.optional(v.number()),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  sourceWatermark: v.number(),
  projectedAt: v.number(),
};

export const reportingStoreDayProjectionSchema = v.object({
  ...projectionValueFields,
  operatingDate: v.string(),
  scheduleVersionId: v.id("storeSchedule"),
});

export const reportingSkuDayProjectionSchema = v.object({
  ...projectionValueFields,
  productSkuId: v.id("productSku"),
  operatingDate: v.string(),
  scheduleVersionId: v.id("storeSchedule"),
});

export const reportingCurrentValuationProjectionSchema = v.object({
  ...projectionValueFields,
  productSkuId: v.id("productSku"),
  asOf: v.number(),
});

export const reportingRangeProjectionSchema = v.object({
  ...projectionValueFields,
  rangeStartDate: v.string(),
  rangeEndDate: v.string(),
  productSkuId: v.optional(v.id("productSku")),
});

export const reportingAttentionProjectionSchema = v.object({
  generationId: v.id("reportingProjectionGeneration"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  scope: v.union(v.literal("store"), v.literal("sku")),
  productSkuId: v.optional(v.id("productSku")),
  primaryReason: reportingAttentionCodeSchema,
  reasons: v.array(reportingAttentionReasonSchema),
  ruleVersion: v.number(),
  factContractVersion: v.number(),
  metricContractVersion: v.number(),
  projectionContractVersion: v.number(),
  sourceGenerationIds: v.array(v.id("reportingProjectionGeneration")),
  sourceWatermark: v.number(),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  projectedAt: v.number(),
});

export const reportingDailyCloseProjectionSchema = v.object({
  generationId: v.id("reportingProjectionGeneration"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  operatingDate: v.string(),
  scheduleVersionId: v.id("storeSchedule"),
  acceptedCloseFactId: v.id("reportingFact"),
  acceptedCloseBusinessEventKey: v.string(),
  acceptedAt: v.number(),
  acceptedCloseVersion: v.number(),
  supersedesDailyCloseProjectionId: v.optional(
    v.id("reportingDailyCloseProjection"),
  ),
  acceptedNetSalesMinor: v.number(),
  acceptedRefundsMinor: v.number(),
  acceptedDeficitAdjustmentMinor: v.number(),
  currentNetSalesMinor: v.number(),
  currentRefundsMinor: v.number(),
  currentDeficitAdjustmentMinor: v.number(),
  postCloseNetSalesDeltaMinor: v.number(),
  postCloseRefundsDeltaMinor: v.number(),
  postCloseDeficitAdjustmentDeltaMinor: v.number(),
  postCloseKnownCogsDeltaMinor: v.number(),
  postCloseGrossProfitDeltaMinor: v.number(),
  currencyCode: v.optional(v.string()),
  currencyMinorUnitScale: v.optional(v.number()),
  factContractVersion: v.number(),
  metricContractVersion: v.number(),
  projectionContractVersion: v.number(),
  sourceWatermark: v.number(),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  projectedAt: v.number(),
});

export const reportingSkuInsightProjectionSchema = v.object({
  generationId: v.id("reportingProjectionGeneration"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  productSkuId: v.id("productSku"),
  windowStartDate: v.string(),
  windowEndDate: v.string(),
  activeDays: v.number(),
  netSoldUnits: v.number(),
  returnedUnits: v.number(),
  velocitySufficient: v.boolean(),
  averageUnitsPerActiveDay: v.optional(v.number()),
  onHandQuantity: v.number(),
  sellableQuantity: v.number(),
  projectedDaysOfCover: v.optional(v.number()),
  confirmedInboundQuantity: v.number(),
  outstandingCommitmentQuantity: v.number(),
  expectedInboundAt: v.optional(v.number()),
  shortReceipt: v.boolean(),
  eligibleMerchandiseRevenueMinor: v.number(),
  coveredEligibleRevenueMinor: v.number(),
  uncoveredEligibleRevenueMinor: v.number(),
  knownCogsMinor: v.number(),
  knownGrossProfitMinor: v.number(),
  knownInventoryValueMinor: v.optional(v.number()),
  uncostedOnHandQuantity: v.number(),
  currencyCode: v.optional(v.string()),
  currencyMinorUnitScale: v.optional(v.number()),
  revenueCurrencyCode: v.optional(v.string()),
  revenueCurrencyMinorUnitScale: v.optional(v.number()),
  valuationCurrencyCode: v.optional(v.string()),
  valuationCurrencyMinorUnitScale: v.optional(v.number()),
  revenueCostCoverage: v.union(
    v.literal("known"),
    v.literal("partial"),
    v.literal("unknown"),
    v.literal("mixed_currency"),
  ),
  inventoryCostCoverage: v.union(
    v.literal("known"),
    v.literal("partial"),
    v.literal("unknown"),
    v.literal("mixed_currency"),
  ),
  costCoverageBasisPoints: v.optional(v.number()),
  marginBasisPoints: v.optional(v.number()),
  refundVoidCorrectionCount: v.number(),
  refundVoidCorrectionMinor: v.number(),
  windowScheduleVersionIds: v.array(v.id("storeSchedule")),
  sourceGenerationIds: v.array(v.id("reportingProjectionGeneration")),
  sourceWatermark: v.number(),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  factContractVersion: v.number(),
  metricContractVersion: v.number(),
  projectionContractVersion: v.number(),
  projectedAt: v.number(),
});

export const reportingMetricCoverageSchema = v.object({
  generationId: v.id("reportingProjectionGeneration"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  metric: v.string(),
  sourceDomain: v.string(),
  periodStart: v.number(),
  periodEnd: v.number(),
  latestOccurrenceAt: v.optional(v.number()),
  projectedAt: v.optional(v.number()),
  knownLagMs: v.optional(v.number()),
  omittedCount: v.number(),
  quarantinedCount: v.number(),
  failedCount: v.number(),
  truncated: v.boolean(),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  updatedAt: v.number(),
});

export const reportingProjectionEvidenceSchema = v.object({
  generationId: v.id("reportingProjectionGeneration"),
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  metric: v.string(),
  productSkuId: v.optional(v.id("productSku")),
  recognitionProductSkuId: v.optional(v.id("productSku")),
  originalProductSkuId: v.optional(v.id("productSku")),
  provisionalProductSkuId: v.optional(v.id("productSku")),
  attributionKind: v.optional(
    v.union(
      v.literal("direct"),
      v.literal("pending_checkout"),
      v.literal("inventory_import"),
    ),
  ),
  attributionVersion: v.optional(v.number()),
  channel: v.optional(
    v.union(v.literal("pos"), v.literal("storefront"), v.literal("service")),
  ),
  factId: v.optional(v.id("reportingFact")),
  factType: v.optional(reportingFactTypeSchema),
  inventoryEffectId: v.optional(v.id("reportingInventoryEffect")),
  effectType: v.optional(
    v.union(
      v.literal("receipt"),
      v.literal("sale"),
      v.literal("return"),
      v.literal("adjustment"),
      v.literal("transfer"),
      v.literal("deficit_resolution"),
      v.literal("baseline"),
    ),
  ),
  sourceDomain: reportingSourceDomainSchema,
  businessEventKey: v.string(),
  operatingDate: v.optional(v.string()),
  occurrenceAt: v.number(),
  recognitionAt: v.number(),
  sourceWatermark: v.optional(v.number()),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  amountMinor: v.optional(v.number()),
  quantity: v.optional(v.number()),
  returnedQuantity: v.optional(v.number()),
  returnDisposition: v.optional(
    v.union(
      v.literal("sellable"),
      v.literal("non_restocked"),
      v.literal("damaged"),
      v.literal("missing"),
      v.literal("financial_only"),
    ),
  ),
  originalQuantity: v.optional(v.number()),
  unitPriceMinor: v.optional(v.number()),
  allocatedDiscountMinor: v.optional(v.number()),
  recognizedNetAmountMinor: v.optional(v.number()),
  currencyCode: v.optional(v.string()),
  revenueCurrencyCode: v.optional(v.string()),
  valuationCurrencyCode: v.optional(v.string()),
  createdAt: v.number(),
});

export const reportingSkuEvidenceSchema = v.object({
  organizationId: v.id("organization"),
  storeId: v.id("store"),
  productSkuId: v.id("productSku"),
  recognitionProductSkuId: v.optional(v.id("productSku")),
  originalProductSkuId: v.optional(v.id("productSku")),
  provisionalProductSkuId: v.optional(v.id("productSku")),
  recognitionProductId: v.optional(v.id("product")),
  recognitionCategoryId: v.optional(v.id("category")),
  pendingCheckoutItemId: v.optional(v.id("posPendingCheckoutItem")),
  inventoryImportProvisionalSkuId: v.optional(
    v.id("inventoryImportProvisionalSku"),
  ),
  attributionKind: v.optional(
    v.union(
      v.literal("direct"),
      v.literal("pending_checkout"),
      v.literal("inventory_import"),
    ),
  ),
  attributionVersion: v.optional(v.number()),
  channel: v.optional(
    v.union(v.literal("pos"), v.literal("storefront"), v.literal("service")),
  ),
  identityKey: v.string(),
  evidenceKind: v.union(
    v.literal("fact"),
    v.literal("inventory_effect"),
    v.literal("payment"),
  ),
  contributionState: v.optional(
    v.union(v.literal("contributing"), v.literal("excluded")),
  ),
  exclusionReason: v.optional(v.string()),
  factId: v.optional(v.id("reportingFact")),
  inventoryEffectId: v.optional(v.id("reportingInventoryEffect")),
  paymentAllocationId: v.optional(v.id("paymentAllocation")),
  sourceDomain: reportingSourceDomainSchema,
  businessEventKey: v.string(),
  occurrenceAt: v.number(),
  recognitionAt: v.number(),
  factType: v.optional(reportingFactTypeSchema),
  effectType: v.optional(
    v.union(
      v.literal("receipt"),
      v.literal("sale"),
      v.literal("return"),
      v.literal("adjustment"),
      v.literal("transfer"),
      v.literal("deficit_resolution"),
      v.literal("baseline"),
    ),
  ),
  amountMinor: v.optional(v.number()),
  cogsKnownMinor: v.optional(v.number()),
  knownGrossProfitMinor: v.optional(v.number()),
  quantity: v.optional(v.number()),
  returnedQuantity: v.optional(v.number()),
  returnDisposition: v.optional(
    v.union(
      v.literal("sellable"),
      v.literal("non_restocked"),
      v.literal("damaged"),
      v.literal("missing"),
      v.literal("financial_only"),
    ),
  ),
  originalQuantity: v.optional(v.number()),
  unitPriceMinor: v.optional(v.number()),
  allocatedDiscountMinor: v.optional(v.number()),
  recognizedNetAmountMinor: v.optional(v.number()),
  currencyCode: v.optional(v.string()),
  revenueCurrencyCode: v.optional(v.string()),
  valuationCurrencyCode: v.optional(v.string()),
  costStatus: v.optional(
    v.union(
      v.literal("known"),
      v.literal("partial"),
      v.literal("unknown"),
      v.literal("not_applicable"),
    ),
  ),
  evidenceStatus: v.optional(v.string()),
  linkedBusinessEventKey: v.optional(v.string()),
  refundAdjustmentState: v.optional(
    v.union(
      v.literal("none"),
      v.literal("refunded"),
      v.literal("voided"),
      v.literal("corrected"),
      v.literal("returned"),
      v.literal("revalued"),
    ),
  ),
  completeness: reportingCompletenessSchema,
  limitingReason: v.optional(reportingLimitingReasonSchema),
  sourceRoutes: v.array(
    v.object({
      sourceType: v.string(),
      sourceId: v.string(),
      relation: v.string(),
    }),
  ),
  createdAt: v.number(),
});
