export const accraNeighborhoods = [
  { label: "Adabraka", value: "adabraka" },
  { label: "Adenta", value: "adenta" },
  { label: "Adjiringanor", value: "adjiringanor" },
  { label: "Airport Residential Area", value: "airport_residential" },
  { label: "Ashaley Botwe", value: "ashaley_botwe" },
  { label: "Cantonments", value: "cantonments" },
  { label: "Dansoman", value: "dansoman" },
  { label: "Dzorwulu", value: "dzorwulu" },
  { label: "East Legon", value: "east_legon" },
  { label: "Haatso", value: "haatso" },
  { label: "Kokomlemle", value: "kokomlemle" },
  { label: "Labadi", value: "labadi" },
  { label: "Labone", value: "labone" },
  { label: "Madina", value: "madina" },
  { label: "Osu", value: "osu" },
  { label: "Roman Ridge", value: "roman_ridge" },
  { label: "Spintex", value: "spintex" },
  { label: "Tema", value: "tema" },
  { label: "Tesano", value: "tesano" },
  { label: "Teshie", value: "teshie" },
  { label: "Weija", value: "weija" },
  { label: "West Legon", value: "west_legon" },
];

export const ghanaRegions = [
  { code: "AH", name: "Ahafo" },
  { code: "AA", name: "Ashanti" },
  { code: "BA", name: "Bono" },
  { code: "BE", name: "Bono East" },
  { code: "CP", name: "Central" },
  { code: "EP", name: "Eastern" },
  { code: "GA", name: "Greater Accra" },
  { code: "NE", name: "North East" },
  { code: "NR", name: "Northern" },
  { code: "OT", name: "Oti" },
  { code: "SV", name: "Savannah" },
  { code: "UE", name: "Upper East" },
  { code: "UW", name: "Upper West" },
  { code: "VR", name: "Volta" },
  { code: "WN", name: "Western North" },
  { code: "WR", name: "Western" },
];
