export const ATHENA_CAPABILITY_CATALOG = [
  { id: "administration.destructive", label: "Destructive administration" },
  { id: "administration.maintenance", label: "System maintenance" },
  { id: "appointments.manage", label: "Appointments" },
  { id: "approvals.manage", label: "Operational approvals" },
  { id: "billing.manage", label: "Payment collection and billing" },
  { id: "cash.control.write", label: "Cash controls" },
  { id: "catalog.quick_add", label: "Quick product creation" },
  { id: "catalog.maintain", label: "Catalog maintenance" },
  { id: "catalog.manage", label: "Catalog management" },
  { id: "customer.messaging.send", label: "Customer messaging" },
  { id: "daily_operations.write", label: "Daily operations" },
  { id: "demo.lifecycle", label: "Demo lifecycle" },
  { id: "expense.manage", label: "Expenses" },
  { id: "exports.generate", label: "Data exports" },
  { id: "identity.authenticate", label: "Identity authentication" },
  { id: "identity.manage", label: "Identity management" },
  { id: "integrations.manage", label: "Integrations and provider media" },
  { id: "intelligence.generate", label: "Athena intelligence generation" },
  { id: "intelligence.manage", label: "Athena intelligence management" },
  { id: "inventory.adjust", label: "Inventory adjustments and counts" },
  { id: "inventory.import", label: "Inventory import" },
  { id: "orders.create", label: "Order creation" },
  { id: "orders.fulfill", label: "Order fulfillment" },
  { id: "orders.manage", label: "Order management" },
  { id: "orders.return", label: "Order returns" },
  { id: "organization.manage", label: "Organization management" },
  { id: "payments.refund", label: "Refunds and payment reversals" },
  { id: "permissions.manage", label: "Permissions and invitations" },
  { id: "pos.catalog.manage", label: "POS catalog operations" },
  { id: "pos.customer.manage", label: "POS customers" },
  { id: "pos.recovery.manage", label: "POS recovery" },
  { id: "pos.sale.complete", label: "POS sale completion" },
  { id: "pos.session.manage", label: "POS sessions" },
  { id: "pos.sync.write", label: "POS synchronization" },
  { id: "pos.terminal.manage", label: "POS terminals" },
  { id: "pos.transaction.correct", label: "POS transaction corrections" },
  { id: "pos.transaction.void", label: "POS transaction voids" },
  { id: "procurement.manage", label: "Procurement" },
  { id: "remote_assist.manage", label: "Remote Assist" },
  { id: "reporting.generate", label: "Report generation" },
  { id: "reporting.maintain", label: "Reporting maintenance" },
  { id: "reports.read", label: "Reports read access" },
  { id: "reviews.manage", label: "Reviews" },
  { id: "rewards.manage", label: "Rewards" },
  { id: "service.catalog.manage", label: "Service catalog" },
  { id: "service.cases.manage", label: "Service cases" },
  { id: "service.intake.write", label: "Service intake" },
  { id: "staff.authenticate", label: "Staff authentication and elevation" },
  { id: "staff.communication.write", label: "Staff communication" },
  { id: "staff.manage", label: "Staff management" },
  { id: "store.configure", label: "Store configuration" },
  { id: "storefront.analytics.write", label: "Storefront analytics" },
  { id: "storefront.content.manage", label: "Storefront merchandising" },
  { id: "storefront.session.manage", label: "Storefront sessions" },
] as const;

export type AthenaCapability = (typeof ATHENA_CAPABILITY_CATALOG)[number]["id"];

export const SHARED_DEMO_ALLOWED_CAPABILITIES = [
  "approvals.manage",
  "cash.control.write",
  "catalog.maintain",
  "catalog.quick_add",
  "customer.messaging.send",
  "daily_operations.write",
  // Recording expenses is a first-class POS operation the demo exposes (the
  // /pos/expense route). Without this grant, expense event sync is rejected while
  // sales (pos.sale.complete) succeed.
  "expense.manage",
  "inventory.adjust",
  "orders.fulfill",
  "orders.manage",
  "orders.return",
  "payments.refund",
  "pos.sale.complete",
  "pos.sync.write",
  "pos.transaction.correct",
  "pos.transaction.void",
  "reports.read",
  "reviews.manage",
  "staff.authenticate",
  "staff.communication.write",
] as const satisfies readonly AthenaCapability[];

const EXACT_PUBLIC_WRITE_CAPABILITIES = {
  "inventory/organizations:remove": "administration.destructive",
  "inventory/productSku:nukeProblematicImages": "administration.maintenance",
  "inventory/products:removeAllProductsForStore": "administration.destructive",
  "inventory/stores:patchConfigV2Command": "integrations.manage",
  "inventory/stores:remove": "administration.destructive",
  "operations/staffCredentials:createStaffCredential": "identity.manage",
  "operations/staffCredentials:updateStaffCredential": "identity.manage",
  "operations/staffProfiles:createStaffProfile": "staff.manage",
  "operations/staffProfiles:updateStaffProfile": "staff.manage",
  "pos/public/catalog:quickAddSku": "catalog.quick_add",
  "pos/public/terminals:deleteTerminal": "administration.destructive",
  "pos/public/terminals:registerTerminal": "daily_operations.write",
  "pos/public/transactions:completeTransaction": "pos.sale.complete",
  "pos/public/transactions:createTransactionFromSession": "pos.sale.complete",
  "pos/public/transactions:updateInventory": "inventory.adjust",
  "pos/public/transactions:voidTransaction": "pos.transaction.void",
  "reporting/export:getExportDownloadUrl": "exports.generate",
  "reporting/export:getExportStatus": "exports.generate",
  "reporting/export:requestExport": "exports.generate",
  "serviceOps/serviceCases:recordServicePayment": "billing.manage",
  "storeFront/checkoutSession:cancelOrder": "orders.manage",
  "storeFront/onlineOrder:processReturnExchange": "payments.refund",
  "storeFront/onlineOrder:returnAllItemsToStock": "orders.return",
  "storeFront/onlineOrder:returnItemsToStock": "orders.return",
  "storeFront/onlineOrder:update": "orders.fulfill",
  "storeFront/onlineOrderUtilFns:sendOrderUpdateEmail":
    "customer.messaging.send",
  "storeFront/payment:createTransaction": "billing.manage",
  "storeFront/payment:refundPayment": "payments.refund",
} as const satisfies Record<string, AthenaCapability>;

const PUBLIC_WRITE_MODULE_CAPABILITIES = {
  "cashControls/closeouts": "cash.control.write",
  "cashControls/deposits": "cash.control.write",
  "cloudflare/stream": "integrations.manage",
  "customerMessaging/public": "customer.messaging.send",
  devPatchBadTransaction: "administration.maintenance",
  "intelligence/capabilities/actions": "intelligence.generate",
  "intelligence/runs": "intelligence.manage",
  "inventory/auth": "identity.authenticate",
  "inventory/bannerMessage": "storefront.content.manage",
  "inventory/bestSeller": "storefront.content.manage",
  "inventory/catalogImport": "inventory.import",
  "inventory/categories": "catalog.manage",
  "inventory/colors": "catalog.manage",
  "inventory/complimentaryProduct": "storefront.content.manage",
  "inventory/expenseSessionItems": "expense.manage",
  "inventory/expenseSessions": "expense.manage",
  "inventory/expenseTransactions": "expense.manage",
  "inventory/featuredItem": "storefront.content.manage",
  "inventory/inviteCode": "permissions.manage",
  "inventory/organizations": "organization.manage",
  "inventory/posSessionItems": "pos.session.manage",
  "inventory/posSessions": "pos.session.manage",
  "inventory/productSku": "catalog.manage",
  "inventory/productUtil": "administration.maintenance",
  "inventory/products": "catalog.manage",
  "inventory/promoCode": "storefront.content.manage",
  "inventory/skuSearch": "administration.maintenance",
  "inventory/storeSchedule": "store.configure",
  "inventory/stores": "store.configure",
  "inventory/subcategories": "catalog.manage",
  "llm/storeInsights": "intelligence.generate",
  "llm/userInsights": "intelligence.generate",
  "operations/approvalRequests": "approvals.manage",
  "operations/dailyClose": "daily_operations.write",
  "operations/dailyManagerReportEmail": "customer.messaging.send",
  "operations/dailyOpening": "daily_operations.write",
  "operations/dailyOperationsAutomation": "store.configure",
  "operations/managerElevations": "staff.authenticate",
  "operations/openWorkInventoryReviews": "daily_operations.write",
  "operations/serviceIntake": "service.intake.write",
  "operations/staffCredentials": "staff.authenticate",
  "operations/staffMessages": "staff.communication.write",
  "operations/staffProfiles": "staff.manage",
  "pos/public/catalog": "pos.catalog.manage",
  "pos/public/customers": "pos.customer.manage",
  "pos/public/posRecoveryCodes": "pos.recovery.manage",
  "pos/public/register": "cash.control.write",
  "pos/public/sync": "pos.sync.write",
  "pos/public/telemetry": "pos.sync.write",
  "pos/public/terminalAppSessions": "pos.terminal.manage",
  "pos/public/terminals": "pos.terminal.manage",
  "pos/public/transactions": "pos.transaction.correct",
  "remoteAssist/public": "remote_assist.manage",
  "remoteAssist/transport": "remote_assist.manage",
  "reporting/customRangeRequests": "reporting.generate",
  "reporting/evidence": "reporting.maintain",
  "reporting/export": "exports.generate",
  "reporting/inventory/corrections": "reporting.maintain",
  "reporting/maintenance/authorizedPosBackfill": "reporting.maintain",
  "reporting/maintenance/legacyCompatibility": "reporting.maintain",
  "serviceOps/appointments": "appointments.manage",
  "serviceOps/catalog": "service.catalog.manage",
  "serviceOps/serviceCases": "service.cases.manage",
  "sharedDemo/admission": "demo.lifecycle",
  "sharedDemo/public": "demo.lifecycle",
  "stockOps/adjustments": "inventory.adjust",
  "stockOps/cycleCountDrafts": "inventory.adjust",
  "stockOps/purchaseOrders": "procurement.manage",
  "stockOps/receiving": "procurement.manage",
  "stockOps/vendors": "procurement.manage",
  "storeFront/analytics": "storefront.analytics.write",
  "storeFront/auth": "identity.authenticate",
  "storeFront/bag": "storefront.session.manage",
  "storeFront/checkoutSession": "orders.create",
  "storeFront/guest": "storefront.session.manage",
  "storeFront/offers": "storefront.content.manage",
  "storeFront/onlineOrder": "orders.manage",
  "storeFront/onlineOrderItem": "orders.manage",
  "storeFront/onlineOrderUtilFns": "customer.messaging.send",
  "storeFront/payment": "billing.manage",
  "storeFront/paystackActions": "billing.manage",
  "storeFront/reviews": "reviews.manage",
  "storeFront/rewards": "rewards.manage",
  "storeFront/savedBag": "storefront.session.manage",
  "storeFront/supportTicket": "customer.messaging.send",
} as const satisfies Record<string, AthenaCapability>;

export function classifyAthenaPublicWrite(
  functionName: string,
):
  | { capability: AthenaCapability; decision: "classified" }
  | { decision: "unclassified" } {
  const exact = (
    EXACT_PUBLIC_WRITE_CAPABILITIES as Record<string, AthenaCapability>
  )[functionName];
  if (exact) return { capability: exact, decision: "classified" };

  const separator = functionName.lastIndexOf(":");
  const moduleName =
    separator < 0 ? functionName : functionName.slice(0, separator);
  const capability = (
    PUBLIC_WRITE_MODULE_CAPABILITIES as Record<string, AthenaCapability>
  )[moduleName];
  return capability
    ? { capability, decision: "classified" }
    : { decision: "unclassified" };
}

export function isSharedDemoCapabilityAllowed(capability: AthenaCapability) {
  return (
    SHARED_DEMO_ALLOWED_CAPABILITIES as readonly AthenaCapability[]
  ).includes(capability);
}
