import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../../../../platform/operationAdmission", () => ({
  // The projection is what this suite pins; admission is covered by
  // `coreAdmission.test.ts` and the admission-rail suites.
  admitHttpRead: (_definition: unknown, handler: unknown) => handler,
}));

const { productRoutes } = await import("./products");

const OPERATOR_ONLY_PRODUCT_FIELDS = [
  "areProcessingFeesAbsorbed",
  "createdByUserId",
  "inventoryCount",
  "organizationId",
  "posVisible",
];

const OPERATOR_ONLY_SKU_FIELDS = [
  "barcode",
  "barcodeAutoGenerated",
  "durableQuantityAvailable",
  "inventoryCount",
  "netPrice",
  "pesewasMigratedAt",
  "posVisible",
  "reservedQuantity",
  "unitCost",
];

const LEAKED_FIELDS = [
  ...new Set([...OPERATOR_ONLY_PRODUCT_FIELDS, ...OPERATOR_ONLY_SKU_FIELDS]),
];

function skuDocument() {
  return {
    _id: "productSku_1",
    attributes: { origin: "Ghana" },
    barcode: "000000000123",
    barcodeAutoGenerated: true,
    color: "color_1",
    durableQuantityAvailable: 6,
    images: ["https://example.invalid/a.jpg"],
    inventoryCount: 6,
    isVisible: true,
    length: 20,
    netPrice: 4500,
    pesewasMigratedAt: 1_700_000_000_000,
    posVisible: true,
    price: 5000,
    productId: "product_1",
    productName: "Lace front",
    quantityAvailable: 4,
    reservedQuantity: 2,
    size: "M",
    sku: "LF-20",
    storeId: "store_1",
    unitCost: 2500,
    weight: "200g",
  };
}

function productDocument() {
  return {
    _id: "product_1",
    areProcessingFeesAbsorbed: true,
    attributes: {},
    availability: "live",
    categoryId: "category_1",
    createdByUserId: "athenaUser_1",
    currency: "GHS",
    inventoryCount: 17,
    isVisible: true,
    name: "Lace front",
    organizationId: "organization_1",
    posVisible: false,
    quantityAvailable: 9,
    slug: "lace-front",
    storeId: "store_1",
    subcategoryId: "subcategory_1",
    skus: [skuDocument()],
  };
}

function collectKeys(value: unknown, seen: Set<string> = new Set()) {
  if (Array.isArray(value)) {
    for (const entry of value) collectKeys(entry, seen);
    return seen;
  }
  if (typeof value === "object" && value !== null) {
    for (const [key, entry] of Object.entries(value)) {
      seen.add(key);
      collectKeys(entry, seen);
    }
  }
  return seen;
}

function requestCatalogue(
  path: string,
  env: { runAction?: unknown; runQuery?: unknown },
) {
  return productRoutes.request(
    path,
    { headers: { cookie: "store_id=store_1; organization_id=organization_1" } },
    env as never,
  );
}

let runAction: ReturnType<typeof vi.fn>;
let runQuery: ReturnType<typeof vi.fn>;

beforeEach(() => {
  runAction = vi.fn();
  runQuery = vi.fn();
});

describe("anonymous catalogue routes project the public catalogue shape", () => {
  // The list read is served from a Valkey cache inside `getAllProducts`, so a
  // hit and a miss reach the route as the same whole-document payload. Both are
  // driven here to pin that the projection sits after the cache read.
  it.each([
    ["a cache miss", [productDocument()]],
    ["a cache hit", JSON.parse(JSON.stringify([productDocument()]))],
  ])("drops operator-only fields from GET /products on %s", async (_label, payload) => {
    runAction.mockResolvedValue(payload);

    const response = await requestCatalogue("/?isVisible=true", { runAction });
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.products).toHaveLength(1);
    expect(body.products[0].skus[0].price).toBe(5000);
    for (const field of LEAKED_FIELDS) {
      expect(collectKeys(body)).not.toContain(field);
    }
  });

  it.each([
    ["a cache miss", productDocument()],
    ["a cache hit", JSON.parse(JSON.stringify(productDocument()))],
  ])("drops operator-only fields from GET /products/:productId on %s", async (_label, payload) => {
    runQuery.mockResolvedValue({
      ...payload,
      categoryName: "Wigs",
      categorySlug: "wigs",
    });

    const response = await requestCatalogue("/lace-front?isVisible=true", {
      runQuery,
    });
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.categoryName).toBe("Wigs");
    expect(body.skus[0].sku).toBe("LF-20");
    for (const field of LEAKED_FIELDS) {
      expect(collectKeys(body)).not.toContain(field);
    }
  });

  it("drops operator-only fields from GET /products/bestSellers, including the nested product", async () => {
    runQuery.mockResolvedValue([
      {
        _id: "bestSeller_1",
        rank: 1,
        productSku: { ...skuDocument(), product: productDocument() },
      },
    ]);

    const response = await requestCatalogue("/bestSellers", { runQuery });
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body[0].productSku.price).toBe(5000);
    for (const field of LEAKED_FIELDS) {
      expect(collectKeys(body)).not.toContain(field);
    }
  });

  it("drops operator-only fields from GET /products/featured, including collection products", async () => {
    runQuery.mockResolvedValue([
      {
        _id: "featuredItem_1",
        product: productDocument(),
        category: { _id: "category_1", products: [productDocument()] },
        subcategory: { _id: "subcategory_1", products: [productDocument()] },
      },
    ]);

    const response = await requestCatalogue("/featured", { runQuery });
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body[0].category.products).toHaveLength(1);
    for (const field of LEAKED_FIELDS) {
      expect(collectKeys(body)).not.toContain(field);
    }
  });

  it("keeps the existing error shape when store context is missing", async () => {
    const response = await productRoutes.request("/", {}, { runAction } as never);

    expect(response.status).toBe(404);
    expect(await response.json()).toEqual({ error: "Store id missing" });
  });
});
