/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as app from "../app.js";
import type * as auth from "../auth.js";
import type * as cache_index from "../cache/index.js";
import type * as cashControls_closeouts from "../cashControls/closeouts.js";
import type * as cashControls_deposits from "../cashControls/deposits.js";
import type * as cashControls_paymentAllocationAttribution from "../cashControls/paymentAllocationAttribution.js";
import type * as cloudflare_r2 from "../cloudflare/r2.js";
import type * as cloudflare_stream from "../cloudflare/stream.js";
import type * as constants_countries from "../constants/countries.js";
import type * as constants_email from "../constants/email.js";
import type * as constants_ghana from "../constants/ghana.js";
import type * as constants_payment from "../constants/payment.js";
import type * as crons from "../crons.js";
import type * as customerMessaging_domain from "../customerMessaging/domain.js";
import type * as customerMessaging_internal from "../customerMessaging/internal.js";
import type * as customerMessaging_policy from "../customerMessaging/policy.js";
import type * as customerMessaging_public from "../customerMessaging/public.js";
import type * as customerMessaging_repository from "../customerMessaging/repository.js";
import type * as customerMessaging_token from "../customerMessaging/token.js";
import type * as customerMessaging_webhookSecurity from "../customerMessaging/webhookSecurity.js";
import type * as customerMessaging_whatsappClient from "../customerMessaging/whatsappClient.js";
import type * as customerMessaging_whatsappConfig from "../customerMessaging/whatsappConfig.js";
import type * as devPatchBadTransaction from "../devPatchBadTransaction.js";
import type * as emails_DiscountCode from "../emails/DiscountCode.js";
import type * as emails_DiscountReminder from "../emails/DiscountReminder.js";
import type * as emails_FeedbackRequest from "../emails/FeedbackRequest.js";
import type * as emails_NewOrderAdmin from "../emails/NewOrderAdmin.js";
import type * as emails_OrderEmail from "../emails/OrderEmail.js";
import type * as emails_PosReceiptEmail from "../emails/PosReceiptEmail.js";
import type * as emails_VerificationCode from "../emails/VerificationCode.js";
import type * as env from "../env.js";
import type * as http from "../http.js";
import type * as http_domains_core_routes_analytics from "../http/domains/core/routes/analytics.js";
import type * as http_domains_core_routes_auth from "../http/domains/core/routes/auth.js";
import type * as http_domains_core_routes_bannerMessage from "../http/domains/core/routes/bannerMessage.js";
import type * as http_domains_core_routes_categories from "../http/domains/core/routes/categories.js";
import type * as http_domains_core_routes_colors from "../http/domains/core/routes/colors.js";
import type * as http_domains_core_routes_index from "../http/domains/core/routes/index.js";
import type * as http_domains_core_routes_organizations from "../http/domains/core/routes/organizations.js";
import type * as http_domains_core_routes_products from "../http/domains/core/routes/products.js";
import type * as http_domains_core_routes_stores from "../http/domains/core/routes/stores.js";
import type * as http_domains_core_routes_subcategories from "../http/domains/core/routes/subcategories.js";
import type * as http_domains_customerChannel_routes_bag from "../http/domains/customerChannel/routes/bag.js";
import type * as http_domains_customerChannel_routes_checkout from "../http/domains/customerChannel/routes/checkout.js";
import type * as http_domains_customerChannel_routes_guest from "../http/domains/customerChannel/routes/guest.js";
import type * as http_domains_customerChannel_routes_index from "../http/domains/customerChannel/routes/index.js";
import type * as http_domains_customerChannel_routes_me from "../http/domains/customerChannel/routes/me.js";
import type * as http_domains_customerChannel_routes_offers from "../http/domains/customerChannel/routes/offers.js";
import type * as http_domains_customerChannel_routes_onlineOrder from "../http/domains/customerChannel/routes/onlineOrder.js";
import type * as http_domains_customerChannel_routes_paystack from "../http/domains/customerChannel/routes/paystack.js";
import type * as http_domains_customerChannel_routes_posTransaction from "../http/domains/customerChannel/routes/posTransaction.js";
import type * as http_domains_customerChannel_routes_reviews from "../http/domains/customerChannel/routes/reviews.js";
import type * as http_domains_customerChannel_routes_rewards from "../http/domains/customerChannel/routes/rewards.js";
import type * as http_domains_customerChannel_routes_savedBag from "../http/domains/customerChannel/routes/savedBag.js";
import type * as http_domains_customerChannel_routes_security from "../http/domains/customerChannel/routes/security.js";
import type * as http_domains_customerChannel_routes_storefront from "../http/domains/customerChannel/routes/storefront.js";
import type * as http_domains_customerChannel_routes_upsells from "../http/domains/customerChannel/routes/upsells.js";
import type * as http_domains_customerChannel_routes_user from "../http/domains/customerChannel/routes/user.js";
import type * as http_domains_customerChannel_routes_userOffers from "../http/domains/customerChannel/routes/userOffers.js";
import type * as http_domains_customerMessaging_routes_whatsapp from "../http/domains/customerMessaging/routes/whatsapp.js";
import type * as http_domains_moneyMovement_routes_index from "../http/domains/moneyMovement/routes/index.js";
import type * as http_domains_moneyMovement_routes_mtnMomo from "../http/domains/moneyMovement/routes/mtnMomo.js";
import type * as http_utils from "../http/utils.js";
import type * as inventory_athenaUser from "../inventory/athenaUser.js";
import type * as inventory_auth from "../inventory/auth.js";
import type * as inventory_bannerMessage from "../inventory/bannerMessage.js";
import type * as inventory_bestSeller from "../inventory/bestSeller.js";
import type * as inventory_categories from "../inventory/categories.js";
import type * as inventory_colors from "../inventory/colors.js";
import type * as inventory_complimentaryProduct from "../inventory/complimentaryProduct.js";
import type * as inventory_expenseSessionItems from "../inventory/expenseSessionItems.js";
import type * as inventory_expenseSessions from "../inventory/expenseSessions.js";
import type * as inventory_expenseTransactions from "../inventory/expenseTransactions.js";
import type * as inventory_featuredItem from "../inventory/featuredItem.js";
import type * as inventory_helpers_expenseSessionExpiration from "../inventory/helpers/expenseSessionExpiration.js";
import type * as inventory_helpers_expenseSessionValidation from "../inventory/helpers/expenseSessionValidation.js";
import type * as inventory_helpers_inventoryHolds from "../inventory/helpers/inventoryHolds.js";
import type * as inventory_helpers_resultTypes from "../inventory/helpers/resultTypes.js";
import type * as inventory_helpers_sessionExpiration from "../inventory/helpers/sessionExpiration.js";
import type * as inventory_helpers_sessionValidation from "../inventory/helpers/sessionValidation.js";
import type * as inventory_inviteCode from "../inventory/inviteCode.js";
import type * as inventory_organizationMembers from "../inventory/organizationMembers.js";
import type * as inventory_organizations from "../inventory/organizations.js";
import type * as inventory_pos from "../inventory/pos.js";
import type * as inventory_posCustomers from "../inventory/posCustomers.js";
import type * as inventory_posSessionItems from "../inventory/posSessionItems.js";
import type * as inventory_posSessions from "../inventory/posSessions.js";
import type * as inventory_posTerminal from "../inventory/posTerminal.js";
import type * as inventory_productSku from "../inventory/productSku.js";
import type * as inventory_productUtil from "../inventory/productUtil.js";
import type * as inventory_products from "../inventory/products.js";
import type * as inventory_promoCode from "../inventory/promoCode.js";
import type * as inventory_stockValidation from "../inventory/stockValidation.js";
import type * as inventory_storeConfigV2 from "../inventory/storeConfigV2.js";
import type * as inventory_stores from "../inventory/stores.js";
import type * as inventory_subcategories from "../inventory/subcategories.js";
import type * as inventory_utils from "../inventory/utils.js";
import type * as lib_athenaUserAuth from "../lib/athenaUserAuth.js";
import type * as lib_commandResultValidators from "../lib/commandResultValidators.js";
import type * as lib_currency from "../lib/currency.js";
import type * as llm_callLlmProvider from "../llm/callLlmProvider.js";
import type * as llm_providers_anthropic from "../llm/providers/anthropic.js";
import type * as llm_providers_openai from "../llm/providers/openai.js";
import type * as llm_storeInsights from "../llm/storeInsights.js";
import type * as llm_userInsights from "../llm/userInsights.js";
import type * as llm_utils_analyticsUtils from "../llm/utils/analyticsUtils.js";
import type * as mailersend_index from "../mailersend/index.js";
import type * as migrations_migrateAmountsToPesewas from "../migrations/migrateAmountsToPesewas.js";
import type * as mtn_client from "../mtn/client.js";
import type * as mtn_collections from "../mtn/collections.js";
import type * as mtn_config from "../mtn/config.js";
import type * as mtn_normalize from "../mtn/normalize.js";
import type * as mtn_types from "../mtn/types.js";
import type * as operations_approvalActions from "../operations/approvalActions.js";
import type * as operations_approvalAuditEvents from "../operations/approvalAuditEvents.js";
import type * as operations_approvalProofs from "../operations/approvalProofs.js";
import type * as operations_approvalRequestHelpers from "../operations/approvalRequestHelpers.js";
import type * as operations_approvalRequests from "../operations/approvalRequests.js";
import type * as operations_customerProfiles from "../operations/customerProfiles.js";
import type * as operations_dailyClose from "../operations/dailyClose.js";
import type * as operations_dailyOpening from "../operations/dailyOpening.js";
import type * as operations_dailyOperations from "../operations/dailyOperations.js";
import type * as operations_helpers_eventBuilders from "../operations/helpers/eventBuilders.js";
import type * as operations_helpers_linking from "../operations/helpers/linking.js";
import type * as operations_inventoryMovements from "../operations/inventoryMovements.js";
import type * as operations_managerElevations from "../operations/managerElevations.js";
import type * as operations_operationalEvents from "../operations/operationalEvents.js";
import type * as operations_operationalWorkItems from "../operations/operationalWorkItems.js";
import type * as operations_paymentAllocations from "../operations/paymentAllocations.js";
import type * as operations_registerSessionTracing from "../operations/registerSessionTracing.js";
import type * as operations_registerSessions from "../operations/registerSessions.js";
import type * as operations_serviceIntake from "../operations/serviceIntake.js";
import type * as operations_skuActivity from "../operations/skuActivity.js";
import type * as operations_staffCredentials from "../operations/staffCredentials.js";
import type * as operations_staffProfiles from "../operations/staffProfiles.js";
import type * as operations_staffRoles from "../operations/staffRoles.js";
import type * as otp_EmailOTP from "../otp/EmailOTP.js";
import type * as paystack_index from "../paystack/index.js";
import type * as pos_application_commands_assignCustomer from "../pos/application/commands/assignCustomer.js";
import type * as pos_application_commands_completeTransaction from "../pos/application/commands/completeTransaction.js";
import type * as pos_application_commands_correctTransaction from "../pos/application/commands/correctTransaction.js";
import type * as pos_application_commands_expenseSessionCommands from "../pos/application/commands/expenseSessionCommands.js";
import type * as pos_application_commands_expenseSessionTracing from "../pos/application/commands/expenseSessionTracing.js";
import type * as pos_application_commands_posSessionTracing from "../pos/application/commands/posSessionTracing.js";
import type * as pos_application_commands_quickAddCatalogItem from "../pos/application/commands/quickAddCatalogItem.js";
import type * as pos_application_commands_register from "../pos/application/commands/register.js";
import type * as pos_application_commands_sessionCommands from "../pos/application/commands/sessionCommands.js";
import type * as pos_application_commands_terminals from "../pos/application/commands/terminals.js";
import type * as pos_application_corrections_correctionEvents from "../pos/application/corrections/correctionEvents.js";
import type * as pos_application_corrections_correctionPolicy from "../pos/application/corrections/correctionPolicy.js";
import type * as pos_application_dto from "../pos/application/dto.js";
import type * as pos_application_queries_getRegisterState from "../pos/application/queries/getRegisterState.js";
import type * as pos_application_queries_getTransactions from "../pos/application/queries/getTransactions.js";
import type * as pos_application_queries_listRegisterCatalog from "../pos/application/queries/listRegisterCatalog.js";
import type * as pos_application_queries_searchCatalog from "../pos/application/queries/searchCatalog.js";
import type * as pos_application_queries_searchCustomers from "../pos/application/queries/searchCustomers.js";
import type * as pos_application_queries_terminals from "../pos/application/queries/terminals.js";
import type * as pos_application_sync_ingestLocalEvents from "../pos/application/sync/ingestLocalEvents.js";
import type * as pos_application_sync_projectLocalEvents from "../pos/application/sync/projectLocalEvents.js";
import type * as pos_application_sync_staffProof from "../pos/application/sync/staffProof.js";
import type * as pos_application_sync_terminalSyncSecret from "../pos/application/sync/terminalSyncSecret.js";
import type * as pos_application_sync_types from "../pos/application/sync/types.js";
import type * as pos_domain_errors from "../pos/domain/errors.js";
import type * as pos_domain_sessionRules from "../pos/domain/sessionRules.js";
import type * as pos_domain_types from "../pos/domain/types.js";
import type * as pos_infrastructure_integrations_inventoryHoldGateway from "../pos/infrastructure/integrations/inventoryHoldGateway.js";
import type * as pos_infrastructure_integrations_paymentAllocationService from "../pos/infrastructure/integrations/paymentAllocationService.js";
import type * as pos_infrastructure_repositories_cashierRepository from "../pos/infrastructure/repositories/cashierRepository.js";
import type * as pos_infrastructure_repositories_catalogRepository from "../pos/infrastructure/repositories/catalogRepository.js";
import type * as pos_infrastructure_repositories_customerRepository from "../pos/infrastructure/repositories/customerRepository.js";
import type * as pos_infrastructure_repositories_expenseSessionCommandRepository from "../pos/infrastructure/repositories/expenseSessionCommandRepository.js";
import type * as pos_infrastructure_repositories_localSyncRepository from "../pos/infrastructure/repositories/localSyncRepository.js";
import type * as pos_infrastructure_repositories_registerSessionRepository from "../pos/infrastructure/repositories/registerSessionRepository.js";
import type * as pos_infrastructure_repositories_sessionCommandRepository from "../pos/infrastructure/repositories/sessionCommandRepository.js";
import type * as pos_infrastructure_repositories_sessionRepository from "../pos/infrastructure/repositories/sessionRepository.js";
import type * as pos_infrastructure_repositories_terminalRepository from "../pos/infrastructure/repositories/terminalRepository.js";
import type * as pos_infrastructure_repositories_transactionRepository from "../pos/infrastructure/repositories/transactionRepository.js";
import type * as pos_public_catalog from "../pos/public/catalog.js";
import type * as pos_public_customers from "../pos/public/customers.js";
import type * as pos_public_register from "../pos/public/register.js";
import type * as pos_public_sync from "../pos/public/sync.js";
import type * as pos_public_terminals from "../pos/public/terminals.js";
import type * as pos_public_transactions from "../pos/public/transactions.js";
import type * as schemas_customerMessaging_customerMessageDelivery from "../schemas/customerMessaging/customerMessageDelivery.js";
import type * as schemas_customerMessaging_index from "../schemas/customerMessaging/index.js";
import type * as schemas_customerMessaging_receiptShareToken from "../schemas/customerMessaging/receiptShareToken.js";
import type * as schemas_inventory_appVerificationCode from "../schemas/inventory/appVerificationCode.js";
import type * as schemas_inventory_athenaUser from "../schemas/inventory/athenaUser.js";
import type * as schemas_inventory_bannerMessage from "../schemas/inventory/bannerMessage.js";
import type * as schemas_inventory_bestSeller from "../schemas/inventory/bestSeller.js";
import type * as schemas_inventory_category from "../schemas/inventory/category.js";
import type * as schemas_inventory_color from "../schemas/inventory/color.js";
import type * as schemas_inventory_complimentaryProduct from "../schemas/inventory/complimentaryProduct.js";
import type * as schemas_inventory_featuredItem from "../schemas/inventory/featuredItem.js";
import type * as schemas_inventory_index from "../schemas/inventory/index.js";
import type * as schemas_inventory_inventoryHold from "../schemas/inventory/inventoryHold.js";
import type * as schemas_inventory_inviteCode from "../schemas/inventory/inviteCode.js";
import type * as schemas_inventory_organization from "../schemas/inventory/organization.js";
import type * as schemas_inventory_organizationMember from "../schemas/inventory/organizationMember.js";
import type * as schemas_inventory_product from "../schemas/inventory/product.js";
import type * as schemas_inventory_promoCode from "../schemas/inventory/promoCode.js";
import type * as schemas_inventory_redeemedPromoCode from "../schemas/inventory/redeemedPromoCode.js";
import type * as schemas_inventory_store from "../schemas/inventory/store.js";
import type * as schemas_inventory_subcategory from "../schemas/inventory/subcategory.js";
import type * as schemas_observability_index from "../schemas/observability/index.js";
import type * as schemas_observability_workflowTrace from "../schemas/observability/workflowTrace.js";
import type * as schemas_observability_workflowTraceEvent from "../schemas/observability/workflowTraceEvent.js";
import type * as schemas_observability_workflowTraceLookup from "../schemas/observability/workflowTraceLookup.js";
import type * as schemas_operations_approvalRequest from "../schemas/operations/approvalRequest.js";
import type * as schemas_operations_customerProfile from "../schemas/operations/customerProfile.js";
import type * as schemas_operations_dailyClose from "../schemas/operations/dailyClose.js";
import type * as schemas_operations_dailyOpening from "../schemas/operations/dailyOpening.js";
import type * as schemas_operations_index from "../schemas/operations/index.js";
import type * as schemas_operations_inventoryMovement from "../schemas/operations/inventoryMovement.js";
import type * as schemas_operations_managerElevation from "../schemas/operations/managerElevation.js";
import type * as schemas_operations_operationalEvent from "../schemas/operations/operationalEvent.js";
import type * as schemas_operations_operationalWorkItem from "../schemas/operations/operationalWorkItem.js";
import type * as schemas_operations_paymentAllocation from "../schemas/operations/paymentAllocation.js";
import type * as schemas_operations_registerSession from "../schemas/operations/registerSession.js";
import type * as schemas_operations_skuActivityEvent from "../schemas/operations/skuActivityEvent.js";
import type * as schemas_operations_staffCredential from "../schemas/operations/staffCredential.js";
import type * as schemas_operations_staffProfile from "../schemas/operations/staffProfile.js";
import type * as schemas_operations_staffRoleAssignment from "../schemas/operations/staffRoleAssignment.js";
import type * as schemas_payments_mtnCollections from "../schemas/payments/mtnCollections.js";
import type * as schemas_pos_customer from "../schemas/pos/customer.js";
import type * as schemas_pos_expenseSession from "../schemas/pos/expenseSession.js";
import type * as schemas_pos_expenseSessionItem from "../schemas/pos/expenseSessionItem.js";
import type * as schemas_pos_expenseTransaction from "../schemas/pos/expenseTransaction.js";
import type * as schemas_pos_expenseTransactionItem from "../schemas/pos/expenseTransactionItem.js";
import type * as schemas_pos_index from "../schemas/pos/index.js";
import type * as schemas_pos_posLocalStaffProof from "../schemas/pos/posLocalStaffProof.js";
import type * as schemas_pos_posLocalSyncConflict from "../schemas/pos/posLocalSyncConflict.js";
import type * as schemas_pos_posLocalSyncCursor from "../schemas/pos/posLocalSyncCursor.js";
import type * as schemas_pos_posLocalSyncEvent from "../schemas/pos/posLocalSyncEvent.js";
import type * as schemas_pos_posLocalSyncMapping from "../schemas/pos/posLocalSyncMapping.js";
import type * as schemas_pos_posSession from "../schemas/pos/posSession.js";
import type * as schemas_pos_posSessionItem from "../schemas/pos/posSessionItem.js";
import type * as schemas_pos_posTerminal from "../schemas/pos/posTerminal.js";
import type * as schemas_pos_posTransaction from "../schemas/pos/posTransaction.js";
import type * as schemas_pos_posTransactionItem from "../schemas/pos/posTransactionItem.js";
import type * as schemas_serviceOps_index from "../schemas/serviceOps/index.js";
import type * as schemas_serviceOps_serviceAppointment from "../schemas/serviceOps/serviceAppointment.js";
import type * as schemas_serviceOps_serviceCase from "../schemas/serviceOps/serviceCase.js";
import type * as schemas_serviceOps_serviceCaseLineItem from "../schemas/serviceOps/serviceCaseLineItem.js";
import type * as schemas_serviceOps_serviceCatalog from "../schemas/serviceOps/serviceCatalog.js";
import type * as schemas_serviceOps_serviceInventoryUsage from "../schemas/serviceOps/serviceInventoryUsage.js";
import type * as schemas_stockOps_cycleCountDraft from "../schemas/stockOps/cycleCountDraft.js";
import type * as schemas_stockOps_index from "../schemas/stockOps/index.js";
import type * as schemas_stockOps_purchaseOrder from "../schemas/stockOps/purchaseOrder.js";
import type * as schemas_stockOps_purchaseOrderLineItem from "../schemas/stockOps/purchaseOrderLineItem.js";
import type * as schemas_stockOps_receivingBatch from "../schemas/stockOps/receivingBatch.js";
import type * as schemas_stockOps_stockAdjustmentBatch from "../schemas/stockOps/stockAdjustmentBatch.js";
import type * as schemas_stockOps_vendor from "../schemas/stockOps/vendor.js";
import type * as schemas_storeFront_analytics from "../schemas/storeFront/analytics.js";
import type * as schemas_storeFront_bag from "../schemas/storeFront/bag.js";
import type * as schemas_storeFront_bagItem from "../schemas/storeFront/bagItem.js";
import type * as schemas_storeFront_checkoutSession from "../schemas/storeFront/checkoutSession.js";
import type * as schemas_storeFront_checkoutSessionItem from "../schemas/storeFront/checkoutSessionItem.js";
import type * as schemas_storeFront_guest from "../schemas/storeFront/guest.js";
import type * as schemas_storeFront_index from "../schemas/storeFront/index.js";
import type * as schemas_storeFront_offer from "../schemas/storeFront/offer.js";
import type * as schemas_storeFront_onlineOrder_onlineOrder from "../schemas/storeFront/onlineOrder/onlineOrder.js";
import type * as schemas_storeFront_onlineOrder_onlineOrderItem from "../schemas/storeFront/onlineOrder/onlineOrderItem.js";
import type * as schemas_storeFront_review from "../schemas/storeFront/review.js";
import type * as schemas_storeFront_rewards from "../schemas/storeFront/rewards.js";
import type * as schemas_storeFront_savedBag from "../schemas/storeFront/savedBag.js";
import type * as schemas_storeFront_savedBagItem from "../schemas/storeFront/savedBagItem.js";
import type * as schemas_storeFront_storeFrontSession from "../schemas/storeFront/storeFrontSession.js";
import type * as schemas_storeFront_storeFrontUser from "../schemas/storeFront/storeFrontUser.js";
import type * as schemas_storeFront_storeFrontVerificationCode from "../schemas/storeFront/storeFrontVerificationCode.js";
import type * as schemas_storeFront_supportTicket from "../schemas/storeFront/supportTicket.js";
import type * as sendgrid_index from "../sendgrid/index.js";
import type * as serviceOps_appointments from "../serviceOps/appointments.js";
import type * as serviceOps_catalog from "../serviceOps/catalog.js";
import type * as serviceOps_serviceCases from "../serviceOps/serviceCases.js";
import type * as services_orderEmailService from "../services/orderEmailService.js";
import type * as services_paystackService from "../services/paystackService.js";
import type * as stockOps_access from "../stockOps/access.js";
import type * as stockOps_adjustments from "../stockOps/adjustments.js";
import type * as stockOps_cycleCountDrafts from "../stockOps/cycleCountDrafts.js";
import type * as stockOps_purchaseOrders from "../stockOps/purchaseOrders.js";
import type * as stockOps_receiving from "../stockOps/receiving.js";
import type * as stockOps_replenishment from "../stockOps/replenishment.js";
import type * as stockOps_vendors from "../stockOps/vendors.js";
import type * as storeFront_analytics from "../storeFront/analytics.js";
import type * as storeFront_auth from "../storeFront/auth.js";
import type * as storeFront_bag from "../storeFront/bag.js";
import type * as storeFront_bagItem from "../storeFront/bagItem.js";
import type * as storeFront_checkoutSession from "../storeFront/checkoutSession.js";
import type * as storeFront_customerBehaviorTimeline from "../storeFront/customerBehaviorTimeline.js";
import type * as storeFront_customerObservabilityTimelineData from "../storeFront/customerObservabilityTimelineData.js";
import type * as storeFront_guest from "../storeFront/guest.js";
import type * as storeFront_helpers_bag from "../storeFront/helpers/bag.js";
import type * as storeFront_helpers_customerEngagementEvents from "../storeFront/helpers/customerEngagementEvents.js";
import type * as storeFront_helpers_onlineOrder from "../storeFront/helpers/onlineOrder.js";
import type * as storeFront_helpers_orderOperations from "../storeFront/helpers/orderOperations.js";
import type * as storeFront_helpers_orderUpdateEmails from "../storeFront/helpers/orderUpdateEmails.js";
import type * as storeFront_helpers_paymentHelpers from "../storeFront/helpers/paymentHelpers.js";
import type * as storeFront_helpers_returnExchangeOperations from "../storeFront/helpers/returnExchangeOperations.js";
import type * as storeFront_offers from "../storeFront/offers.js";
import type * as storeFront_onlineOrder from "../storeFront/onlineOrder.js";
import type * as storeFront_onlineOrderItem from "../storeFront/onlineOrderItem.js";
import type * as storeFront_onlineOrderUtilFns from "../storeFront/onlineOrderUtilFns.js";
import type * as storeFront_payment from "../storeFront/payment.js";
import type * as storeFront_paystackActions from "../storeFront/paystackActions.js";
import type * as storeFront_reviews from "../storeFront/reviews.js";
import type * as storeFront_rewards from "../storeFront/rewards.js";
import type * as storeFront_savedBag from "../storeFront/savedBag.js";
import type * as storeFront_savedBagItem from "../storeFront/savedBagItem.js";
import type * as storeFront_storefrontObservabilityReport from "../storeFront/storefrontObservabilityReport.js";
import type * as storeFront_supportTicket from "../storeFront/supportTicket.js";
import type * as storeFront_syntheticMonitor from "../storeFront/syntheticMonitor.js";
import type * as storeFront_user from "../storeFront/user.js";
import type * as storeFront_userOffers from "../storeFront/userOffers.js";
import type * as storeFront_users from "../storeFront/users.js";
import type * as types_payment from "../types/payment.js";
import type * as utils from "../utils.js";
import type * as workflowTraces_adapters_expenseSession from "../workflowTraces/adapters/expenseSession.js";
import type * as workflowTraces_adapters_posSession from "../workflowTraces/adapters/posSession.js";
import type * as workflowTraces_adapters_registerSession from "../workflowTraces/adapters/registerSession.js";
import type * as workflowTraces_core from "../workflowTraces/core.js";
import type * as workflowTraces_presentation from "../workflowTraces/presentation.js";
import type * as workflowTraces_public from "../workflowTraces/public.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  app: typeof app;
  auth: typeof auth;
  "cache/index": typeof cache_index;
  "cashControls/closeouts": typeof cashControls_closeouts;
  "cashControls/deposits": typeof cashControls_deposits;
  "cashControls/paymentAllocationAttribution": typeof cashControls_paymentAllocationAttribution;
  "cloudflare/r2": typeof cloudflare_r2;
  "cloudflare/stream": typeof cloudflare_stream;
  "constants/countries": typeof constants_countries;
  "constants/email": typeof constants_email;
  "constants/ghana": typeof constants_ghana;
  "constants/payment": typeof constants_payment;
  crons: typeof crons;
  "customerMessaging/domain": typeof customerMessaging_domain;
  "customerMessaging/internal": typeof customerMessaging_internal;
  "customerMessaging/policy": typeof customerMessaging_policy;
  "customerMessaging/public": typeof customerMessaging_public;
  "customerMessaging/repository": typeof customerMessaging_repository;
  "customerMessaging/token": typeof customerMessaging_token;
  "customerMessaging/webhookSecurity": typeof customerMessaging_webhookSecurity;
  "customerMessaging/whatsappClient": typeof customerMessaging_whatsappClient;
  "customerMessaging/whatsappConfig": typeof customerMessaging_whatsappConfig;
  devPatchBadTransaction: typeof devPatchBadTransaction;
  "emails/DiscountCode": typeof emails_DiscountCode;
  "emails/DiscountReminder": typeof emails_DiscountReminder;
  "emails/FeedbackRequest": typeof emails_FeedbackRequest;
  "emails/NewOrderAdmin": typeof emails_NewOrderAdmin;
  "emails/OrderEmail": typeof emails_OrderEmail;
  "emails/PosReceiptEmail": typeof emails_PosReceiptEmail;
  "emails/VerificationCode": typeof emails_VerificationCode;
  env: typeof env;
  http: typeof http;
  "http/domains/core/routes/analytics": typeof http_domains_core_routes_analytics;
  "http/domains/core/routes/auth": typeof http_domains_core_routes_auth;
  "http/domains/core/routes/bannerMessage": typeof http_domains_core_routes_bannerMessage;
  "http/domains/core/routes/categories": typeof http_domains_core_routes_categories;
  "http/domains/core/routes/colors": typeof http_domains_core_routes_colors;
  "http/domains/core/routes/index": typeof http_domains_core_routes_index;
  "http/domains/core/routes/organizations": typeof http_domains_core_routes_organizations;
  "http/domains/core/routes/products": typeof http_domains_core_routes_products;
  "http/domains/core/routes/stores": typeof http_domains_core_routes_stores;
  "http/domains/core/routes/subcategories": typeof http_domains_core_routes_subcategories;
  "http/domains/customerChannel/routes/bag": typeof http_domains_customerChannel_routes_bag;
  "http/domains/customerChannel/routes/checkout": typeof http_domains_customerChannel_routes_checkout;
  "http/domains/customerChannel/routes/guest": typeof http_domains_customerChannel_routes_guest;
  "http/domains/customerChannel/routes/index": typeof http_domains_customerChannel_routes_index;
  "http/domains/customerChannel/routes/me": typeof http_domains_customerChannel_routes_me;
  "http/domains/customerChannel/routes/offers": typeof http_domains_customerChannel_routes_offers;
  "http/domains/customerChannel/routes/onlineOrder": typeof http_domains_customerChannel_routes_onlineOrder;
  "http/domains/customerChannel/routes/paystack": typeof http_domains_customerChannel_routes_paystack;
  "http/domains/customerChannel/routes/posTransaction": typeof http_domains_customerChannel_routes_posTransaction;
  "http/domains/customerChannel/routes/reviews": typeof http_domains_customerChannel_routes_reviews;
  "http/domains/customerChannel/routes/rewards": typeof http_domains_customerChannel_routes_rewards;
  "http/domains/customerChannel/routes/savedBag": typeof http_domains_customerChannel_routes_savedBag;
  "http/domains/customerChannel/routes/security": typeof http_domains_customerChannel_routes_security;
  "http/domains/customerChannel/routes/storefront": typeof http_domains_customerChannel_routes_storefront;
  "http/domains/customerChannel/routes/upsells": typeof http_domains_customerChannel_routes_upsells;
  "http/domains/customerChannel/routes/user": typeof http_domains_customerChannel_routes_user;
  "http/domains/customerChannel/routes/userOffers": typeof http_domains_customerChannel_routes_userOffers;
  "http/domains/customerMessaging/routes/whatsapp": typeof http_domains_customerMessaging_routes_whatsapp;
  "http/domains/moneyMovement/routes/index": typeof http_domains_moneyMovement_routes_index;
  "http/domains/moneyMovement/routes/mtnMomo": typeof http_domains_moneyMovement_routes_mtnMomo;
  "http/utils": typeof http_utils;
  "inventory/athenaUser": typeof inventory_athenaUser;
  "inventory/auth": typeof inventory_auth;
  "inventory/bannerMessage": typeof inventory_bannerMessage;
  "inventory/bestSeller": typeof inventory_bestSeller;
  "inventory/categories": typeof inventory_categories;
  "inventory/colors": typeof inventory_colors;
  "inventory/complimentaryProduct": typeof inventory_complimentaryProduct;
  "inventory/expenseSessionItems": typeof inventory_expenseSessionItems;
  "inventory/expenseSessions": typeof inventory_expenseSessions;
  "inventory/expenseTransactions": typeof inventory_expenseTransactions;
  "inventory/featuredItem": typeof inventory_featuredItem;
  "inventory/helpers/expenseSessionExpiration": typeof inventory_helpers_expenseSessionExpiration;
  "inventory/helpers/expenseSessionValidation": typeof inventory_helpers_expenseSessionValidation;
  "inventory/helpers/inventoryHolds": typeof inventory_helpers_inventoryHolds;
  "inventory/helpers/resultTypes": typeof inventory_helpers_resultTypes;
  "inventory/helpers/sessionExpiration": typeof inventory_helpers_sessionExpiration;
  "inventory/helpers/sessionValidation": typeof inventory_helpers_sessionValidation;
  "inventory/inviteCode": typeof inventory_inviteCode;
  "inventory/organizationMembers": typeof inventory_organizationMembers;
  "inventory/organizations": typeof inventory_organizations;
  "inventory/pos": typeof inventory_pos;
  "inventory/posCustomers": typeof inventory_posCustomers;
  "inventory/posSessionItems": typeof inventory_posSessionItems;
  "inventory/posSessions": typeof inventory_posSessions;
  "inventory/posTerminal": typeof inventory_posTerminal;
  "inventory/productSku": typeof inventory_productSku;
  "inventory/productUtil": typeof inventory_productUtil;
  "inventory/products": typeof inventory_products;
  "inventory/promoCode": typeof inventory_promoCode;
  "inventory/stockValidation": typeof inventory_stockValidation;
  "inventory/storeConfigV2": typeof inventory_storeConfigV2;
  "inventory/stores": typeof inventory_stores;
  "inventory/subcategories": typeof inventory_subcategories;
  "inventory/utils": typeof inventory_utils;
  "lib/athenaUserAuth": typeof lib_athenaUserAuth;
  "lib/commandResultValidators": typeof lib_commandResultValidators;
  "lib/currency": typeof lib_currency;
  "llm/callLlmProvider": typeof llm_callLlmProvider;
  "llm/providers/anthropic": typeof llm_providers_anthropic;
  "llm/providers/openai": typeof llm_providers_openai;
  "llm/storeInsights": typeof llm_storeInsights;
  "llm/userInsights": typeof llm_userInsights;
  "llm/utils/analyticsUtils": typeof llm_utils_analyticsUtils;
  "mailersend/index": typeof mailersend_index;
  "migrations/migrateAmountsToPesewas": typeof migrations_migrateAmountsToPesewas;
  "mtn/client": typeof mtn_client;
  "mtn/collections": typeof mtn_collections;
  "mtn/config": typeof mtn_config;
  "mtn/normalize": typeof mtn_normalize;
  "mtn/types": typeof mtn_types;
  "operations/approvalActions": typeof operations_approvalActions;
  "operations/approvalAuditEvents": typeof operations_approvalAuditEvents;
  "operations/approvalProofs": typeof operations_approvalProofs;
  "operations/approvalRequestHelpers": typeof operations_approvalRequestHelpers;
  "operations/approvalRequests": typeof operations_approvalRequests;
  "operations/customerProfiles": typeof operations_customerProfiles;
  "operations/dailyClose": typeof operations_dailyClose;
  "operations/dailyOpening": typeof operations_dailyOpening;
  "operations/dailyOperations": typeof operations_dailyOperations;
  "operations/helpers/eventBuilders": typeof operations_helpers_eventBuilders;
  "operations/helpers/linking": typeof operations_helpers_linking;
  "operations/inventoryMovements": typeof operations_inventoryMovements;
  "operations/managerElevations": typeof operations_managerElevations;
  "operations/operationalEvents": typeof operations_operationalEvents;
  "operations/operationalWorkItems": typeof operations_operationalWorkItems;
  "operations/paymentAllocations": typeof operations_paymentAllocations;
  "operations/registerSessionTracing": typeof operations_registerSessionTracing;
  "operations/registerSessions": typeof operations_registerSessions;
  "operations/serviceIntake": typeof operations_serviceIntake;
  "operations/skuActivity": typeof operations_skuActivity;
  "operations/staffCredentials": typeof operations_staffCredentials;
  "operations/staffProfiles": typeof operations_staffProfiles;
  "operations/staffRoles": typeof operations_staffRoles;
  "otp/EmailOTP": typeof otp_EmailOTP;
  "paystack/index": typeof paystack_index;
  "pos/application/commands/assignCustomer": typeof pos_application_commands_assignCustomer;
  "pos/application/commands/completeTransaction": typeof pos_application_commands_completeTransaction;
  "pos/application/commands/correctTransaction": typeof pos_application_commands_correctTransaction;
  "pos/application/commands/expenseSessionCommands": typeof pos_application_commands_expenseSessionCommands;
  "pos/application/commands/expenseSessionTracing": typeof pos_application_commands_expenseSessionTracing;
  "pos/application/commands/posSessionTracing": typeof pos_application_commands_posSessionTracing;
  "pos/application/commands/quickAddCatalogItem": typeof pos_application_commands_quickAddCatalogItem;
  "pos/application/commands/register": typeof pos_application_commands_register;
  "pos/application/commands/sessionCommands": typeof pos_application_commands_sessionCommands;
  "pos/application/commands/terminals": typeof pos_application_commands_terminals;
  "pos/application/corrections/correctionEvents": typeof pos_application_corrections_correctionEvents;
  "pos/application/corrections/correctionPolicy": typeof pos_application_corrections_correctionPolicy;
  "pos/application/dto": typeof pos_application_dto;
  "pos/application/queries/getRegisterState": typeof pos_application_queries_getRegisterState;
  "pos/application/queries/getTransactions": typeof pos_application_queries_getTransactions;
  "pos/application/queries/listRegisterCatalog": typeof pos_application_queries_listRegisterCatalog;
  "pos/application/queries/searchCatalog": typeof pos_application_queries_searchCatalog;
  "pos/application/queries/searchCustomers": typeof pos_application_queries_searchCustomers;
  "pos/application/queries/terminals": typeof pos_application_queries_terminals;
  "pos/application/sync/ingestLocalEvents": typeof pos_application_sync_ingestLocalEvents;
  "pos/application/sync/projectLocalEvents": typeof pos_application_sync_projectLocalEvents;
  "pos/application/sync/staffProof": typeof pos_application_sync_staffProof;
  "pos/application/sync/terminalSyncSecret": typeof pos_application_sync_terminalSyncSecret;
  "pos/application/sync/types": typeof pos_application_sync_types;
  "pos/domain/errors": typeof pos_domain_errors;
  "pos/domain/sessionRules": typeof pos_domain_sessionRules;
  "pos/domain/types": typeof pos_domain_types;
  "pos/infrastructure/integrations/inventoryHoldGateway": typeof pos_infrastructure_integrations_inventoryHoldGateway;
  "pos/infrastructure/integrations/paymentAllocationService": typeof pos_infrastructure_integrations_paymentAllocationService;
  "pos/infrastructure/repositories/cashierRepository": typeof pos_infrastructure_repositories_cashierRepository;
  "pos/infrastructure/repositories/catalogRepository": typeof pos_infrastructure_repositories_catalogRepository;
  "pos/infrastructure/repositories/customerRepository": typeof pos_infrastructure_repositories_customerRepository;
  "pos/infrastructure/repositories/expenseSessionCommandRepository": typeof pos_infrastructure_repositories_expenseSessionCommandRepository;
  "pos/infrastructure/repositories/localSyncRepository": typeof pos_infrastructure_repositories_localSyncRepository;
  "pos/infrastructure/repositories/registerSessionRepository": typeof pos_infrastructure_repositories_registerSessionRepository;
  "pos/infrastructure/repositories/sessionCommandRepository": typeof pos_infrastructure_repositories_sessionCommandRepository;
  "pos/infrastructure/repositories/sessionRepository": typeof pos_infrastructure_repositories_sessionRepository;
  "pos/infrastructure/repositories/terminalRepository": typeof pos_infrastructure_repositories_terminalRepository;
  "pos/infrastructure/repositories/transactionRepository": typeof pos_infrastructure_repositories_transactionRepository;
  "pos/public/catalog": typeof pos_public_catalog;
  "pos/public/customers": typeof pos_public_customers;
  "pos/public/register": typeof pos_public_register;
  "pos/public/sync": typeof pos_public_sync;
  "pos/public/terminals": typeof pos_public_terminals;
  "pos/public/transactions": typeof pos_public_transactions;
  "schemas/customerMessaging/customerMessageDelivery": typeof schemas_customerMessaging_customerMessageDelivery;
  "schemas/customerMessaging/index": typeof schemas_customerMessaging_index;
  "schemas/customerMessaging/receiptShareToken": typeof schemas_customerMessaging_receiptShareToken;
  "schemas/inventory/appVerificationCode": typeof schemas_inventory_appVerificationCode;
  "schemas/inventory/athenaUser": typeof schemas_inventory_athenaUser;
  "schemas/inventory/bannerMessage": typeof schemas_inventory_bannerMessage;
  "schemas/inventory/bestSeller": typeof schemas_inventory_bestSeller;
  "schemas/inventory/category": typeof schemas_inventory_category;
  "schemas/inventory/color": typeof schemas_inventory_color;
  "schemas/inventory/complimentaryProduct": typeof schemas_inventory_complimentaryProduct;
  "schemas/inventory/featuredItem": typeof schemas_inventory_featuredItem;
  "schemas/inventory/index": typeof schemas_inventory_index;
  "schemas/inventory/inventoryHold": typeof schemas_inventory_inventoryHold;
  "schemas/inventory/inviteCode": typeof schemas_inventory_inviteCode;
  "schemas/inventory/organization": typeof schemas_inventory_organization;
  "schemas/inventory/organizationMember": typeof schemas_inventory_organizationMember;
  "schemas/inventory/product": typeof schemas_inventory_product;
  "schemas/inventory/promoCode": typeof schemas_inventory_promoCode;
  "schemas/inventory/redeemedPromoCode": typeof schemas_inventory_redeemedPromoCode;
  "schemas/inventory/store": typeof schemas_inventory_store;
  "schemas/inventory/subcategory": typeof schemas_inventory_subcategory;
  "schemas/observability/index": typeof schemas_observability_index;
  "schemas/observability/workflowTrace": typeof schemas_observability_workflowTrace;
  "schemas/observability/workflowTraceEvent": typeof schemas_observability_workflowTraceEvent;
  "schemas/observability/workflowTraceLookup": typeof schemas_observability_workflowTraceLookup;
  "schemas/operations/approvalRequest": typeof schemas_operations_approvalRequest;
  "schemas/operations/customerProfile": typeof schemas_operations_customerProfile;
  "schemas/operations/dailyClose": typeof schemas_operations_dailyClose;
  "schemas/operations/dailyOpening": typeof schemas_operations_dailyOpening;
  "schemas/operations/index": typeof schemas_operations_index;
  "schemas/operations/inventoryMovement": typeof schemas_operations_inventoryMovement;
  "schemas/operations/managerElevation": typeof schemas_operations_managerElevation;
  "schemas/operations/operationalEvent": typeof schemas_operations_operationalEvent;
  "schemas/operations/operationalWorkItem": typeof schemas_operations_operationalWorkItem;
  "schemas/operations/paymentAllocation": typeof schemas_operations_paymentAllocation;
  "schemas/operations/registerSession": typeof schemas_operations_registerSession;
  "schemas/operations/skuActivityEvent": typeof schemas_operations_skuActivityEvent;
  "schemas/operations/staffCredential": typeof schemas_operations_staffCredential;
  "schemas/operations/staffProfile": typeof schemas_operations_staffProfile;
  "schemas/operations/staffRoleAssignment": typeof schemas_operations_staffRoleAssignment;
  "schemas/payments/mtnCollections": typeof schemas_payments_mtnCollections;
  "schemas/pos/customer": typeof schemas_pos_customer;
  "schemas/pos/expenseSession": typeof schemas_pos_expenseSession;
  "schemas/pos/expenseSessionItem": typeof schemas_pos_expenseSessionItem;
  "schemas/pos/expenseTransaction": typeof schemas_pos_expenseTransaction;
  "schemas/pos/expenseTransactionItem": typeof schemas_pos_expenseTransactionItem;
  "schemas/pos/index": typeof schemas_pos_index;
  "schemas/pos/posLocalStaffProof": typeof schemas_pos_posLocalStaffProof;
  "schemas/pos/posLocalSyncConflict": typeof schemas_pos_posLocalSyncConflict;
  "schemas/pos/posLocalSyncCursor": typeof schemas_pos_posLocalSyncCursor;
  "schemas/pos/posLocalSyncEvent": typeof schemas_pos_posLocalSyncEvent;
  "schemas/pos/posLocalSyncMapping": typeof schemas_pos_posLocalSyncMapping;
  "schemas/pos/posSession": typeof schemas_pos_posSession;
  "schemas/pos/posSessionItem": typeof schemas_pos_posSessionItem;
  "schemas/pos/posTerminal": typeof schemas_pos_posTerminal;
  "schemas/pos/posTransaction": typeof schemas_pos_posTransaction;
  "schemas/pos/posTransactionItem": typeof schemas_pos_posTransactionItem;
  "schemas/serviceOps/index": typeof schemas_serviceOps_index;
  "schemas/serviceOps/serviceAppointment": typeof schemas_serviceOps_serviceAppointment;
  "schemas/serviceOps/serviceCase": typeof schemas_serviceOps_serviceCase;
  "schemas/serviceOps/serviceCaseLineItem": typeof schemas_serviceOps_serviceCaseLineItem;
  "schemas/serviceOps/serviceCatalog": typeof schemas_serviceOps_serviceCatalog;
  "schemas/serviceOps/serviceInventoryUsage": typeof schemas_serviceOps_serviceInventoryUsage;
  "schemas/stockOps/cycleCountDraft": typeof schemas_stockOps_cycleCountDraft;
  "schemas/stockOps/index": typeof schemas_stockOps_index;
  "schemas/stockOps/purchaseOrder": typeof schemas_stockOps_purchaseOrder;
  "schemas/stockOps/purchaseOrderLineItem": typeof schemas_stockOps_purchaseOrderLineItem;
  "schemas/stockOps/receivingBatch": typeof schemas_stockOps_receivingBatch;
  "schemas/stockOps/stockAdjustmentBatch": typeof schemas_stockOps_stockAdjustmentBatch;
  "schemas/stockOps/vendor": typeof schemas_stockOps_vendor;
  "schemas/storeFront/analytics": typeof schemas_storeFront_analytics;
  "schemas/storeFront/bag": typeof schemas_storeFront_bag;
  "schemas/storeFront/bagItem": typeof schemas_storeFront_bagItem;
  "schemas/storeFront/checkoutSession": typeof schemas_storeFront_checkoutSession;
  "schemas/storeFront/checkoutSessionItem": typeof schemas_storeFront_checkoutSessionItem;
  "schemas/storeFront/guest": typeof schemas_storeFront_guest;
  "schemas/storeFront/index": typeof schemas_storeFront_index;
  "schemas/storeFront/offer": typeof schemas_storeFront_offer;
  "schemas/storeFront/onlineOrder/onlineOrder": typeof schemas_storeFront_onlineOrder_onlineOrder;
  "schemas/storeFront/onlineOrder/onlineOrderItem": typeof schemas_storeFront_onlineOrder_onlineOrderItem;
  "schemas/storeFront/review": typeof schemas_storeFront_review;
  "schemas/storeFront/rewards": typeof schemas_storeFront_rewards;
  "schemas/storeFront/savedBag": typeof schemas_storeFront_savedBag;
  "schemas/storeFront/savedBagItem": typeof schemas_storeFront_savedBagItem;
  "schemas/storeFront/storeFrontSession": typeof schemas_storeFront_storeFrontSession;
  "schemas/storeFront/storeFrontUser": typeof schemas_storeFront_storeFrontUser;
  "schemas/storeFront/storeFrontVerificationCode": typeof schemas_storeFront_storeFrontVerificationCode;
  "schemas/storeFront/supportTicket": typeof schemas_storeFront_supportTicket;
  "sendgrid/index": typeof sendgrid_index;
  "serviceOps/appointments": typeof serviceOps_appointments;
  "serviceOps/catalog": typeof serviceOps_catalog;
  "serviceOps/serviceCases": typeof serviceOps_serviceCases;
  "services/orderEmailService": typeof services_orderEmailService;
  "services/paystackService": typeof services_paystackService;
  "stockOps/access": typeof stockOps_access;
  "stockOps/adjustments": typeof stockOps_adjustments;
  "stockOps/cycleCountDrafts": typeof stockOps_cycleCountDrafts;
  "stockOps/purchaseOrders": typeof stockOps_purchaseOrders;
  "stockOps/receiving": typeof stockOps_receiving;
  "stockOps/replenishment": typeof stockOps_replenishment;
  "stockOps/vendors": typeof stockOps_vendors;
  "storeFront/analytics": typeof storeFront_analytics;
  "storeFront/auth": typeof storeFront_auth;
  "storeFront/bag": typeof storeFront_bag;
  "storeFront/bagItem": typeof storeFront_bagItem;
  "storeFront/checkoutSession": typeof storeFront_checkoutSession;
  "storeFront/customerBehaviorTimeline": typeof storeFront_customerBehaviorTimeline;
  "storeFront/customerObservabilityTimelineData": typeof storeFront_customerObservabilityTimelineData;
  "storeFront/guest": typeof storeFront_guest;
  "storeFront/helpers/bag": typeof storeFront_helpers_bag;
  "storeFront/helpers/customerEngagementEvents": typeof storeFront_helpers_customerEngagementEvents;
  "storeFront/helpers/onlineOrder": typeof storeFront_helpers_onlineOrder;
  "storeFront/helpers/orderOperations": typeof storeFront_helpers_orderOperations;
  "storeFront/helpers/orderUpdateEmails": typeof storeFront_helpers_orderUpdateEmails;
  "storeFront/helpers/paymentHelpers": typeof storeFront_helpers_paymentHelpers;
  "storeFront/helpers/returnExchangeOperations": typeof storeFront_helpers_returnExchangeOperations;
  "storeFront/offers": typeof storeFront_offers;
  "storeFront/onlineOrder": typeof storeFront_onlineOrder;
  "storeFront/onlineOrderItem": typeof storeFront_onlineOrderItem;
  "storeFront/onlineOrderUtilFns": typeof storeFront_onlineOrderUtilFns;
  "storeFront/payment": typeof storeFront_payment;
  "storeFront/paystackActions": typeof storeFront_paystackActions;
  "storeFront/reviews": typeof storeFront_reviews;
  "storeFront/rewards": typeof storeFront_rewards;
  "storeFront/savedBag": typeof storeFront_savedBag;
  "storeFront/savedBagItem": typeof storeFront_savedBagItem;
  "storeFront/storefrontObservabilityReport": typeof storeFront_storefrontObservabilityReport;
  "storeFront/supportTicket": typeof storeFront_supportTicket;
  "storeFront/syntheticMonitor": typeof storeFront_syntheticMonitor;
  "storeFront/user": typeof storeFront_user;
  "storeFront/userOffers": typeof storeFront_userOffers;
  "storeFront/users": typeof storeFront_users;
  "types/payment": typeof types_payment;
  utils: typeof utils;
  "workflowTraces/adapters/expenseSession": typeof workflowTraces_adapters_expenseSession;
  "workflowTraces/adapters/posSession": typeof workflowTraces_adapters_posSession;
  "workflowTraces/adapters/registerSession": typeof workflowTraces_adapters_registerSession;
  "workflowTraces/core": typeof workflowTraces_core;
  "workflowTraces/presentation": typeof workflowTraces_presentation;
  "workflowTraces/public": typeof workflowTraces_public;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
