/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutContactUsImport } from './routes/_layout/contact-us'
import { Route as LayoutShopLayoutImport } from './routes/_layout/_shopLayout'
import { Route as LayoutOrdersLayoutImport } from './routes/_layout/_ordersLayout'
import { Route as ShopCheckoutIndexImport } from './routes/shop/checkout/index'
import { Route as ShopBagIndexImport } from './routes/shop/bag.index'
import { Route as ShopCheckoutVerifyIndexImport } from './routes/shop/checkout/verify.index'
import { Route as ShopCheckoutCompleteIndexImport } from './routes/shop/checkout/complete.index'
import { Route as ShopCheckoutSessionIdSlugIndexImport } from './routes/shop/checkout/$sessionIdSlug/index'
import { Route as LayoutShopSavedIndexImport } from './routes/_layout/shop.saved.index'
import { Route as LayoutPoliciesTosIndexImport } from './routes/_layout/policies/tos.index'
import { Route as LayoutPoliciesPrivacyIndexImport } from './routes/_layout/policies/privacy.index'
import { Route as LayoutPoliciesDeliveryReturnsExchangesIndexImport } from './routes/_layout/policies/delivery-returns-exchanges.index'
import { Route as ShopCheckoutSessionIdSlugCompleteImport } from './routes/shop/checkout/$sessionIdSlug/complete'
import { Route as LayoutShopProductProductSlugImport } from './routes/_layout/shop.product.$productSlug'
import { Route as LayoutShopLayoutShopCategorySlugIndexImport } from './routes/_layout/_shopLayout/shop/$categorySlug/index'
import { Route as LayoutOrdersLayoutShopOrdersIndexImport } from './routes/_layout/_ordersLayout/shop/orders/index'
import { Route as LayoutShopLayoutShopCategorySlugSubcategorySlugImport } from './routes/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug'
import { Route as LayoutOrdersLayoutShopOrdersOrderIdImport } from './routes/_layout/_ordersLayout/shop/orders/$orderId'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutContactUsRoute = LayoutContactUsImport.update({
  path: '/contact-us',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutShopLayoutRoute = LayoutShopLayoutImport.update({
  id: '/_shopLayout',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutOrdersLayoutRoute = LayoutOrdersLayoutImport.update({
  id: '/_ordersLayout',
  getParentRoute: () => LayoutRoute,
} as any)

const ShopCheckoutIndexRoute = ShopCheckoutIndexImport.update({
  path: '/shop/checkout/',
  getParentRoute: () => rootRoute,
} as any)

const ShopBagIndexRoute = ShopBagIndexImport.update({
  path: '/shop/bag/',
  getParentRoute: () => rootRoute,
} as any)

const ShopCheckoutVerifyIndexRoute = ShopCheckoutVerifyIndexImport.update({
  path: '/shop/checkout/verify/',
  getParentRoute: () => rootRoute,
} as any)

const ShopCheckoutCompleteIndexRoute = ShopCheckoutCompleteIndexImport.update({
  path: '/shop/checkout/complete/',
  getParentRoute: () => rootRoute,
} as any)

const ShopCheckoutSessionIdSlugIndexRoute =
  ShopCheckoutSessionIdSlugIndexImport.update({
    path: '/shop/checkout/$sessionIdSlug/',
    getParentRoute: () => rootRoute,
  } as any)

const LayoutShopSavedIndexRoute = LayoutShopSavedIndexImport.update({
  path: '/shop/saved/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPoliciesTosIndexRoute = LayoutPoliciesTosIndexImport.update({
  path: '/policies/tos/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPoliciesPrivacyIndexRoute = LayoutPoliciesPrivacyIndexImport.update(
  {
    path: '/policies/privacy/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutPoliciesDeliveryReturnsExchangesIndexRoute =
  LayoutPoliciesDeliveryReturnsExchangesIndexImport.update({
    path: '/policies/delivery-returns-exchanges/',
    getParentRoute: () => LayoutRoute,
  } as any)

const ShopCheckoutSessionIdSlugCompleteRoute =
  ShopCheckoutSessionIdSlugCompleteImport.update({
    path: '/shop/checkout/$sessionIdSlug/complete',
    getParentRoute: () => rootRoute,
  } as any)

const LayoutShopProductProductSlugRoute =
  LayoutShopProductProductSlugImport.update({
    path: '/shop/product/$productSlug',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutShopLayoutShopCategorySlugIndexRoute =
  LayoutShopLayoutShopCategorySlugIndexImport.update({
    path: '/shop/$categorySlug/',
    getParentRoute: () => LayoutShopLayoutRoute,
  } as any)

const LayoutOrdersLayoutShopOrdersIndexRoute =
  LayoutOrdersLayoutShopOrdersIndexImport.update({
    path: '/shop/orders/',
    getParentRoute: () => LayoutOrdersLayoutRoute,
  } as any)

const LayoutShopLayoutShopCategorySlugSubcategorySlugRoute =
  LayoutShopLayoutShopCategorySlugSubcategorySlugImport.update({
    path: '/shop/$categorySlug/$subcategorySlug',
    getParentRoute: () => LayoutShopLayoutRoute,
  } as any)

const LayoutOrdersLayoutShopOrdersOrderIdRoute =
  LayoutOrdersLayoutShopOrdersOrderIdImport.update({
    path: '/shop/orders/$orderId',
    getParentRoute: () => LayoutOrdersLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_ordersLayout': {
      id: '/_layout/_ordersLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutOrdersLayoutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_shopLayout': {
      id: '/_layout/_shopLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutShopLayoutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/contact-us': {
      id: '/_layout/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof LayoutContactUsImport
      parentRoute: typeof LayoutImport
    }
    '/shop/bag/': {
      id: '/shop/bag/'
      path: '/shop/bag'
      fullPath: '/shop/bag'
      preLoaderRoute: typeof ShopBagIndexImport
      parentRoute: typeof rootRoute
    }
    '/shop/checkout/': {
      id: '/shop/checkout/'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/shop/product/$productSlug': {
      id: '/_layout/shop/product/$productSlug'
      path: '/shop/product/$productSlug'
      fullPath: '/shop/product/$productSlug'
      preLoaderRoute: typeof LayoutShopProductProductSlugImport
      parentRoute: typeof LayoutImport
    }
    '/shop/checkout/$sessionIdSlug/complete': {
      id: '/shop/checkout/$sessionIdSlug/complete'
      path: '/shop/checkout/$sessionIdSlug/complete'
      fullPath: '/shop/checkout/$sessionIdSlug/complete'
      preLoaderRoute: typeof ShopCheckoutSessionIdSlugCompleteImport
      parentRoute: typeof rootRoute
    }
    '/_layout/policies/delivery-returns-exchanges/': {
      id: '/_layout/policies/delivery-returns-exchanges/'
      path: '/policies/delivery-returns-exchanges'
      fullPath: '/policies/delivery-returns-exchanges'
      preLoaderRoute: typeof LayoutPoliciesDeliveryReturnsExchangesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/policies/privacy/': {
      id: '/_layout/policies/privacy/'
      path: '/policies/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof LayoutPoliciesPrivacyIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/policies/tos/': {
      id: '/_layout/policies/tos/'
      path: '/policies/tos'
      fullPath: '/policies/tos'
      preLoaderRoute: typeof LayoutPoliciesTosIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/shop/saved/': {
      id: '/_layout/shop/saved/'
      path: '/shop/saved'
      fullPath: '/shop/saved'
      preLoaderRoute: typeof LayoutShopSavedIndexImport
      parentRoute: typeof LayoutImport
    }
    '/shop/checkout/$sessionIdSlug/': {
      id: '/shop/checkout/$sessionIdSlug/'
      path: '/shop/checkout/$sessionIdSlug'
      fullPath: '/shop/checkout/$sessionIdSlug'
      preLoaderRoute: typeof ShopCheckoutSessionIdSlugIndexImport
      parentRoute: typeof rootRoute
    }
    '/shop/checkout/complete/': {
      id: '/shop/checkout/complete/'
      path: '/shop/checkout/complete'
      fullPath: '/shop/checkout/complete'
      preLoaderRoute: typeof ShopCheckoutCompleteIndexImport
      parentRoute: typeof rootRoute
    }
    '/shop/checkout/verify/': {
      id: '/shop/checkout/verify/'
      path: '/shop/checkout/verify'
      fullPath: '/shop/checkout/verify'
      preLoaderRoute: typeof ShopCheckoutVerifyIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_ordersLayout/shop/orders/$orderId': {
      id: '/_layout/_ordersLayout/shop/orders/$orderId'
      path: '/shop/orders/$orderId'
      fullPath: '/shop/orders/$orderId'
      preLoaderRoute: typeof LayoutOrdersLayoutShopOrdersOrderIdImport
      parentRoute: typeof LayoutOrdersLayoutImport
    }
    '/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug': {
      id: '/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug'
      path: '/shop/$categorySlug/$subcategorySlug'
      fullPath: '/shop/$categorySlug/$subcategorySlug'
      preLoaderRoute: typeof LayoutShopLayoutShopCategorySlugSubcategorySlugImport
      parentRoute: typeof LayoutShopLayoutImport
    }
    '/_layout/_ordersLayout/shop/orders/': {
      id: '/_layout/_ordersLayout/shop/orders/'
      path: '/shop/orders'
      fullPath: '/shop/orders'
      preLoaderRoute: typeof LayoutOrdersLayoutShopOrdersIndexImport
      parentRoute: typeof LayoutOrdersLayoutImport
    }
    '/_layout/_shopLayout/shop/$categorySlug/': {
      id: '/_layout/_shopLayout/shop/$categorySlug/'
      path: '/shop/$categorySlug'
      fullPath: '/shop/$categorySlug'
      preLoaderRoute: typeof LayoutShopLayoutShopCategorySlugIndexImport
      parentRoute: typeof LayoutShopLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutOrdersLayoutRouteChildren {
  LayoutOrdersLayoutShopOrdersOrderIdRoute: typeof LayoutOrdersLayoutShopOrdersOrderIdRoute
  LayoutOrdersLayoutShopOrdersIndexRoute: typeof LayoutOrdersLayoutShopOrdersIndexRoute
}

const LayoutOrdersLayoutRouteChildren: LayoutOrdersLayoutRouteChildren = {
  LayoutOrdersLayoutShopOrdersOrderIdRoute:
    LayoutOrdersLayoutShopOrdersOrderIdRoute,
  LayoutOrdersLayoutShopOrdersIndexRoute:
    LayoutOrdersLayoutShopOrdersIndexRoute,
}

const LayoutOrdersLayoutRouteWithChildren =
  LayoutOrdersLayoutRoute._addFileChildren(LayoutOrdersLayoutRouteChildren)

interface LayoutShopLayoutRouteChildren {
  LayoutShopLayoutShopCategorySlugSubcategorySlugRoute: typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRoute
  LayoutShopLayoutShopCategorySlugIndexRoute: typeof LayoutShopLayoutShopCategorySlugIndexRoute
}

const LayoutShopLayoutRouteChildren: LayoutShopLayoutRouteChildren = {
  LayoutShopLayoutShopCategorySlugSubcategorySlugRoute:
    LayoutShopLayoutShopCategorySlugSubcategorySlugRoute,
  LayoutShopLayoutShopCategorySlugIndexRoute:
    LayoutShopLayoutShopCategorySlugIndexRoute,
}

const LayoutShopLayoutRouteWithChildren =
  LayoutShopLayoutRoute._addFileChildren(LayoutShopLayoutRouteChildren)

interface LayoutRouteChildren {
  LayoutOrdersLayoutRoute: typeof LayoutOrdersLayoutRouteWithChildren
  LayoutShopLayoutRoute: typeof LayoutShopLayoutRouteWithChildren
  LayoutContactUsRoute: typeof LayoutContactUsRoute
  LayoutShopProductProductSlugRoute: typeof LayoutShopProductProductSlugRoute
  LayoutPoliciesDeliveryReturnsExchangesIndexRoute: typeof LayoutPoliciesDeliveryReturnsExchangesIndexRoute
  LayoutPoliciesPrivacyIndexRoute: typeof LayoutPoliciesPrivacyIndexRoute
  LayoutPoliciesTosIndexRoute: typeof LayoutPoliciesTosIndexRoute
  LayoutShopSavedIndexRoute: typeof LayoutShopSavedIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutOrdersLayoutRoute: LayoutOrdersLayoutRouteWithChildren,
  LayoutShopLayoutRoute: LayoutShopLayoutRouteWithChildren,
  LayoutContactUsRoute: LayoutContactUsRoute,
  LayoutShopProductProductSlugRoute: LayoutShopProductProductSlugRoute,
  LayoutPoliciesDeliveryReturnsExchangesIndexRoute:
    LayoutPoliciesDeliveryReturnsExchangesIndexRoute,
  LayoutPoliciesPrivacyIndexRoute: LayoutPoliciesPrivacyIndexRoute,
  LayoutPoliciesTosIndexRoute: LayoutPoliciesTosIndexRoute,
  LayoutShopSavedIndexRoute: LayoutShopSavedIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutShopLayoutRouteWithChildren
  '/contact-us': typeof LayoutContactUsRoute
  '/shop/bag': typeof ShopBagIndexRoute
  '/shop/checkout': typeof ShopCheckoutIndexRoute
  '/shop/product/$productSlug': typeof LayoutShopProductProductSlugRoute
  '/shop/checkout/$sessionIdSlug/complete': typeof ShopCheckoutSessionIdSlugCompleteRoute
  '/policies/delivery-returns-exchanges': typeof LayoutPoliciesDeliveryReturnsExchangesIndexRoute
  '/policies/privacy': typeof LayoutPoliciesPrivacyIndexRoute
  '/policies/tos': typeof LayoutPoliciesTosIndexRoute
  '/shop/saved': typeof LayoutShopSavedIndexRoute
  '/shop/checkout/$sessionIdSlug': typeof ShopCheckoutSessionIdSlugIndexRoute
  '/shop/checkout/complete': typeof ShopCheckoutCompleteIndexRoute
  '/shop/checkout/verify': typeof ShopCheckoutVerifyIndexRoute
  '/shop/orders/$orderId': typeof LayoutOrdersLayoutShopOrdersOrderIdRoute
  '/shop/$categorySlug/$subcategorySlug': typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRoute
  '/shop/orders': typeof LayoutOrdersLayoutShopOrdersIndexRoute
  '/shop/$categorySlug': typeof LayoutShopLayoutShopCategorySlugIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutShopLayoutRouteWithChildren
  '/contact-us': typeof LayoutContactUsRoute
  '/shop/bag': typeof ShopBagIndexRoute
  '/shop/checkout': typeof ShopCheckoutIndexRoute
  '/shop/product/$productSlug': typeof LayoutShopProductProductSlugRoute
  '/shop/checkout/$sessionIdSlug/complete': typeof ShopCheckoutSessionIdSlugCompleteRoute
  '/policies/delivery-returns-exchanges': typeof LayoutPoliciesDeliveryReturnsExchangesIndexRoute
  '/policies/privacy': typeof LayoutPoliciesPrivacyIndexRoute
  '/policies/tos': typeof LayoutPoliciesTosIndexRoute
  '/shop/saved': typeof LayoutShopSavedIndexRoute
  '/shop/checkout/$sessionIdSlug': typeof ShopCheckoutSessionIdSlugIndexRoute
  '/shop/checkout/complete': typeof ShopCheckoutCompleteIndexRoute
  '/shop/checkout/verify': typeof ShopCheckoutVerifyIndexRoute
  '/shop/orders/$orderId': typeof LayoutOrdersLayoutShopOrdersOrderIdRoute
  '/shop/$categorySlug/$subcategorySlug': typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRoute
  '/shop/orders': typeof LayoutOrdersLayoutShopOrdersIndexRoute
  '/shop/$categorySlug': typeof LayoutShopLayoutShopCategorySlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_ordersLayout': typeof LayoutOrdersLayoutRouteWithChildren
  '/_layout/_shopLayout': typeof LayoutShopLayoutRouteWithChildren
  '/_layout/contact-us': typeof LayoutContactUsRoute
  '/shop/bag/': typeof ShopBagIndexRoute
  '/shop/checkout/': typeof ShopCheckoutIndexRoute
  '/_layout/shop/product/$productSlug': typeof LayoutShopProductProductSlugRoute
  '/shop/checkout/$sessionIdSlug/complete': typeof ShopCheckoutSessionIdSlugCompleteRoute
  '/_layout/policies/delivery-returns-exchanges/': typeof LayoutPoliciesDeliveryReturnsExchangesIndexRoute
  '/_layout/policies/privacy/': typeof LayoutPoliciesPrivacyIndexRoute
  '/_layout/policies/tos/': typeof LayoutPoliciesTosIndexRoute
  '/_layout/shop/saved/': typeof LayoutShopSavedIndexRoute
  '/shop/checkout/$sessionIdSlug/': typeof ShopCheckoutSessionIdSlugIndexRoute
  '/shop/checkout/complete/': typeof ShopCheckoutCompleteIndexRoute
  '/shop/checkout/verify/': typeof ShopCheckoutVerifyIndexRoute
  '/_layout/_ordersLayout/shop/orders/$orderId': typeof LayoutOrdersLayoutShopOrdersOrderIdRoute
  '/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug': typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRoute
  '/_layout/_ordersLayout/shop/orders/': typeof LayoutOrdersLayoutShopOrdersIndexRoute
  '/_layout/_shopLayout/shop/$categorySlug/': typeof LayoutShopLayoutShopCategorySlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/contact-us'
    | '/shop/bag'
    | '/shop/checkout'
    | '/shop/product/$productSlug'
    | '/shop/checkout/$sessionIdSlug/complete'
    | '/policies/delivery-returns-exchanges'
    | '/policies/privacy'
    | '/policies/tos'
    | '/shop/saved'
    | '/shop/checkout/$sessionIdSlug'
    | '/shop/checkout/complete'
    | '/shop/checkout/verify'
    | '/shop/orders/$orderId'
    | '/shop/$categorySlug/$subcategorySlug'
    | '/shop/orders'
    | '/shop/$categorySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/contact-us'
    | '/shop/bag'
    | '/shop/checkout'
    | '/shop/product/$productSlug'
    | '/shop/checkout/$sessionIdSlug/complete'
    | '/policies/delivery-returns-exchanges'
    | '/policies/privacy'
    | '/policies/tos'
    | '/shop/saved'
    | '/shop/checkout/$sessionIdSlug'
    | '/shop/checkout/complete'
    | '/shop/checkout/verify'
    | '/shop/orders/$orderId'
    | '/shop/$categorySlug/$subcategorySlug'
    | '/shop/orders'
    | '/shop/$categorySlug'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/_ordersLayout'
    | '/_layout/_shopLayout'
    | '/_layout/contact-us'
    | '/shop/bag/'
    | '/shop/checkout/'
    | '/_layout/shop/product/$productSlug'
    | '/shop/checkout/$sessionIdSlug/complete'
    | '/_layout/policies/delivery-returns-exchanges/'
    | '/_layout/policies/privacy/'
    | '/_layout/policies/tos/'
    | '/_layout/shop/saved/'
    | '/shop/checkout/$sessionIdSlug/'
    | '/shop/checkout/complete/'
    | '/shop/checkout/verify/'
    | '/_layout/_ordersLayout/shop/orders/$orderId'
    | '/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug'
    | '/_layout/_ordersLayout/shop/orders/'
    | '/_layout/_shopLayout/shop/$categorySlug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  ShopBagIndexRoute: typeof ShopBagIndexRoute
  ShopCheckoutIndexRoute: typeof ShopCheckoutIndexRoute
  ShopCheckoutSessionIdSlugCompleteRoute: typeof ShopCheckoutSessionIdSlugCompleteRoute
  ShopCheckoutSessionIdSlugIndexRoute: typeof ShopCheckoutSessionIdSlugIndexRoute
  ShopCheckoutCompleteIndexRoute: typeof ShopCheckoutCompleteIndexRoute
  ShopCheckoutVerifyIndexRoute: typeof ShopCheckoutVerifyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  ShopBagIndexRoute: ShopBagIndexRoute,
  ShopCheckoutIndexRoute: ShopCheckoutIndexRoute,
  ShopCheckoutSessionIdSlugCompleteRoute:
    ShopCheckoutSessionIdSlugCompleteRoute,
  ShopCheckoutSessionIdSlugIndexRoute: ShopCheckoutSessionIdSlugIndexRoute,
  ShopCheckoutCompleteIndexRoute: ShopCheckoutCompleteIndexRoute,
  ShopCheckoutVerifyIndexRoute: ShopCheckoutVerifyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/shop/bag/",
        "/shop/checkout/",
        "/shop/checkout/$sessionIdSlug/complete",
        "/shop/checkout/$sessionIdSlug/",
        "/shop/checkout/complete/",
        "/shop/checkout/verify/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_ordersLayout",
        "/_layout/_shopLayout",
        "/_layout/contact-us",
        "/_layout/shop/product/$productSlug",
        "/_layout/policies/delivery-returns-exchanges/",
        "/_layout/policies/privacy/",
        "/_layout/policies/tos/",
        "/_layout/shop/saved/"
      ]
    },
    "/_layout/_ordersLayout": {
      "filePath": "_layout/_ordersLayout.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_ordersLayout/shop/orders/$orderId",
        "/_layout/_ordersLayout/shop/orders/"
      ]
    },
    "/_layout/_shopLayout": {
      "filePath": "_layout/_shopLayout.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug",
        "/_layout/_shopLayout/shop/$categorySlug/"
      ]
    },
    "/_layout/contact-us": {
      "filePath": "_layout/contact-us.tsx",
      "parent": "/_layout"
    },
    "/shop/bag/": {
      "filePath": "shop/bag.index.tsx"
    },
    "/shop/checkout/": {
      "filePath": "shop/checkout/index.tsx"
    },
    "/_layout/shop/product/$productSlug": {
      "filePath": "_layout/shop.product.$productSlug.tsx",
      "parent": "/_layout"
    },
    "/shop/checkout/$sessionIdSlug/complete": {
      "filePath": "shop/checkout/$sessionIdSlug/complete.tsx"
    },
    "/_layout/policies/delivery-returns-exchanges/": {
      "filePath": "_layout/policies/delivery-returns-exchanges.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/policies/privacy/": {
      "filePath": "_layout/policies/privacy.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/policies/tos/": {
      "filePath": "_layout/policies/tos.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/shop/saved/": {
      "filePath": "_layout/shop.saved.index.tsx",
      "parent": "/_layout"
    },
    "/shop/checkout/$sessionIdSlug/": {
      "filePath": "shop/checkout/$sessionIdSlug/index.tsx"
    },
    "/shop/checkout/complete/": {
      "filePath": "shop/checkout/complete.index.tsx"
    },
    "/shop/checkout/verify/": {
      "filePath": "shop/checkout/verify.index.tsx"
    },
    "/_layout/_ordersLayout/shop/orders/$orderId": {
      "filePath": "_layout/_ordersLayout/shop/orders/$orderId.tsx",
      "parent": "/_layout/_ordersLayout"
    },
    "/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug": {
      "filePath": "_layout/_shopLayout/shop/$categorySlug/$subcategorySlug.tsx",
      "parent": "/_layout/_shopLayout"
    },
    "/_layout/_ordersLayout/shop/orders/": {
      "filePath": "_layout/_ordersLayout/shop/orders/index.tsx",
      "parent": "/_layout/_ordersLayout"
    },
    "/_layout/_shopLayout/shop/$categorySlug/": {
      "filePath": "_layout/_shopLayout/shop/$categorySlug/index.tsx",
      "parent": "/_layout/_shopLayout"
    }
  }
}
ROUTE_MANIFEST_END */
