import { v } from "convex/values";

export const sharedDemoRestoreStateSchema = v.object({
  appliedAt: v.optional(v.number()),
  baselineVersion: v.number(),
  cleanupTerminalIds: v.optional(v.array(v.id("posTerminal"))),
  completedAt: v.optional(v.number()),
  epoch: v.number(),
  failureCode: v.optional(v.string()),
  idempotencyKey: v.optional(v.string()),
  phase: v.optional(v.union(v.literal("leased"), v.literal("applied"))),
  restoreSource: v.optional(v.union(v.literal("hourly"), v.literal("manual"))),
  restoredDocuments: v.optional(v.number()),
  startedAt: v.optional(v.number()),
  status: v.union(v.literal("ready"), v.literal("restoring"), v.literal("failed")),
  storeId: v.id("store"),
});

export const sharedDemoBaselineRowSchema = v.object({
  baselineVersion: v.number(),
  domain: v.string(),
  expectedCount: v.number(),
  storeId: v.id("store"),
});

export const sharedDemoRestoreAuditSchema = v.object({
  baselineVersion: v.number(),
  epoch: v.number(),
  occurredAt: v.number(),
  outcome: v.union(v.literal("ready"), v.literal("failed")),
  source: v.union(v.literal("hourly"), v.literal("manual")),
  storeId: v.id("store"),
});

export const sharedDemoBaselineDocumentSchema = v.object({
  baselineVersion: v.number(),
  document: v.any(),
  documentId: v.string(),
  storeId: v.id("store"),
  tableName: v.union(
    v.literal("posTransaction"),
    v.literal("posTransactionItem"),
    v.literal("posTerminal"),
    v.literal("posLocalSyncConflict"),
    v.literal("posLocalSyncCursor"),
    v.literal("posLocalSyncMapping"),
    v.literal("posLocalSyncEvent"),
    v.literal("posLifecycleJournal"),
    v.literal("posLifecycleJournalCursor"),
    v.literal("posRegisterMappingAuthority"),
    v.literal("posRegisterAuthorityReplicationStatus"),
    v.literal("posPendingCheckoutItem"),
    v.literal("posSession"),
    v.literal("posSessionItem"),
    v.literal("inventoryMovement"),
    v.literal("product"),
    v.literal("productSku"),
    v.literal("productSkuSearch"),
    v.literal("reportingInventoryPosition"),
    v.literal("reportingInventoryPositionRevision"),
    v.literal("reportingInventoryEffect"),
    v.literal("reportingInventoryEffectSourceReference"),
    v.literal("reportingInventoryDeficitLedger"),
    v.literal("reportingInventoryDeficitLot"),
    v.literal("reportingInventoryDeficitResolutionWork"),
    v.literal("reportingInventoryOccurrenceReplay"),
    v.literal("reportingInventoryOccurrenceReplayLot"),
    v.literal("reportingInventoryOccurrenceReplayOutcome"),
    v.literal("stockAdjustmentBatch"),
    v.literal("cycleCountDraft"),
    v.literal("cycleCountDraftLine"),
    v.literal("posRegisterSessionActivity"),
    v.literal("registerSession"),
    v.literal("onlineOrder"),
    v.literal("onlineOrderItem"),
    v.literal("approvalRequest"),
    v.literal("approvalProof"),
    v.literal("approvalRequesterChallenge"),
    v.literal("managerElevation"),
    v.literal("operationalWorkItem"),
    v.literal("operationalEvent"),
    v.literal("dailyOpening"),
    v.literal("reportingIngress"),
    v.literal("reportingIngressSourceReference"),
    v.literal("reportingIngressLine"),
    v.literal("reportingIngressConflict"),
    v.literal("reportingFact"),
    v.literal("reportingFactSourceReference"),
    v.literal("reportingFactProcessingAttempt"),
    v.literal("reportingQuarantine"),
    v.literal("reportingProjectionHealth"),
    v.literal("reportingReconciliationDiscrepancy"),
    v.literal("reportingProjectionGeneration"),
    v.literal("reportingProjectionActivation"),
    v.literal("reportingStoreDayProjection"),
    v.literal("reportingStoreIntradayProjection"),
    v.literal("reportingStoreIntradayScheduleState"),
    v.literal("reportingSkuDayProjection"),
    v.literal("reportingCurrentValuationProjection"),
    v.literal("reportingRangeProjection"),
    v.literal("reportingAttentionProjection"),
    v.literal("reportingDailyCloseProjection"),
    v.literal("reportingSkuInsightProjection"),
    v.literal("reportingMetricCoverage"),
    v.literal("reportingStorePeriodSummary"),
    v.literal("reportingSkuPeriodSummary"),
    v.literal("reportingSkuPeriodClassification"),
    v.literal("reportingPeriodRollup"),
    v.literal("reportingPeriodFacet"),
    v.literal("reportingInventoryExposureSummary"),
    v.literal("reportingInventoryMovementSummary"),
    v.literal("reportingInventoryPeriodSummary"),
    v.literal("reportingDailyCloseTrust"),
    v.literal("reportingReadCursorContext"),
    v.literal("reportingWorkspaceMaterializationEpoch"),
    v.literal("reportingWorkspaceReadModelActivation"),
    v.literal("reportingReadBundle"),
    v.literal("reportingReadBundleActivation"),
    v.literal("reportingProjectionEvidence"),
    v.literal("reportingSkuEvidence"),
    v.literal("staffProfile"),
    v.literal("staffCredential"),
    v.literal("staffMessage"),
  ),
});
