import { access, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

const GENERATED_DOC_NOTICE =
  "> Generated by `bun run harness:generate`. Regenerate instead of editing by hand.";
const PLAYWRIGHT_TEST_DIR_PATTERN = /testDir\s*:\s*["'`](.+?)["'`]/;
const TEST_FILE_PATTERN = /\.(?:test|spec)\.[cm]?[jt]sx?$/;

export const GENERATED_HARNESS_DOCS = [
  "docs/agent/route-index.md",
  "docs/agent/test-index.md",
  "docs/agent/key-folder-index.md",
  "docs/agent/validation-guide.md",
  "docs/agent/validation-map.json",
] as const;

type ValidationCommand =
  | { kind: "script"; script: string }
  | { kind: "raw"; command: string };

type GeneratedHarnessAppConfig = {
  appName: "athena-webapp" | "storefront-webapp";
  label: string;
  packageDir: string;
  routeRoot: string;
  keyFolderGroups: Array<{
    title: string;
    folders: Array<{ path: string; description: string }>;
  }>;
  validationScenarios: Array<{
    title: string;
    touchedPaths: string[];
    commands: ValidationCommand[];
    note: string;
  }>;
};

type PackageConfig = {
  packageName: string;
  scripts: Record<string, string>;
};

const APP_CONFIGS: GeneratedHarnessAppConfig[] = [
  {
    appName: "athena-webapp",
    label: "Athena Webapp",
    packageDir: "packages/athena-webapp",
    routeRoot: "src/routes",
    keyFolderGroups: [
      {
        title: "Core app surfaces",
        folders: [
          {
            path: "src/routes",
            description: "TanStack route entrypoints and authenticated shells.",
          },
          {
            path: "src/components",
            description: "UI components, views, and package-local feature widgets.",
          },
          {
            path: "src/hooks",
            description: "React hooks that fan out auth, shell, and feature state.",
          },
          {
            path: "src/contexts",
            description: "Context providers for app-wide state and wiring.",
          },
          {
            path: "src/lib",
            description: "Shared frontend helpers, schemas, and package utilities.",
          },
          {
            path: "src/utils",
            description: "Cross-cutting browser helpers and lower-level utilities.",
          },
        ],
      },
      {
        title: "Backend and test surfaces",
        folders: [
          {
            path: "convex",
            description: "Convex functions, HTTP composition, schemas, and backend tests.",
          },
          {
            path: "src/tests",
            description: "Focused browser-facing regression tests.",
          },
          {
            path: "src/test",
            description: "Package test harness helpers and setup.",
          },
        ],
      },
    ],
    validationScenarios: [
      {
        title: "Route or UI-only edits",
        touchedPaths: [
          "src/assets",
          "src/config.ts",
          "src/routes",
          "src/components",
          "src/hooks",
          "src/contexts",
          "src/index.css",
        ],
        commands: [
          { kind: "script", script: "test" },
          { kind: "script", script: "lint:architecture" },
        ],
        note: "Use this for authenticated dashboard flows, route trees, and UI behavior changes that stay inside the frontend shell.",
      },
      {
        title: "Shared-lib or utility edits",
        touchedPaths: ["src/lib", "src/settings", "src/utils", "src/stores"],
        commands: [
          { kind: "script", script: "test" },
          {
            kind: "raw",
            command: "bunx tsc --noEmit -p packages/athena-webapp/tsconfig.json",
          },
        ],
        note: "Reach for the package suite first, then typecheck when helpers or shared state can affect many call sites.",
      },
      {
        title: "Frontend test harness edits",
        touchedPaths: ["src/test", "src/tests"],
        commands: [{ kind: "script", script: "test" }],
        note: "Run the package suite when package-local frontend test helpers or focused regression tests change.",
      },
      {
        title: "Convex or backend-adjacent edits",
        touchedPaths: ["convex", "src/routes/_authed", "src/main.tsx"],
        commands: [
          { kind: "script", script: "test" },
          { kind: "script", script: "audit:convex" },
          { kind: "script", script: "lint:convex:changed" },
        ],
        note: "Any change that can affect Convex HTTP wiring, schemas, queries, or route-to-backend composition should include the Convex audit pair.",
      },
      {
        title: "Route runtime or build-pipeline edits",
        touchedPaths: ["src/main.tsx", "src/routeTree.gen.ts", "vite.config.ts"],
        commands: [
          {
            kind: "raw",
            command: "bunx tsc --noEmit -p packages/athena-webapp/tsconfig.json",
          },
          { kind: "script", script: "build" },
        ],
        note: "Run these when bootstrap, generated router state, or package build configuration changes.",
      },
    ],
  },
  {
    appName: "storefront-webapp",
    label: "Storefront Webapp",
    packageDir: "packages/storefront-webapp",
    routeRoot: "src/routes",
    keyFolderGroups: [
      {
        title: "Core app surfaces",
        folders: [
          {
            path: "src/routes",
            description: "TanStack Start routes, layouts, and browser journey entrypoints.",
          },
          {
            path: "src/components",
            description: "Reusable storefront UI and feature-specific checkout/catalog components.",
          },
          {
            path: "src/hooks",
            description: "Client hooks for bag, routing, observability, and auth interactions.",
          },
          {
            path: "src/contexts",
            description: "Shared client providers for store, navigation, and observability state.",
          },
          {
            path: "src/lib",
            description: "Shared utilities, query helpers, schemas, and domain logic.",
          },
          {
            path: "src/api",
            description: "Backend-facing request wrappers and typed API helpers.",
          },
        ],
      },
      {
        title: "Validation and support surfaces",
        folders: [
          {
            path: "tests/e2e",
            description: "Playwright browser journeys and redirect/payment coverage.",
          },
          {
            path: "src/utils",
            description: "Lower-level runtime helpers used across route and API code.",
          },
        ],
      },
    ],
    validationScenarios: [
      {
        title: "Route or UI-only edits",
        touchedPaths: [
          "src/assets",
          "src/client.tsx",
          "src/config.ts",
          "src/index.css",
          "src/main.tsx",
          "src/router.tsx",
          "src/routes",
          "src/components",
          "src/hooks",
          "src/contexts",
          "src/routeTree.gen.ts",
          "src/ssr.tsx",
        ],
        commands: [{ kind: "script", script: "test" }],
        note: "Start here for most layout, component, and route behavior changes that do not alter the checkout or browser-journey contract.",
      },
      {
        title: "Shared-lib, utility, or API-wrapper edits",
        touchedPaths: ["src/lib", "src/utils", "src/api"],
        commands: [
          { kind: "script", script: "test" },
          {
            kind: "raw",
            command:
              "bunx tsc --noEmit -p packages/storefront-webapp/tsconfig.json",
          },
        ],
        note: "These surfaces fan out widely across the app, so pair the default suite with a typecheck when shared helpers change.",
      },
      {
        title: "Checkout or auth route-boundary edits",
        touchedPaths: [
          "src/routes/shop/checkout",
          "src/components/checkout",
          "src/routes/auth.verify.tsx",
        ],
        commands: [
          { kind: "script", script: "test" },
          { kind: "script", script: "lint:architecture" },
        ],
        note: "Use the scoped architecture lint when lower-level helpers could accidentally depend on checkout or auth route entrypoints.",
      },
      {
        title: "Full browser journeys and payment redirects",
        touchedPaths: [
          "tests/e2e",
          "src/routes/shop/checkout",
          "src/components/checkout",
        ],
        commands: [
          { kind: "script", script: "test" },
          { kind: "script", script: "test:e2e" },
        ],
        note: "Run the Playwright layer when navigation, checkout, or redirect behavior could change the end-to-end customer path.",
      },
    ],
  },
];

function normalizeRepoPath(filePath: string) {
  return filePath.split(path.sep).join("/");
}

function shouldSkipGeneratedEntry(entryName: string) {
  return entryName.startsWith(".");
}

async function fileExists(filePath: string) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function walkFiles(dirPath: string): Promise<string[]> {
  if (!(await fileExists(dirPath))) {
    return [];
  }

  const entries = await readdir(dirPath, { withFileTypes: true });
  const files = await Promise.all(
    entries
      .filter((entry) => !shouldSkipGeneratedEntry(entry.name))
      .map(async (entry) => {
      const entryPath = path.join(dirPath, entry.name);
      if (entry.isDirectory()) {
        return walkFiles(entryPath);
      }

      return [entryPath];
      })
  );

  return files.flat();
}

async function readPackageConfig(rootDir: string, packageDir: string) {
  const packageJson = JSON.parse(
    await readFile(path.join(rootDir, packageDir, "package.json"), "utf8")
  ) as {
    name?: string;
    scripts?: Record<string, string>;
  };

  if (!packageJson.name) {
    throw new Error(`Missing package name for ${packageDir}.`);
  }

  return {
    packageName: packageJson.name,
    scripts: packageJson.scripts ?? {},
  } satisfies PackageConfig;
}

function toDocPath(packageRelativePath: string) {
  return `../../${normalizeRepoPath(packageRelativePath)}`;
}

function formatMarkdownLink(packageRelativePath: string) {
  return `[\`${packageRelativePath}\`](${toDocPath(packageRelativePath)})`;
}

function headingFromSegment(segment: string | undefined) {
  if (!segment) {
    return "Top-level entries";
  }

  return `Section \`${segment}\``;
}

function summarizeChildren(children: string[]) {
  if (children.length === 0) {
    return "no nested entries yet";
  }

  return children.slice(0, 5).join(", ");
}

async function collectRouteGroups(
  rootDir: string,
  config: GeneratedHarnessAppConfig
) {
  const routeRoot = path.join(rootDir, config.packageDir, config.routeRoot);
  const files = (await walkFiles(routeRoot))
    .filter((filePath) => /\.(?:[cm]?[jt]sx?)$/.test(filePath))
    .map((filePath) =>
      normalizeRepoPath(path.relative(path.join(rootDir, config.packageDir), filePath))
    )
    .sort();
  const groups = new Map<string, string[]>();

  for (const routePath of files) {
    const relativeToRouteRoot = routePath.slice(`${config.routeRoot}/`.length);
    const groupKey = relativeToRouteRoot.includes("/")
      ? (relativeToRouteRoot.split("/", 1)[0] ?? "")
      : "";
    const existing = groups.get(groupKey) ?? [];
    existing.push(routePath);
    groups.set(groupKey, existing);
  }

  return groups;
}

async function collectTestFiles(
  rootDir: string,
  config: GeneratedHarnessAppConfig
) {
  const packageRoot = path.join(rootDir, config.packageDir);
  const files = await walkFiles(packageRoot);
  const testFiles = files
    .map((filePath) =>
      normalizeRepoPath(path.relative(packageRoot, filePath))
    )
    .filter(
      (repoRelativePath) =>
        !repoRelativePath.startsWith("node_modules/") &&
        !repoRelativePath.startsWith("dist/") &&
        !repoRelativePath.startsWith("coverage/") &&
        TEST_FILE_PATTERN.test(repoRelativePath)
    )
    .sort();
  const groups = new Map<string, string[]>();

  for (const testFile of testFiles) {
    const groupKey = testFile.split("/", 1)[0] ?? "other";
    const existing = groups.get(groupKey) ?? [];
    existing.push(testFile);
    groups.set(groupKey, existing);
  }

  return groups;
}

async function collectTestSurfaceRoots(
  rootDir: string,
  config: GeneratedHarnessAppConfig,
  packageConfig: PackageConfig
) {
  const packageRoot = path.join(rootDir, config.packageDir);
  const allFiles = await walkFiles(packageRoot);
  const surfaces = new Set<string>();

  for (const filePath of allFiles) {
    const repoRelativePath = normalizeRepoPath(path.relative(packageRoot, filePath));
    if (
      repoRelativePath.startsWith("node_modules/") ||
      repoRelativePath.startsWith("dist/") ||
      repoRelativePath.startsWith("coverage/")
    ) {
      continue;
    }

    if (!TEST_FILE_PATTERN.test(repoRelativePath)) {
      continue;
    }

    surfaces.add(repoRelativePath.split("/", 1)[0] ?? repoRelativePath);
  }

  const playwrightConfigPath = path.join(packageRoot, "playwright.config.ts");
  if (
    packageConfig.scripts["test:e2e"] &&
    (await fileExists(playwrightConfigPath))
  ) {
    const playwrightConfig = await readFile(playwrightConfigPath, "utf8");
    const testDirMatch = playwrightConfig.match(PLAYWRIGHT_TEST_DIR_PATTERN);
    const testDir = testDirMatch?.[1]?.replace(/^\.\//, "").replace(/\/+$/, "");
    if (testDir) {
      surfaces.add(testDir);
    }
  }

  return [...surfaces].sort();
}

async function collectFolderFacts(
  rootDir: string,
  config: GeneratedHarnessAppConfig,
  folderPath: string
) {
  const absoluteFolderPath = path.join(rootDir, config.packageDir, folderPath);
  if (!(await fileExists(absoluteFolderPath))) {
    return null;
  }

  const allFiles = await walkFiles(absoluteFolderPath);
  const directChildren = await readdir(absoluteFolderPath, { withFileTypes: true });
  const childNames = directChildren
    .filter((entry) => !shouldSkipGeneratedEntry(entry.name))
    .map((entry) => entry.name)
    .sort();

  return {
    fileCount: allFiles.length,
    childSummary: summarizeChildren(childNames),
  };
}

function formatScriptCommand(packageConfig: PackageConfig, script: string) {
  if (!packageConfig.scripts[script]) {
    throw new Error(
      `Missing required script "${packageConfig.packageName}:${script}" while generating harness docs.`
    );
  }

  return `bun run --filter '${packageConfig.packageName}' ${script}`;
}

function toRepoValidationPath(packageDir: string, touchedPath: string) {
  const normalizedPath = normalizeRepoPath(touchedPath).replace(/\/+$/, "");
  return normalizeRepoPath(path.posix.join(packageDir, normalizedPath));
}

function slugifyTitle(title: string) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function formatValidationCommandForDoc(
  packageConfig: PackageConfig,
  command: ValidationCommand
) {
  return command.kind === "raw"
    ? command.command
    : formatScriptCommand(packageConfig, command.script);
}

function toGeneratedValidationMap(
  config: GeneratedHarnessAppConfig,
  packageConfig: PackageConfig
) {
  return {
    workspace: packageConfig.packageName,
    packageDir: config.packageDir,
    surfaces: [
      ...config.validationScenarios.map((scenario) => ({
        name: slugifyTitle(scenario.title),
        pathPrefixes: scenario.touchedPaths.map((touchedPath) =>
          toRepoValidationPath(config.packageDir, touchedPath)
        ),
        commands: scenario.commands,
      })),
      {
        name: "harness-docs",
        pathPrefixes: [
          `${config.packageDir}/AGENTS.md`,
          `${config.packageDir}/docs/agent`,
        ],
        commands: [] as ValidationCommand[],
      },
    ],
  };
}

function buildGeneratedDoc(
  title: string,
  introLines: string[],
  bodyLines: string[]
) {
  return [title, "", GENERATED_DOC_NOTICE, "", ...introLines, "", ...bodyLines, ""]
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

async function buildRouteIndex(
  rootDir: string,
  config: GeneratedHarnessAppConfig
) {
  const routeGroups = await collectRouteGroups(rootDir, config);
  const bodyLines: string[] = [];

  for (const [groupKey, routes] of [...routeGroups.entries()].sort(([a], [b]) =>
    a.localeCompare(b)
  )) {
    bodyLines.push(`## ${headingFromSegment(groupKey)}`);
    bodyLines.push("");
    for (const routePath of routes) {
      bodyLines.push(`- ${formatMarkdownLink(routePath)}`);
    }
    bodyLines.push("");
  }

  return buildGeneratedDoc(
    `# ${config.label} Route Index`,
    [
      `This route index enumerates the current files under \`${config.routeRoot}\` so agents can orient quickly without scanning the whole package.`,
    ],
    bodyLines
  );
}

async function buildTestIndex(
  rootDir: string,
  config: GeneratedHarnessAppConfig,
  packageConfig: PackageConfig
) {
  const testGroups = await collectTestFiles(rootDir, config);
  const surfaces = await collectTestSurfaceRoots(rootDir, config, packageConfig);
  const documentedCommands = ["test"];
  if (packageConfig.scripts["test:e2e"]) {
    documentedCommands.push("test:e2e");
  }
  const bodyLines = ["## Package-level commands", ""];

  for (const script of documentedCommands) {
    bodyLines.push(`- \`${formatScriptCommand(packageConfig, script)}\``);
  }

  bodyLines.push("");
  bodyLines.push("## Detected test surfaces");
  bodyLines.push("");
  for (const surface of surfaces) {
    bodyLines.push(`- \`${surface}\``);
  }
  bodyLines.push("");

  for (const [groupKey, testFiles] of [...testGroups.entries()].sort(([a], [b]) =>
    a.localeCompare(b)
  )) {
    bodyLines.push(`## ${headingFromSegment(groupKey)}`);
    bodyLines.push("");
    for (const testFile of testFiles) {
      bodyLines.push(`- ${formatMarkdownLink(testFile)}`);
    }
    bodyLines.push("");
  }

  return buildGeneratedDoc(
    `# ${config.label} Test Index`,
    [
      "This index enumerates the current automated test files and ties them back to the package-level commands agents should start from.",
    ],
    bodyLines
  );
}

async function buildKeyFolderIndex(
  rootDir: string,
  config: GeneratedHarnessAppConfig
) {
  const bodyLines: string[] = [];

  for (const group of config.keyFolderGroups) {
    bodyLines.push(`## ${group.title}`);
    bodyLines.push("");

    for (const folder of group.folders) {
      const facts = await collectFolderFacts(rootDir, config, folder.path);
      if (!facts) {
        continue;
      }

      bodyLines.push(
        `- ${formatMarkdownLink(folder.path)} — ${folder.description} Currently ${facts.fileCount} file(s); key children: ${facts.childSummary}.`
      );
    }

    bodyLines.push("");
  }

  return buildGeneratedDoc(
    `# ${config.label} Key Folder Index`,
    [
      "This key-folder index highlights the main directories agents are likely to need for fast package orientation.",
    ],
    bodyLines
  );
}

async function buildValidationGuide(
  config: GeneratedHarnessAppConfig,
  packageConfig: PackageConfig
) {
  const bodyLines = [
    "Use this decision guide to answer “what should I run for this change?” based on the surface you touched.",
    "",
  ];

  for (const scenario of config.validationScenarios) {
    bodyLines.push(`## ${scenario.title}`);
    bodyLines.push("");
    bodyLines.push(`Touched surfaces: ${scenario.touchedPaths.map((entry) => `\`${entry}\``).join(", ")}`);
    bodyLines.push("");
    bodyLines.push("Run:");
    bodyLines.push("");

    for (const command of scenario.commands) {
      bodyLines.push(`- \`${formatValidationCommandForDoc(packageConfig, command)}\``);
    }

    bodyLines.push("");
    bodyLines.push(scenario.note);
    bodyLines.push("");
  }

  return buildGeneratedDoc(
    `# ${config.label} Validation Guide`,
    [],
    bodyLines
  );
}

async function buildValidationMap(
  config: GeneratedHarnessAppConfig,
  packageConfig: PackageConfig
) {
  return `${JSON.stringify(toGeneratedValidationMap(config, packageConfig), null, 2)}\n`;
}

export async function generateHarnessDocs(rootDir: string) {
  const docs = new Map<string, string>();

  for (const config of APP_CONFIGS) {
    const packageConfig = await readPackageConfig(rootDir, config.packageDir);
    docs.set(
      `${config.packageDir}/docs/agent/route-index.md`,
      await buildRouteIndex(rootDir, config)
    );
    docs.set(
      `${config.packageDir}/docs/agent/test-index.md`,
      await buildTestIndex(rootDir, config, packageConfig)
    );
    docs.set(
      `${config.packageDir}/docs/agent/key-folder-index.md`,
      await buildKeyFolderIndex(rootDir, config)
    );
    docs.set(
      `${config.packageDir}/docs/agent/validation-guide.md`,
      await buildValidationGuide(config, packageConfig)
    );
    docs.set(
      `${config.packageDir}/docs/agent/validation-map.json`,
      await buildValidationMap(config, packageConfig)
    );
  }

  return docs;
}

export async function writeGeneratedHarnessDocs(rootDir: string) {
  const docs = await generateHarnessDocs(rootDir);

  for (const [relativePath, contents] of docs) {
    const absolutePath = path.join(rootDir, relativePath);
    await mkdir(path.dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, contents);
  }

  return docs;
}

if (import.meta.main) {
  await writeGeneratedHarnessDocs(process.cwd());
}
