/**
 * Public catalogue projection (`public_catalog.v1`).
 *
 * The anonymous catalogue routes under `http/domains/core/routes/products.ts`
 * used to spread whole `product` / `productSku` documents to shoppers. This
 * module is the boundary projection they apply to every response, on a cache
 * hit as well as a miss.
 *
 * It is deliberately drop-only: field names are unchanged, and only the
 * operator-internal fields enumerated below are removed. Enrichment that the
 * queries add on top of the documents (`categoryName`, `colorName`, `skus`,
 * ...) is preserved, so the storefront's read set is untouched.
 *
 * Every key of `productSchema` and `productSkuSchema` must appear in exactly
 * one of the kept/dropped lists here; `publicCatalog.test.ts` enumerates the
 * schemas and fails when a new key arrives without a decision.
 */

export const PUBLIC_CATALOG_CONTRACT_VERSION = "public_catalog.v1" as const;

/** `product` keys the projection keeps. */
export const PUBLIC_CATALOG_PRODUCT_KEPT_FIELDS = [
  "attributes",
  "availability",
  "categoryId",
  "currency",
  "description",
  "isVisible",
  "name",
  "quantityAvailable",
  "slug",
  "storeId",
  "subcategoryId",
] as const;

/** `product` keys the projection drops. */
export const PUBLIC_CATALOG_PRODUCT_DROPPED_FIELDS = [
  "areProcessingFeesAbsorbed",
  "createdByUserId",
  // Roll-up of on-hand stock. The storefront never reads it from these routes;
  // it asks `POST /storefront/inventory/batch` when it needs counts.
  "inventoryCount",
  "organizationId",
  "posVisible",
] as const;

/** `productSku` keys the projection keeps. */
export const PUBLIC_CATALOG_SKU_KEPT_FIELDS = [
  "attributes",
  "color",
  "images",
  "isVisible",
  "length",
  "price",
  "productId",
  "productName",
  "quantityAvailable",
  "size",
  "sku",
  "storeId",
  "weight",
] as const;

/** `productSku` keys the projection drops. */
export const PUBLIC_CATALOG_SKU_DROPPED_FIELDS = [
  "barcode",
  "barcodeAutoGenerated",
  "inventoryCount",
  "netPrice",
  "pesewasMigratedAt",
  "posVisible",
  "unitCost",
] as const;

/**
 * Fields the availability adjustment attaches to a SKU at read time rather than
 * storing them, so they are not schema keys but still reach the wire.
 */
export const PUBLIC_CATALOG_SKU_DROPPED_DERIVED_FIELDS = [
  "durableQuantityAvailable",
  "reservedQuantity",
] as const;

const PRODUCT_DROPPED: readonly string[] = PUBLIC_CATALOG_PRODUCT_DROPPED_FIELDS;
const SKU_DROPPED: readonly string[] = [
  ...PUBLIC_CATALOG_SKU_DROPPED_FIELDS,
  ...PUBLIC_CATALOG_SKU_DROPPED_DERIVED_FIELDS,
];

type AnyRecord = Record<string, unknown>;

function isRecord(value: unknown): value is AnyRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function omitFields(value: AnyRecord, dropped: readonly string[]): AnyRecord {
  const projected: AnyRecord = {};
  for (const [key, entry] of Object.entries(value)) {
    if (dropped.includes(key)) continue;
    projected[key] = entry;
  }
  return projected;
}

/**
 * Projects one SKU, including the product document `productSku.retrieve`
 * attaches for the best-seller route.
 */
export function projectPublicCatalogSku<T>(sku: T): T {
  if (!isRecord(sku)) return sku;

  const projected = omitFields(sku, SKU_DROPPED);

  if (isRecord(projected.product)) {
    projected.product = projectPublicCatalogProduct(projected.product);
  }

  return projected as T;
}

/** Projects one product and any `skus` it carries. */
export function projectPublicCatalogProduct<T>(product: T): T {
  if (!isRecord(product)) return product;

  const projected = omitFields(product, PRODUCT_DROPPED);

  if (Array.isArray(projected.skus)) {
    projected.skus = projected.skus.map((sku) => projectPublicCatalogSku(sku));
  }

  return projected as T;
}

/** Projects the `GET /products` list. */
export function projectPublicCatalogProducts<T>(products: T): T {
  if (!Array.isArray(products)) return products;
  return products.map((product) =>
    projectPublicCatalogProduct(product),
  ) as unknown as T;
}

/** Projects the `GET /products/bestSellers` rows. */
export function projectPublicCatalogBestSellers<T>(items: T): T {
  if (!Array.isArray(items)) return items;

  return items.map((item) => {
    if (!isRecord(item)) return item;
    if (!isRecord(item.productSku)) return item;
    return { ...item, productSku: projectPublicCatalogSku(item.productSku) };
  }) as unknown as T;
}

function projectFeaturedCollection(collection: unknown): unknown {
  if (!isRecord(collection)) return collection;
  if (!Array.isArray(collection.products)) return collection;

  return {
    ...collection,
    products: collection.products.map((product) =>
      projectPublicCatalogProduct(product),
    ),
  };
}

/** Projects the `GET /products/featured` rows. */
export function projectPublicCatalogFeaturedItems<T>(items: T): T {
  if (!Array.isArray(items)) return items;

  return items.map((item) => {
    if (!isRecord(item)) return item;

    const projected: AnyRecord = { ...item };

    if (isRecord(projected.product)) {
      projected.product = projectPublicCatalogProduct(projected.product);
    }
    if (isRecord(projected.category)) {
      projected.category = projectFeaturedCollection(projected.category);
    }
    if (isRecord(projected.subcategory)) {
      projected.subcategory = projectFeaturedCollection(projected.subcategory);
    }

    return projected;
  }) as unknown as T;
}
