import { describe, expect, it } from "vitest";

import {
  productSchema,
  productSkuSchema,
} from "../schemas/inventory/product";
import {
  PUBLIC_CATALOG_PRODUCT_DROPPED_FIELDS,
  PUBLIC_CATALOG_PRODUCT_KEPT_FIELDS,
  PUBLIC_CATALOG_SKU_DROPPED_FIELDS,
  PUBLIC_CATALOG_SKU_KEPT_FIELDS,
  projectPublicCatalogBestSellers,
  projectPublicCatalogFeaturedItems,
  projectPublicCatalogProduct,
  projectPublicCatalogProducts,
  projectPublicCatalogSku,
} from "./publicCatalog";

const productDropped: string[] = [...PUBLIC_CATALOG_PRODUCT_DROPPED_FIELDS];
const productKept: string[] = [...PUBLIC_CATALOG_PRODUCT_KEPT_FIELDS];
const skuDropped: string[] = [...PUBLIC_CATALOG_SKU_DROPPED_FIELDS];
const skuKept: string[] = [...PUBLIC_CATALOG_SKU_KEPT_FIELDS];

function buildProductDocument() {
  return {
    _id: "product_1",
    _creationTime: 1,
    areProcessingFeesAbsorbed: true,
    attributes: { fibre: "human hair" },
    availability: "live",
    categoryId: "category_1",
    createdByUserId: "athenaUser_1",
    currency: "GHS",
    description: "A description",
    inventoryCount: 17,
    isVisible: true,
    name: "Lace front",
    organizationId: "organization_1",
    posVisible: false,
    quantityAvailable: 9,
    slug: "lace-front",
    storeId: "store_1",
    subcategoryId: "subcategory_1",
  };
}

function buildSkuDocument() {
  return {
    _id: "productSku_1",
    _creationTime: 1,
    attributes: { origin: "Ghana" },
    barcode: "000000000123",
    barcodeAutoGenerated: true,
    color: "color_1",
    durableQuantityAvailable: 6,
    images: ["https://example.invalid/a.jpg"],
    inventoryCount: 6,
    isVisible: true,
    length: 20,
    netPrice: 4500,
    pesewasMigratedAt: 1_700_000_000_000,
    posVisible: true,
    price: 5000,
    productId: "product_1",
    productName: "Lace front",
    quantityAvailable: 4,
    reservedQuantity: 2,
    size: "M",
    sku: "LF-20",
    storeId: "store_1",
    unitCost: 2500,
    weight: "200g",
  };
}

describe("public catalogue schema enumeration", () => {
  it("decides every product schema key", () => {
    const keys = Object.keys(productSchema.fields).sort();
    const decided = [...productKept, ...productDropped].sort();

    expect(decided).toEqual(keys);
  });

  it("decides every product SKU schema key", () => {
    const keys = Object.keys(productSkuSchema.fields).sort();
    const decided = [...skuKept, ...skuDropped].sort();

    expect(decided).toEqual(keys);
  });

  it("never keeps and drops the same key", () => {
    expect(productKept.filter((key) => productDropped.includes(key))).toEqual([]);
    expect(skuKept.filter((key) => skuDropped.includes(key))).toEqual([]);
  });
});

describe("public catalogue projection", () => {
  it("drops only the operator-internal product fields", () => {
    const projected = projectPublicCatalogProduct(buildProductDocument());

    for (const field of productDropped) {
      expect(projected).not.toHaveProperty(field);
    }
    for (const field of productKept) {
      expect(projected).toHaveProperty(field);
    }
    expect(projected._id).toBe("product_1");
  });

  it("drops only the operator-internal SKU fields, including the derived hold counters", () => {
    const projected = projectPublicCatalogSku(buildSkuDocument());

    for (const field of [
      ...skuDropped,
      "reservedQuantity",
      "durableQuantityAvailable",
    ]) {
      expect(projected).not.toHaveProperty(field);
    }
    for (const field of skuKept) {
      expect(projected).toHaveProperty(field);
    }
  });

  it("keeps the enrichment the catalogue queries attach", () => {
    const projected = projectPublicCatalogProduct({
      ...buildProductDocument(),
      categoryName: "Wigs",
      subcategoryName: "Lace fronts",
      categorySlug: "wigs",
      subcategorySlug: "lace-fronts",
      skus: [{ ...buildSkuDocument(), colorName: "Jet black" }],
    });

    expect(projected.categoryName).toBe("Wigs");
    expect(projected.subcategorySlug).toBe("lace-fronts");
    expect(projected.skus[0].colorName).toBe("Jet black");
    expect(projected.skus[0]).not.toHaveProperty("unitCost");
  });

  it("projects the list response", () => {
    const [projected] = projectPublicCatalogProducts([
      { ...buildProductDocument(), skus: [buildSkuDocument()] },
    ]);

    expect(projected).not.toHaveProperty("organizationId");
    expect(projected.skus[0]).not.toHaveProperty("barcode");
  });

  it("projects the product document nested in a best seller SKU", () => {
    const [projected] = projectPublicCatalogBestSellers([
      {
        _id: "bestSeller_1",
        rank: 1,
        productSku: {
          ...buildSkuDocument(),
          product: buildProductDocument(),
          category: { _id: "category_1", organizationId: "organization_1" },
        },
      },
    ]);

    expect(projected.productSku).not.toHaveProperty("netPrice");
    expect(projected.productSku.product).not.toHaveProperty("createdByUserId");
    expect(projected.productSku.product).not.toHaveProperty("inventoryCount");
    // Category documents are outside this projection's scope.
    expect(projected.productSku.category.organizationId).toBe("organization_1");
  });

  it("projects featured products and the collections' product lists", () => {
    const [projected] = projectPublicCatalogFeaturedItems([
      {
        _id: "featuredItem_1",
        product: { ...buildProductDocument(), skus: [buildSkuDocument()] },
        category: {
          _id: "category_1",
          products: [{ ...buildProductDocument(), skus: [buildSkuDocument()] }],
        },
        subcategory: {
          _id: "subcategory_1",
          products: [{ ...buildProductDocument(), skus: [null] }],
        },
      },
    ]);

    expect(projected.product).not.toHaveProperty("organizationId");
    expect(projected.product.skus[0]).not.toHaveProperty("unitCost");
    expect(projected.category.products[0]).not.toHaveProperty("posVisible");
    expect(projected.category.products[0].skus[0]).not.toHaveProperty(
      "barcodeAutoGenerated",
    );
    expect(projected.subcategory.products[0].skus[0]).toBeNull();
  });

  it("passes non-catalogue payloads through unchanged", () => {
    expect(projectPublicCatalogProducts(undefined)).toBeUndefined();
    expect(projectPublicCatalogBestSellers(undefined)).toBeUndefined();
    expect(projectPublicCatalogFeaturedItems(undefined)).toBeUndefined();
    expect(projectPublicCatalogProduct(null)).toBeNull();
  });
});
