/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as LayoutContactUsRouteImport } from './routes/_layout/contact-us'
import { Route as LayoutAccountRouteImport } from './routes/_layout/account'
import { Route as LayoutShopLayoutRouteImport } from './routes/_layout/_shopLayout'
import { Route as LayoutOrdersLayoutRouteImport } from './routes/_layout/_ordersLayout'
import { Route as ShopCheckoutIndexRouteImport } from './routes/shop/checkout/index'
import { Route as ShopBagIndexRouteImport } from './routes/shop/bag.index'
import { Route as LayoutRewardsIndexRouteImport } from './routes/_layout/rewards.index'
import { Route as ShopCheckoutPodConfirmationRouteImport } from './routes/shop/checkout/pod-confirmation'
import { Route as ShopCheckoutPendingRouteImport } from './routes/shop/checkout/pending'
import { Route as ShopCheckoutVerifyIndexRouteImport } from './routes/shop/checkout/verify.index'
import { Route as ShopCheckoutCompleteIndexRouteImport } from './routes/shop/checkout/complete.index'
import { Route as ShopCheckoutSessionIdSlugIndexRouteImport } from './routes/shop/checkout/$sessionIdSlug/index'
import { Route as LayoutShopSavedIndexRouteImport } from './routes/_layout/shop.saved.index'
import { Route as LayoutPoliciesTosIndexRouteImport } from './routes/_layout/policies/tos.index'
import { Route as LayoutPoliciesPrivacyIndexRouteImport } from './routes/_layout/policies/privacy.index'
import { Route as LayoutPoliciesDeliveryReturnsExchangesIndexRouteImport } from './routes/_layout/policies/delivery-returns-exchanges.index'
import { Route as ShopCheckoutSessionIdSlugIncompleteRouteImport } from './routes/shop/checkout/$sessionIdSlug/incomplete'
import { Route as ShopCheckoutSessionIdSlugCompleteRouteImport } from './routes/shop/checkout/$sessionIdSlug/complete'
import { Route as ShopCheckoutSessionIdSlugCanceledRouteImport } from './routes/shop/checkout/$sessionIdSlug/canceled'
import { Route as LayoutShopProductProductSlugRouteImport } from './routes/_layout/shop.product.$productSlug'
import { Route as LayoutShopLayoutShopCategorySlugIndexRouteImport } from './routes/_layout/_shopLayout/shop/$categorySlug/index'
import { Route as LayoutOrdersLayoutShopOrdersIndexRouteImport } from './routes/_layout/_ordersLayout/shop/orders/index'
import { Route as LayoutShopLayoutShopCategorySlugSubcategorySlugRouteImport } from './routes/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug'
import { Route as LayoutOrdersLayoutShopOrdersOrderIdIndexRouteImport } from './routes/_layout/_ordersLayout/shop/orders/$orderId/index'
import { Route as LayoutOrdersLayoutShopOrdersOrderIdReviewRouteImport } from './routes/_layout/_ordersLayout/shop/orders/$orderId/review'
import { Route as LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRouteImport } from './routes/_layout/_ordersLayout/shop/orders/$orderId/$orderItemId.review'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutContactUsRoute = LayoutContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAccountRoute = LayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShopLayoutRoute = LayoutShopLayoutRouteImport.update({
  id: '/_shopLayout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersLayoutRoute = LayoutOrdersLayoutRouteImport.update({
  id: '/_ordersLayout',
  getParentRoute: () => LayoutRoute,
} as any)
const ShopCheckoutIndexRoute = ShopCheckoutIndexRouteImport.update({
  id: '/shop/checkout/',
  path: '/shop/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopBagIndexRoute = ShopBagIndexRouteImport.update({
  id: '/shop/bag/',
  path: '/shop/bag/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRewardsIndexRoute = LayoutRewardsIndexRouteImport.update({
  id: '/rewards/',
  path: '/rewards/',
  getParentRoute: () => LayoutRoute,
} as any)
const ShopCheckoutPodConfirmationRoute =
  ShopCheckoutPodConfirmationRouteImport.update({
    id: '/shop/checkout/pod-confirmation',
    path: '/shop/checkout/pod-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopCheckoutPendingRoute = ShopCheckoutPendingRouteImport.update({
  id: '/shop/checkout/pending',
  path: '/shop/checkout/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutVerifyIndexRoute = ShopCheckoutVerifyIndexRouteImport.update({
  id: '/shop/checkout/verify/',
  path: '/shop/checkout/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCheckoutCompleteIndexRoute =
  ShopCheckoutCompleteIndexRouteImport.update({
    id: '/shop/checkout/complete/',
    path: '/shop/checkout/complete/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopCheckoutSessionIdSlugIndexRoute =
  ShopCheckoutSessionIdSlugIndexRouteImport.update({
    id: '/shop/checkout/$sessionIdSlug/',
    path: '/shop/checkout/$sessionIdSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutShopSavedIndexRoute = LayoutShopSavedIndexRouteImport.update({
  id: '/shop/saved/',
  path: '/shop/saved/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPoliciesTosIndexRoute = LayoutPoliciesTosIndexRouteImport.update({
  id: '/policies/tos/',
  path: '/policies/tos/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPoliciesPrivacyIndexRoute =
  LayoutPoliciesPrivacyIndexRouteImport.update({
    id: '/policies/privacy/',
    path: '/policies/privacy/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPoliciesDeliveryReturnsExchangesIndexRoute =
  LayoutPoliciesDeliveryReturnsExchangesIndexRouteImport.update({
    id: '/policies/delivery-returns-exchanges/',
    path: '/policies/delivery-returns-exchanges/',
    getParentRoute: () => LayoutRoute,
  } as any)
const ShopCheckoutSessionIdSlugIncompleteRoute =
  ShopCheckoutSessionIdSlugIncompleteRouteImport.update({
    id: '/shop/checkout/$sessionIdSlug/incomplete',
    path: '/shop/checkout/$sessionIdSlug/incomplete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopCheckoutSessionIdSlugCompleteRoute =
  ShopCheckoutSessionIdSlugCompleteRouteImport.update({
    id: '/shop/checkout/$sessionIdSlug/complete',
    path: '/shop/checkout/$sessionIdSlug/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShopCheckoutSessionIdSlugCanceledRoute =
  ShopCheckoutSessionIdSlugCanceledRouteImport.update({
    id: '/shop/checkout/$sessionIdSlug/canceled',
    path: '/shop/checkout/$sessionIdSlug/canceled',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutShopProductProductSlugRoute =
  LayoutShopProductProductSlugRouteImport.update({
    id: '/shop/product/$productSlug',
    path: '/shop/product/$productSlug',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutShopLayoutShopCategorySlugIndexRoute =
  LayoutShopLayoutShopCategorySlugIndexRouteImport.update({
    id: '/shop/$categorySlug/',
    path: '/shop/$categorySlug/',
    getParentRoute: () => LayoutShopLayoutRoute,
  } as any)
const LayoutOrdersLayoutShopOrdersIndexRoute =
  LayoutOrdersLayoutShopOrdersIndexRouteImport.update({
    id: '/shop/orders/',
    path: '/shop/orders/',
    getParentRoute: () => LayoutOrdersLayoutRoute,
  } as any)
const LayoutShopLayoutShopCategorySlugSubcategorySlugRoute =
  LayoutShopLayoutShopCategorySlugSubcategorySlugRouteImport.update({
    id: '/shop/$categorySlug/$subcategorySlug',
    path: '/shop/$categorySlug/$subcategorySlug',
    getParentRoute: () => LayoutShopLayoutRoute,
  } as any)
const LayoutOrdersLayoutShopOrdersOrderIdIndexRoute =
  LayoutOrdersLayoutShopOrdersOrderIdIndexRouteImport.update({
    id: '/shop/orders/$orderId/',
    path: '/shop/orders/$orderId/',
    getParentRoute: () => LayoutOrdersLayoutRoute,
  } as any)
const LayoutOrdersLayoutShopOrdersOrderIdReviewRoute =
  LayoutOrdersLayoutShopOrdersOrderIdReviewRouteImport.update({
    id: '/shop/orders/$orderId/review',
    path: '/shop/orders/$orderId/review',
    getParentRoute: () => LayoutOrdersLayoutRoute,
  } as any)
const LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRoute =
  LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRouteImport.update({
    id: '/shop/orders/$orderId/$orderItemId/review',
    path: '/shop/orders/$orderId/$orderItemId/review',
    getParentRoute: () => LayoutOrdersLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof LayoutAccountRoute
  '/contact-us': typeof LayoutContactUsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/shop/checkout/pending': typeof ShopCheckoutPendingRoute
  '/shop/checkout/pod-confirmation': typeof ShopCheckoutPodConfirmationRoute
  '/rewards/': typeof LayoutRewardsIndexRoute
  '/shop/bag/': typeof ShopBagIndexRoute
  '/shop/checkout/': typeof ShopCheckoutIndexRoute
  '/shop/product/$productSlug': typeof LayoutShopProductProductSlugRoute
  '/shop/checkout/$sessionIdSlug/canceled': typeof ShopCheckoutSessionIdSlugCanceledRoute
  '/shop/checkout/$sessionIdSlug/complete': typeof ShopCheckoutSessionIdSlugCompleteRoute
  '/shop/checkout/$sessionIdSlug/incomplete': typeof ShopCheckoutSessionIdSlugIncompleteRoute
  '/policies/delivery-returns-exchanges/': typeof LayoutPoliciesDeliveryReturnsExchangesIndexRoute
  '/policies/privacy/': typeof LayoutPoliciesPrivacyIndexRoute
  '/policies/tos/': typeof LayoutPoliciesTosIndexRoute
  '/shop/saved/': typeof LayoutShopSavedIndexRoute
  '/shop/checkout/$sessionIdSlug/': typeof ShopCheckoutSessionIdSlugIndexRoute
  '/shop/checkout/complete/': typeof ShopCheckoutCompleteIndexRoute
  '/shop/checkout/verify/': typeof ShopCheckoutVerifyIndexRoute
  '/shop/$categorySlug/$subcategorySlug': typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRoute
  '/shop/orders/': typeof LayoutOrdersLayoutShopOrdersIndexRoute
  '/shop/$categorySlug/': typeof LayoutShopLayoutShopCategorySlugIndexRoute
  '/shop/orders/$orderId/review': typeof LayoutOrdersLayoutShopOrdersOrderIdReviewRoute
  '/shop/orders/$orderId/': typeof LayoutOrdersLayoutShopOrdersOrderIdIndexRoute
  '/shop/orders/$orderId/$orderItemId/review': typeof LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof LayoutAccountRoute
  '/contact-us': typeof LayoutContactUsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/shop/checkout/pending': typeof ShopCheckoutPendingRoute
  '/shop/checkout/pod-confirmation': typeof ShopCheckoutPodConfirmationRoute
  '/rewards': typeof LayoutRewardsIndexRoute
  '/shop/bag': typeof ShopBagIndexRoute
  '/shop/checkout': typeof ShopCheckoutIndexRoute
  '/shop/product/$productSlug': typeof LayoutShopProductProductSlugRoute
  '/shop/checkout/$sessionIdSlug/canceled': typeof ShopCheckoutSessionIdSlugCanceledRoute
  '/shop/checkout/$sessionIdSlug/complete': typeof ShopCheckoutSessionIdSlugCompleteRoute
  '/shop/checkout/$sessionIdSlug/incomplete': typeof ShopCheckoutSessionIdSlugIncompleteRoute
  '/policies/delivery-returns-exchanges': typeof LayoutPoliciesDeliveryReturnsExchangesIndexRoute
  '/policies/privacy': typeof LayoutPoliciesPrivacyIndexRoute
  '/policies/tos': typeof LayoutPoliciesTosIndexRoute
  '/shop/saved': typeof LayoutShopSavedIndexRoute
  '/shop/checkout/$sessionIdSlug': typeof ShopCheckoutSessionIdSlugIndexRoute
  '/shop/checkout/complete': typeof ShopCheckoutCompleteIndexRoute
  '/shop/checkout/verify': typeof ShopCheckoutVerifyIndexRoute
  '/shop/$categorySlug/$subcategorySlug': typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRoute
  '/shop/orders': typeof LayoutOrdersLayoutShopOrdersIndexRoute
  '/shop/$categorySlug': typeof LayoutShopLayoutShopCategorySlugIndexRoute
  '/shop/orders/$orderId/review': typeof LayoutOrdersLayoutShopOrdersOrderIdReviewRoute
  '/shop/orders/$orderId': typeof LayoutOrdersLayoutShopOrdersOrderIdIndexRoute
  '/shop/orders/$orderId/$orderItemId/review': typeof LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/_ordersLayout': typeof LayoutOrdersLayoutRouteWithChildren
  '/_layout/_shopLayout': typeof LayoutShopLayoutRouteWithChildren
  '/_layout/account': typeof LayoutAccountRoute
  '/_layout/contact-us': typeof LayoutContactUsRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/shop/checkout/pending': typeof ShopCheckoutPendingRoute
  '/shop/checkout/pod-confirmation': typeof ShopCheckoutPodConfirmationRoute
  '/_layout/rewards/': typeof LayoutRewardsIndexRoute
  '/shop/bag/': typeof ShopBagIndexRoute
  '/shop/checkout/': typeof ShopCheckoutIndexRoute
  '/_layout/shop/product/$productSlug': typeof LayoutShopProductProductSlugRoute
  '/shop/checkout/$sessionIdSlug/canceled': typeof ShopCheckoutSessionIdSlugCanceledRoute
  '/shop/checkout/$sessionIdSlug/complete': typeof ShopCheckoutSessionIdSlugCompleteRoute
  '/shop/checkout/$sessionIdSlug/incomplete': typeof ShopCheckoutSessionIdSlugIncompleteRoute
  '/_layout/policies/delivery-returns-exchanges/': typeof LayoutPoliciesDeliveryReturnsExchangesIndexRoute
  '/_layout/policies/privacy/': typeof LayoutPoliciesPrivacyIndexRoute
  '/_layout/policies/tos/': typeof LayoutPoliciesTosIndexRoute
  '/_layout/shop/saved/': typeof LayoutShopSavedIndexRoute
  '/shop/checkout/$sessionIdSlug/': typeof ShopCheckoutSessionIdSlugIndexRoute
  '/shop/checkout/complete/': typeof ShopCheckoutCompleteIndexRoute
  '/shop/checkout/verify/': typeof ShopCheckoutVerifyIndexRoute
  '/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug': typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRoute
  '/_layout/_ordersLayout/shop/orders/': typeof LayoutOrdersLayoutShopOrdersIndexRoute
  '/_layout/_shopLayout/shop/$categorySlug/': typeof LayoutShopLayoutShopCategorySlugIndexRoute
  '/_layout/_ordersLayout/shop/orders/$orderId/review': typeof LayoutOrdersLayoutShopOrdersOrderIdReviewRoute
  '/_layout/_ordersLayout/shop/orders/$orderId/': typeof LayoutOrdersLayoutShopOrdersOrderIdIndexRoute
  '/_layout/_ordersLayout/shop/orders/$orderId/$orderItemId/review': typeof LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/contact-us'
    | '/auth/verify'
    | '/shop/checkout/pending'
    | '/shop/checkout/pod-confirmation'
    | '/rewards/'
    | '/shop/bag/'
    | '/shop/checkout/'
    | '/shop/product/$productSlug'
    | '/shop/checkout/$sessionIdSlug/canceled'
    | '/shop/checkout/$sessionIdSlug/complete'
    | '/shop/checkout/$sessionIdSlug/incomplete'
    | '/policies/delivery-returns-exchanges/'
    | '/policies/privacy/'
    | '/policies/tos/'
    | '/shop/saved/'
    | '/shop/checkout/$sessionIdSlug/'
    | '/shop/checkout/complete/'
    | '/shop/checkout/verify/'
    | '/shop/$categorySlug/$subcategorySlug'
    | '/shop/orders/'
    | '/shop/$categorySlug/'
    | '/shop/orders/$orderId/review'
    | '/shop/orders/$orderId/'
    | '/shop/orders/$orderId/$orderItemId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/account'
    | '/contact-us'
    | '/auth/verify'
    | '/shop/checkout/pending'
    | '/shop/checkout/pod-confirmation'
    | '/rewards'
    | '/shop/bag'
    | '/shop/checkout'
    | '/shop/product/$productSlug'
    | '/shop/checkout/$sessionIdSlug/canceled'
    | '/shop/checkout/$sessionIdSlug/complete'
    | '/shop/checkout/$sessionIdSlug/incomplete'
    | '/policies/delivery-returns-exchanges'
    | '/policies/privacy'
    | '/policies/tos'
    | '/shop/saved'
    | '/shop/checkout/$sessionIdSlug'
    | '/shop/checkout/complete'
    | '/shop/checkout/verify'
    | '/shop/$categorySlug/$subcategorySlug'
    | '/shop/orders'
    | '/shop/$categorySlug'
    | '/shop/orders/$orderId/review'
    | '/shop/orders/$orderId'
    | '/shop/orders/$orderId/$orderItemId/review'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/_ordersLayout'
    | '/_layout/_shopLayout'
    | '/_layout/account'
    | '/_layout/contact-us'
    | '/auth/verify'
    | '/shop/checkout/pending'
    | '/shop/checkout/pod-confirmation'
    | '/_layout/rewards/'
    | '/shop/bag/'
    | '/shop/checkout/'
    | '/_layout/shop/product/$productSlug'
    | '/shop/checkout/$sessionIdSlug/canceled'
    | '/shop/checkout/$sessionIdSlug/complete'
    | '/shop/checkout/$sessionIdSlug/incomplete'
    | '/_layout/policies/delivery-returns-exchanges/'
    | '/_layout/policies/privacy/'
    | '/_layout/policies/tos/'
    | '/_layout/shop/saved/'
    | '/shop/checkout/$sessionIdSlug/'
    | '/shop/checkout/complete/'
    | '/shop/checkout/verify/'
    | '/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug'
    | '/_layout/_ordersLayout/shop/orders/'
    | '/_layout/_shopLayout/shop/$categorySlug/'
    | '/_layout/_ordersLayout/shop/orders/$orderId/review'
    | '/_layout/_ordersLayout/shop/orders/$orderId/'
    | '/_layout/_ordersLayout/shop/orders/$orderId/$orderItemId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ShopCheckoutPendingRoute: typeof ShopCheckoutPendingRoute
  ShopCheckoutPodConfirmationRoute: typeof ShopCheckoutPodConfirmationRoute
  ShopBagIndexRoute: typeof ShopBagIndexRoute
  ShopCheckoutIndexRoute: typeof ShopCheckoutIndexRoute
  ShopCheckoutSessionIdSlugCanceledRoute: typeof ShopCheckoutSessionIdSlugCanceledRoute
  ShopCheckoutSessionIdSlugCompleteRoute: typeof ShopCheckoutSessionIdSlugCompleteRoute
  ShopCheckoutSessionIdSlugIncompleteRoute: typeof ShopCheckoutSessionIdSlugIncompleteRoute
  ShopCheckoutSessionIdSlugIndexRoute: typeof ShopCheckoutSessionIdSlugIndexRoute
  ShopCheckoutCompleteIndexRoute: typeof ShopCheckoutCompleteIndexRoute
  ShopCheckoutVerifyIndexRoute: typeof ShopCheckoutVerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/contact-us': {
      id: '/_layout/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof LayoutContactUsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/account': {
      id: '/_layout/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_shopLayout': {
      id: '/_layout/_shopLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutShopLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_ordersLayout': {
      id: '/_layout/_ordersLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutOrdersLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/shop/checkout/': {
      id: '/shop/checkout/'
      path: '/shop/checkout'
      fullPath: '/shop/checkout/'
      preLoaderRoute: typeof ShopCheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/bag/': {
      id: '/shop/bag/'
      path: '/shop/bag'
      fullPath: '/shop/bag/'
      preLoaderRoute: typeof ShopBagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/rewards/': {
      id: '/_layout/rewards/'
      path: '/rewards'
      fullPath: '/rewards/'
      preLoaderRoute: typeof LayoutRewardsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/shop/checkout/pod-confirmation': {
      id: '/shop/checkout/pod-confirmation'
      path: '/shop/checkout/pod-confirmation'
      fullPath: '/shop/checkout/pod-confirmation'
      preLoaderRoute: typeof ShopCheckoutPodConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/pending': {
      id: '/shop/checkout/pending'
      path: '/shop/checkout/pending'
      fullPath: '/shop/checkout/pending'
      preLoaderRoute: typeof ShopCheckoutPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/verify/': {
      id: '/shop/checkout/verify/'
      path: '/shop/checkout/verify'
      fullPath: '/shop/checkout/verify/'
      preLoaderRoute: typeof ShopCheckoutVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/complete/': {
      id: '/shop/checkout/complete/'
      path: '/shop/checkout/complete'
      fullPath: '/shop/checkout/complete/'
      preLoaderRoute: typeof ShopCheckoutCompleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/$sessionIdSlug/': {
      id: '/shop/checkout/$sessionIdSlug/'
      path: '/shop/checkout/$sessionIdSlug'
      fullPath: '/shop/checkout/$sessionIdSlug/'
      preLoaderRoute: typeof ShopCheckoutSessionIdSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/shop/saved/': {
      id: '/_layout/shop/saved/'
      path: '/shop/saved'
      fullPath: '/shop/saved/'
      preLoaderRoute: typeof LayoutShopSavedIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies/tos/': {
      id: '/_layout/policies/tos/'
      path: '/policies/tos'
      fullPath: '/policies/tos/'
      preLoaderRoute: typeof LayoutPoliciesTosIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies/privacy/': {
      id: '/_layout/policies/privacy/'
      path: '/policies/privacy'
      fullPath: '/policies/privacy/'
      preLoaderRoute: typeof LayoutPoliciesPrivacyIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies/delivery-returns-exchanges/': {
      id: '/_layout/policies/delivery-returns-exchanges/'
      path: '/policies/delivery-returns-exchanges'
      fullPath: '/policies/delivery-returns-exchanges/'
      preLoaderRoute: typeof LayoutPoliciesDeliveryReturnsExchangesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/shop/checkout/$sessionIdSlug/incomplete': {
      id: '/shop/checkout/$sessionIdSlug/incomplete'
      path: '/shop/checkout/$sessionIdSlug/incomplete'
      fullPath: '/shop/checkout/$sessionIdSlug/incomplete'
      preLoaderRoute: typeof ShopCheckoutSessionIdSlugIncompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/$sessionIdSlug/complete': {
      id: '/shop/checkout/$sessionIdSlug/complete'
      path: '/shop/checkout/$sessionIdSlug/complete'
      fullPath: '/shop/checkout/$sessionIdSlug/complete'
      preLoaderRoute: typeof ShopCheckoutSessionIdSlugCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/checkout/$sessionIdSlug/canceled': {
      id: '/shop/checkout/$sessionIdSlug/canceled'
      path: '/shop/checkout/$sessionIdSlug/canceled'
      fullPath: '/shop/checkout/$sessionIdSlug/canceled'
      preLoaderRoute: typeof ShopCheckoutSessionIdSlugCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/shop/product/$productSlug': {
      id: '/_layout/shop/product/$productSlug'
      path: '/shop/product/$productSlug'
      fullPath: '/shop/product/$productSlug'
      preLoaderRoute: typeof LayoutShopProductProductSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_shopLayout/shop/$categorySlug/': {
      id: '/_layout/_shopLayout/shop/$categorySlug/'
      path: '/shop/$categorySlug'
      fullPath: '/shop/$categorySlug/'
      preLoaderRoute: typeof LayoutShopLayoutShopCategorySlugIndexRouteImport
      parentRoute: typeof LayoutShopLayoutRoute
    }
    '/_layout/_ordersLayout/shop/orders/': {
      id: '/_layout/_ordersLayout/shop/orders/'
      path: '/shop/orders'
      fullPath: '/shop/orders/'
      preLoaderRoute: typeof LayoutOrdersLayoutShopOrdersIndexRouteImport
      parentRoute: typeof LayoutOrdersLayoutRoute
    }
    '/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug': {
      id: '/_layout/_shopLayout/shop/$categorySlug/$subcategorySlug'
      path: '/shop/$categorySlug/$subcategorySlug'
      fullPath: '/shop/$categorySlug/$subcategorySlug'
      preLoaderRoute: typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRouteImport
      parentRoute: typeof LayoutShopLayoutRoute
    }
    '/_layout/_ordersLayout/shop/orders/$orderId/': {
      id: '/_layout/_ordersLayout/shop/orders/$orderId/'
      path: '/shop/orders/$orderId'
      fullPath: '/shop/orders/$orderId/'
      preLoaderRoute: typeof LayoutOrdersLayoutShopOrdersOrderIdIndexRouteImport
      parentRoute: typeof LayoutOrdersLayoutRoute
    }
    '/_layout/_ordersLayout/shop/orders/$orderId/review': {
      id: '/_layout/_ordersLayout/shop/orders/$orderId/review'
      path: '/shop/orders/$orderId/review'
      fullPath: '/shop/orders/$orderId/review'
      preLoaderRoute: typeof LayoutOrdersLayoutShopOrdersOrderIdReviewRouteImport
      parentRoute: typeof LayoutOrdersLayoutRoute
    }
    '/_layout/_ordersLayout/shop/orders/$orderId/$orderItemId/review': {
      id: '/_layout/_ordersLayout/shop/orders/$orderId/$orderItemId/review'
      path: '/shop/orders/$orderId/$orderItemId/review'
      fullPath: '/shop/orders/$orderId/$orderItemId/review'
      preLoaderRoute: typeof LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRouteImport
      parentRoute: typeof LayoutOrdersLayoutRoute
    }
  }
}

interface LayoutOrdersLayoutRouteChildren {
  LayoutOrdersLayoutShopOrdersIndexRoute: typeof LayoutOrdersLayoutShopOrdersIndexRoute
  LayoutOrdersLayoutShopOrdersOrderIdReviewRoute: typeof LayoutOrdersLayoutShopOrdersOrderIdReviewRoute
  LayoutOrdersLayoutShopOrdersOrderIdIndexRoute: typeof LayoutOrdersLayoutShopOrdersOrderIdIndexRoute
  LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRoute: typeof LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRoute
}

const LayoutOrdersLayoutRouteChildren: LayoutOrdersLayoutRouteChildren = {
  LayoutOrdersLayoutShopOrdersIndexRoute:
    LayoutOrdersLayoutShopOrdersIndexRoute,
  LayoutOrdersLayoutShopOrdersOrderIdReviewRoute:
    LayoutOrdersLayoutShopOrdersOrderIdReviewRoute,
  LayoutOrdersLayoutShopOrdersOrderIdIndexRoute:
    LayoutOrdersLayoutShopOrdersOrderIdIndexRoute,
  LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRoute:
    LayoutOrdersLayoutShopOrdersOrderIdOrderItemIdReviewRoute,
}

const LayoutOrdersLayoutRouteWithChildren =
  LayoutOrdersLayoutRoute._addFileChildren(LayoutOrdersLayoutRouteChildren)

interface LayoutShopLayoutRouteChildren {
  LayoutShopLayoutShopCategorySlugSubcategorySlugRoute: typeof LayoutShopLayoutShopCategorySlugSubcategorySlugRoute
  LayoutShopLayoutShopCategorySlugIndexRoute: typeof LayoutShopLayoutShopCategorySlugIndexRoute
}

const LayoutShopLayoutRouteChildren: LayoutShopLayoutRouteChildren = {
  LayoutShopLayoutShopCategorySlugSubcategorySlugRoute:
    LayoutShopLayoutShopCategorySlugSubcategorySlugRoute,
  LayoutShopLayoutShopCategorySlugIndexRoute:
    LayoutShopLayoutShopCategorySlugIndexRoute,
}

const LayoutShopLayoutRouteWithChildren =
  LayoutShopLayoutRoute._addFileChildren(LayoutShopLayoutRouteChildren)

interface LayoutRouteChildren {
  LayoutOrdersLayoutRoute: typeof LayoutOrdersLayoutRouteWithChildren
  LayoutShopLayoutRoute: typeof LayoutShopLayoutRouteWithChildren
  LayoutAccountRoute: typeof LayoutAccountRoute
  LayoutContactUsRoute: typeof LayoutContactUsRoute
  LayoutRewardsIndexRoute: typeof LayoutRewardsIndexRoute
  LayoutShopProductProductSlugRoute: typeof LayoutShopProductProductSlugRoute
  LayoutPoliciesDeliveryReturnsExchangesIndexRoute: typeof LayoutPoliciesDeliveryReturnsExchangesIndexRoute
  LayoutPoliciesPrivacyIndexRoute: typeof LayoutPoliciesPrivacyIndexRoute
  LayoutPoliciesTosIndexRoute: typeof LayoutPoliciesTosIndexRoute
  LayoutShopSavedIndexRoute: typeof LayoutShopSavedIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutOrdersLayoutRoute: LayoutOrdersLayoutRouteWithChildren,
  LayoutShopLayoutRoute: LayoutShopLayoutRouteWithChildren,
  LayoutAccountRoute: LayoutAccountRoute,
  LayoutContactUsRoute: LayoutContactUsRoute,
  LayoutRewardsIndexRoute: LayoutRewardsIndexRoute,
  LayoutShopProductProductSlugRoute: LayoutShopProductProductSlugRoute,
  LayoutPoliciesDeliveryReturnsExchangesIndexRoute:
    LayoutPoliciesDeliveryReturnsExchangesIndexRoute,
  LayoutPoliciesPrivacyIndexRoute: LayoutPoliciesPrivacyIndexRoute,
  LayoutPoliciesTosIndexRoute: LayoutPoliciesTosIndexRoute,
  LayoutShopSavedIndexRoute: LayoutShopSavedIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ShopCheckoutPendingRoute: ShopCheckoutPendingRoute,
  ShopCheckoutPodConfirmationRoute: ShopCheckoutPodConfirmationRoute,
  ShopBagIndexRoute: ShopBagIndexRoute,
  ShopCheckoutIndexRoute: ShopCheckoutIndexRoute,
  ShopCheckoutSessionIdSlugCanceledRoute:
    ShopCheckoutSessionIdSlugCanceledRoute,
  ShopCheckoutSessionIdSlugCompleteRoute:
    ShopCheckoutSessionIdSlugCompleteRoute,
  ShopCheckoutSessionIdSlugIncompleteRoute:
    ShopCheckoutSessionIdSlugIncompleteRoute,
  ShopCheckoutSessionIdSlugIndexRoute: ShopCheckoutSessionIdSlugIndexRoute,
  ShopCheckoutCompleteIndexRoute: ShopCheckoutCompleteIndexRoute,
  ShopCheckoutVerifyIndexRoute: ShopCheckoutVerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
