/**
 * Frozen contract for the rebuilt reports layer (`convex/reports/`).
 *
 * Both the Convex backend and the React frontend import metric names, statuses,
 * and result shapes from this module ONLY. Divergence between what the backend
 * materializes and what the UI reads is a compile error, not a blank dashboard.
 *
 * Design: docs/solutions/architecture/athena-reporting-read-optimized-redesign-2026-07-28.md
 * Plan:   docs/solutions/architecture/athena-reporting-read-optimized-implementation-plan-2026-07-28.md
 *
 * FROZEN after Wave 0. Slices escalate contract changes; they do not edit this file.
 */

/**
 * Semantic version of what `foldDay` computes from a day's facts.
 *
 * Version 2 normalizes each fact's currency code before comparing it against
 * the day's currency, so a day whose facts spell the same currency differently
 * (e.g. `ghs` vs `GHS`) is no longer flagged `mixedCurrency`. That flag feeds
 * weekly `completeness`, and an incorrect one makes the weekly surface withhold
 * every total — the reason the bump is not cosmetic.
 *
 * A bump refolds NOTHING on its own. `reportDay` rows keep whatever
 * `foldVersion` they were written with, and no read path compares the two.
 * To make a bump take effect on already-folded days, run
 * `reports/foldVersionRepair.markStaleFoldVersionDays` per store: it marks the
 * stale rows `fold_version_bump` dirty and the sweeper — the single fold
 * authority — refolds them. `countStaleFoldVersionDays` reports whether a
 * store still needs the repair.
 *
 * Version 3 certifies fold provenance: every fold stamps the same
 * `certifiedFoldRevision` on the written `reportDay` AND every `reportSkuDay`
 * row it replaces (see `foldAndReplaceDay` in convex/reports/sweeper.ts). The
 * bump exists so the per-store repair sees every pre-revision day as stale —
 * clean days never refold on their own, so without it existing history would
 * stay uncertified forever.
 */
export const REPORTS_FOLD_VERSION = 3 as const;
/**
 * Version 2 adds the source-derived allocation dimensions carried by payment
 * facts. Replays hash with the version already stored on a fact.
 */
export const REPORTS_FINGERPRINT_VERSION = 2 as const;

export const REPORT_SOURCE_DOMAINS = [
  "pos",
  "storefront",
  "service",
  "payments",
  "inventory",
  "daily_close",
] as const;
export type ReportSourceDomain = (typeof REPORT_SOURCE_DOMAINS)[number];

export const REPORT_FACT_KINDS = [
  "sale",
  "refund",
  "void",
  "correction",
  "return",
  "payment",
  "payment_refund",
  "close_snapshot",
  "inventory_issue",
  "procurement_receipt",
] as const;
export type ReportFactKind = (typeof REPORT_FACT_KINDS)[number];

export const REPORT_DAY_STATUSES = [
  "open",
  "provisional",
  "reconciled",
  "amended",
] as const;
export type ReportDayStatus = (typeof REPORT_DAY_STATUSES)[number];

/**
 * Authoritative definition of "Today in progress" in reporting.
 *
 * Reporting follows the materialized day lifecycle, not a browser or server
 * clock: the current operating day remains `open` until rollover advances it.
 */
export function isReportingTodayInProgress(
  status: ReportDayStatus | null | undefined,
): boolean {
  return status === "open";
}

/**
 * Day-level metrics. One FIELD per metric — never one row per metric.
 * `grossProfitMinor` is null when any revenue lacks a cost basis; the
 * uncovered portion is reported honestly in `uncostedRevenueMinor`.
 */
export type ReportDayMetrics = {
  grossSalesMinor: number;
  netSalesMinor: number;
  refundsMinor: number;
  unitsSold: number;
  unitsReturned: number;
  uncostedRevenueMinor: number;
  grossProfitMinor: number | null;
  paymentsCollectedMinor: number;
  paymentsRefundedMinor: number;
  paymentAllocatedMinor: number;
};

export const REPORT_DAY_METRIC_KEYS = [
  "grossSalesMinor",
  "netSalesMinor",
  "refundsMinor",
  "unitsSold",
  "unitsReturned",
  "uncostedRevenueMinor",
  "grossProfitMinor",
  "paymentsCollectedMinor",
  "paymentsRefundedMinor",
  "paymentAllocatedMinor",
] as const satisfies readonly (keyof ReportDayMetrics)[];

/** SKU-day metrics — the subset of day metrics that attribute to a SKU. */
export type ReportSkuDayMetrics = {
  unitsSold: number;
  unitsReturned: number;
  grossSalesMinor: number;
  netSalesMinor: number;
  refundsMinor: number;
  uncostedRevenueMinor: number;
  grossProfitMinor: number | null;
};

export const REPORT_SKU_DAY_METRIC_KEYS = [
  "unitsSold",
  "unitsReturned",
  "grossSalesMinor",
  "netSalesMinor",
  "refundsMinor",
  "uncostedRevenueMinor",
  "grossProfitMinor",
] as const satisfies readonly (keyof ReportSkuDayMetrics)[];

export type ReportDayFlags = {
  mixedCurrency: boolean;
  hasUncostedRevenue: boolean;
  quarantinedFactCount: number;
};

/**
 * Settlement is a payment-only view. It never restates recognised sales and
 * contains no tender-method identity.
 */
export type ReportPaymentPosture = {
  collectedMinor: number;
  refundedMinor: number;
  allocatedMinor: number;
  unsettledMinor: number | null;
  allocationCoverage: "complete" | "unknown";
  allocationOmittedMinor: number;
  hasInvalidAllocation: boolean;
};

/**
 * The explicit metric fields materialized on each weekly projection.
 *
 * `paymentAllocationOmittedMinor` and `paymentHasInvalidAllocation` are
 * optional only while weekly documents written before they landed are
 * refreshed. Read them through `normalizeWeekMetrics` so a legacy row never
 * presents an omitted total of zero as source-proven.
 */
export type ReportWeekMetrics = ReportDayMetrics & {
  paymentUnsettledMinor: number | null;
  paymentAllocationCoverage: "complete" | "unknown";
  paymentAllocationOmittedMinor?: number;
  paymentHasInvalidAllocation?: boolean;
};

/**
 * Presentation-ready weekly values. Reports queries own these aliases and
 * net-unit calculation so clients only render a reporting conclusion.
 */
export type ReportWeekSummary = {
  grossSalesMinor: number;
  merchandiseMarginMinor: number | null;
  netSalesMinor: number;
  netUnits: number;
  paymentAllocatedMinor: number;
  paymentAllocationCoverage: "complete" | "unknown";
  paymentUnsettledMinor: number | null;
  paymentsCollectedMinor: number;
  paymentsRefundedMinor: number;
  refundsMinor: number;
  unitsReturned: number;
  unitsSold: number;
};

export const REPORT_WEEK_METRIC_KEYS = [
  ...REPORT_DAY_METRIC_KEYS,
  "paymentUnsettledMinor",
  "paymentAllocationCoverage",
] as const satisfies readonly (keyof ReportWeekMetrics)[];

/** Weekly payment posture fields still rolling out as optional-then-required. */
export const REPORT_WEEK_ROLLOUT_METRIC_KEYS = [
  "paymentAllocationOmittedMinor",
  "paymentHasInvalidAllocation",
] as const satisfies readonly (keyof ReportWeekMetrics)[];

/**
 * Fail-closed normalization for the rolling-out payment fields: an absent
 * omitted total is unknown coverage, not a proven zero.
 */
export function normalizeWeekMetrics(metrics: ReportWeekMetrics): Required<
  Pick<
    ReportWeekMetrics,
    "paymentAllocationOmittedMinor" | "paymentHasInvalidAllocation"
  >
> &
  ReportWeekMetrics {
  return {
    ...metrics,
    paymentAllocationOmittedMinor: metrics.paymentAllocationOmittedMinor ?? 0,
    paymentHasInvalidAllocation: metrics.paymentHasInvalidAllocation ?? false,
    paymentAllocationCoverage:
      metrics.paymentAllocationOmittedMinor === undefined
        ? metrics.paymentAllocationCoverage
        : metrics.paymentAllocationOmittedMinor > 0
          ? "unknown"
          : metrics.paymentAllocationCoverage,
  };
}

/**
 * Combine the scheduled and outside-schedule lanes into the week's total.
 *
 * The reporting frame is seven dates; every fact inside it lands in exactly
 * one lane, so the sum is everything that happened in the labelled date range
 * — which is what a headline over that range must say. The lanes stay stored
 * and separate as evidence; this is the read-time conclusion, so accepted
 * baselines keep their original values and fingerprints.
 *
 * Unknowns poison rather than vanish: an unknown profit or settlement on
 * either lane makes the combined value unknown instead of silently reporting
 * the half that happens to be provable.
 */
export function addWeekMetrics(
  a: ReportWeekMetrics,
  b: ReportWeekMetrics,
): ReportWeekMetrics {
  const left = normalizeWeekMetrics(a);
  const right = normalizeWeekMetrics(b);
  return {
    grossSalesMinor: left.grossSalesMinor + right.grossSalesMinor,
    netSalesMinor: left.netSalesMinor + right.netSalesMinor,
    refundsMinor: left.refundsMinor + right.refundsMinor,
    unitsSold: left.unitsSold + right.unitsSold,
    unitsReturned: left.unitsReturned + right.unitsReturned,
    uncostedRevenueMinor: left.uncostedRevenueMinor + right.uncostedRevenueMinor,
    grossProfitMinor:
      left.grossProfitMinor === null || right.grossProfitMinor === null
        ? null
        : left.grossProfitMinor + right.grossProfitMinor,
    paymentsCollectedMinor:
      left.paymentsCollectedMinor + right.paymentsCollectedMinor,
    paymentsRefundedMinor:
      left.paymentsRefundedMinor + right.paymentsRefundedMinor,
    paymentAllocatedMinor:
      left.paymentAllocatedMinor + right.paymentAllocatedMinor,
    paymentUnsettledMinor:
      left.paymentUnsettledMinor === null || right.paymentUnsettledMinor === null
        ? null
        : left.paymentUnsettledMinor + right.paymentUnsettledMinor,
    paymentAllocationCoverage:
      left.paymentAllocationCoverage === "unknown" ||
      right.paymentAllocationCoverage === "unknown"
        ? "unknown"
        : "complete",
    paymentAllocationOmittedMinor:
      left.paymentAllocationOmittedMinor + right.paymentAllocationOmittedMinor,
    paymentHasInvalidAllocation:
      left.paymentHasInvalidAllocation || right.paymentHasInvalidAllocation,
  };
}

export type ReportWeekCompletenessReason =
  | "complete"
  | "missing_schedule"
  | "missing_timezone"
  | "schedule_history_cap"
  | "missing_day_fold"
  | "mixed_currency"
  | "payment_coverage_unknown"
  | "payment_invalid_allocation"
  | "fact_cap_exceeded"
  | "legacy_fact_without_observed_at";

/**
 * Headline completeness covers included dates only. The outside-schedule lane
 * discloses its own verdict, so an excluded date neither withholds nor
 * silently completes the headline week. Optional while weekly documents
 * written before the split are refreshed.
 */
export type ReportWeekCompleteness = {
  complete: boolean;
  reason: ReportWeekCompletenessReason;
  outsideSchedule?: {
    complete: boolean;
    reason: ReportWeekCompletenessReason;
  };
};

/**
 * The verdict for the combined week. A total is only as trustworthy as its
 * weakest lane, so an incomplete outside-schedule lane makes the headline
 * incomplete too — the scheduled lane keeps its own verdict for the
 * breakdown. Every rebuild writes both verdicts; an absent outside-schedule
 * verdict means no lane-specific limitation was recorded, not a hidden one.
 */
export function combineWeekCompleteness(
  completeness: ReportWeekCompleteness,
): ReportWeekCompleteness {
  const outside = completeness.outsideSchedule;
  if (!completeness.complete) {
    return { complete: false, reason: completeness.reason, outsideSchedule: outside };
  }
  if (outside && !outside.complete) {
    return { complete: false, reason: outside.reason, outsideSchedule: outside };
  }
  return { complete: true, reason: "complete", outsideSchedule: outside };
}

export type ReportWeekLineage = {
  localDate: string;
  included: boolean;
  scheduleVersionId: string | null;
  dayStatus: ReportDayStatus | null;
  dayAvailable: boolean;
  activityPosture: "recorded" | "zero_activity" | "unavailable";
};

export type ReportWeekLifecyclePosture =
  | "live"
  | "awaiting_final_close"
  | "materializing"
  | "accepted"
  | "reopened_awaiting_successor"
  | "successor_accepted";

export type ReportWeekAmendmentPosture =
  | "none"
  | "pending_recompute"
  | "amended";

export type ReportWeekChangeDirection = "higher" | "lower" | "unchanged";

export type ReportWeekInventoryCompleteness =
  | "complete"
  | "incomplete"
  | "unavailable";

export type ReportWeekInventoryGroup = {
  classification: "carried_forward" | "new_this_week";
  evidenceLimited: boolean;
  hasNewActivity: boolean;
  key: string;
  memberCount: number;
  productSkuId: string | null;
};

/**
 * The inventory-attention lane, always present on a weekly projection.
 *
 * A projection materialized before the lane landed is normalized to the
 * explicit `unavailable` posture by the read queries rather than omitted, so a
 * client can never confuse "no lane evidence" with "no lane". The lane carries
 * no route: routing is rebuilt per read as `ReportWeekOwnerRoutes`.
 */
export type ReportWeekInventoryAttention = {
  carriedForwardCount: number;
  completeness: ReportWeekInventoryCompleteness;
  groups: ReportWeekInventoryGroup[];
  newCount: number;
  observedCount: number;
  overflow: boolean;
};

/**
 * Server-built owner navigation. The Reports layer is the single routing
 * authority for a weekly report; no route literal is ever persisted.
 */
export type ReportWeekOwnerRoutes = {
  transactions: {
    to: "/$orgUrlSlug/store/$storeUrlSlug/pos/transactions";
    search: { startDate: string; endDate: string; order: "oldestFirst" };
  };
  dailyClose:
    | {
        to: "/$orgUrlSlug/store/$storeUrlSlug/operations/daily-close";
        search: { operatingDate: string };
      }
    | {
        to: "/$orgUrlSlug/store/$storeUrlSlug/operations/daily-close-history";
        search: { day: string };
      }
    | null;
  cashControls: { to: "/$orgUrlSlug/store/$storeUrlSlug/cash-controls" };
  openWork: {
    to: "/$orgUrlSlug/store/$storeUrlSlug/operations/open-work";
    search: { workType: "synced_sale_inventory_review" };
  };
};

export type ReportWeekClosePosture = {
  acceptedCloseId: string;
  currentCloseId?: string;
  changedAt: number;
  status: "accepted" | "reopened_awaiting_successor" | "successor_accepted";
};

/**
 * `closeVarianceMinor` covers every frame date with close evidence. The split
 * names the two lanes behind it and is `null` for a stored row written before
 * the split existed, whose total means the scheduled lane alone.
 *
 * Coverage counts stay scheduled-only: an outside-schedule date without a
 * close was never expected to have one.
 */
export type ReportWeekVariancePosture = {
  closeVarianceMinor: number;
  coverage: "complete" | "partial" | "unavailable";
  coveredIncludedDayCount: number;
  includedDayCount: number;
  scheduledVarianceMinor: number | null;
  outsideScheduleVarianceMinor: number | null;
  outsideScheduleCoveredDayCount: number | null;
};

export type ReportWeekComparabilityReason =
  | "comparable"
  | "missing_schedule"
  | "missing_timezone"
  | "schedule_history_cap"
  | "scheduled_membership_changed"
  | "missing_prior_day_fold"
  | "prior_incomplete";

/** Prior period as read: stored lineage plus the derived presentation lane. */
export type ReportWeekPriorPeriod = {
  cycleStartDate: string;
  cycleEndDate: string;
  comparabilityReason: ReportWeekComparabilityReason;
  currentScheduledPositionCount: number;
  equivalentScheduledPositions: boolean;
  priorScheduledPositionCount: number;
  values: ReportWeekMetrics | null;
  /**
   * The prior week's outside-schedule lane. Optional only while prior-period
   * records written before the total lane landed are rebuilt; an absent value
   * means the prior total is not knowable, never that it was zero.
   */
  outsideScheduleValues?: ReportWeekMetrics | null;
  summary: ReportWeekSummary | null;
  /**
   * The prior week's total across the labelled date range — the only like-for-
   * like counterpart to the current week's headline. `null` when either lane
   * is unavailable.
   */
  totalSummary: ReportWeekSummary | null;
  /** Current total vs prior total. Never a scheduled-lane-only comparison. */
  netSalesChange: {
    amountMinor: number;
    direction: ReportWeekChangeDirection;
  } | null;
};

/** The single replacement amendment, with its presentation summaries. */
export type ReportWeekAmendment = {
  changedAt: number;
  currentFingerprint: string;
  included: ReportWeekMetrics;
  includedNetSalesDeltaMinor: number;
  outsideSchedule: ReportWeekMetrics;
  outsideScheduleNetSalesDeltaMinor: number;
  outsideScheduleSummary: ReportWeekSummary;
  /** Both lanes combined — the amended conclusion for the labelled range. */
  totalSummary: ReportWeekSummary;
  /** The headline movement: both lane deltas together. */
  netSalesDeltaMinor: number;
  sourceCloseAcceptedAt?: number;
  sourceCloseId?: string;
  summary: ReportWeekSummary;
};

/** Fields shared by the live and accepted weekly projections. */
type ReportWeekProjectionBase = {
  cycleStartDate: string;
  cycleEndDate: string;
  currency: string;
  metricVersion: number;
  included: ReportWeekMetrics;
  summary: ReportWeekSummary;
  outsideSchedule: ReportWeekMetrics;
  /** The outside-schedule lane as a presentation summary, always disclosed. */
  outsideScheduleSummary: ReportWeekSummary;
  /**
   * The headline conclusion for the labelled date range: both lanes combined.
   * Derived at read time from the stored lanes, so accepted baselines keep
   * their original values and fingerprints untouched.
   */
  total: ReportWeekSummary;
  /** The combined verdict — as trustworthy as the weaker of the two lanes. */
  totalCompleteness: ReportWeekCompleteness;
  scheduleLineage: ReportWeekLineage[];
  completeness: ReportWeekCompleteness;
  lifecyclePosture: ReportWeekLifecyclePosture;
  amendmentPosture: ReportWeekAmendmentPosture;
  inventoryAttention: ReportWeekInventoryAttention;
  closePosture?: ReportWeekClosePosture;
  amendment?: ReportWeekAmendment;
  priorPeriod?: ReportWeekPriorPeriod;
  variancePosture?: ReportWeekVariancePosture;
  ownerRoutes: ReportWeekOwnerRoutes;
};

/** The live weekly singleton as read. Never a source or document identity. */
export type ReportWeekCurrentProjection = ReportWeekProjectionBase & {
  materializedAt: number;
};

/**
 * An immutable accepted baseline as read. `current` restates later truth
 * beside, never over, the accepted values.
 */
export type ReportWeekAcceptedProjection = ReportWeekProjectionBase & {
  reportId: string;
  acceptedAt: number;
  cutoffObservedAt: number;
  closeId: string;
  current?: {
    included: ReportWeekMetrics;
    summary: ReportWeekSummary;
    includedNetSalesDeltaMinor: number;
    outsideSchedule: ReportWeekMetrics;
    outsideScheduleSummary: ReportWeekSummary;
    outsideScheduleNetSalesDeltaMinor: number;
    totalSummary: ReportWeekSummary;
    netSalesDeltaMinor: number;
  };
};

export type ReportWeekUnavailableReason =
  | "capability_disabled"
  | "missing_schedule"
  | "missing_timezone"
  | "schedule_history_cap"
  | "no_scheduled_dates"
  | "missing_day_fold"
  | "missing_projection";

/** The weekly tab's single subscription envelope. */
export type ReportWeekBriefing =
  | { status: "unavailable"; reason: ReportWeekUnavailableReason }
  | {
      status: "available";
      current: ReportWeekCurrentProjection;
      acceptedBaseline: ReportWeekAcceptedProjection | null;
    };

/** One page of accepted history, newest first. */
export type ReportWeekHistoryPage = {
  page: ReportWeekAcceptedProjection[];
  isDone: boolean;
  continueCursor: string;
  splitCursor?: string | null;
  pageStatus?: "SplitRecommended" | "SplitRequired" | null;
};

export function derivePaymentPosture(args: {
  collectedMinor: number;
  refundedMinor: number;
  allocatedMinor: number;
  allocationOmittedMinor: number;
}): ReportPaymentPosture {
  const eligibleMinor = Math.max(0, args.collectedMinor - args.refundedMinor);
  const hasUnknownCoverage = args.allocationOmittedMinor > 0;
  const hasInvalidAllocation =
    args.allocatedMinor < 0 || args.allocatedMinor > eligibleMinor;

  return {
    collectedMinor: args.collectedMinor,
    refundedMinor: args.refundedMinor,
    allocatedMinor: args.allocatedMinor,
    unsettledMinor: hasUnknownCoverage
      ? null
      : Math.max(0, eligibleMinor - Math.max(0, args.allocatedMinor)),
    allocationCoverage: hasUnknownCoverage ? "unknown" : "complete",
    allocationOmittedMinor: args.allocationOmittedMinor,
    hasInvalidAllocation,
  };
}

// ---------------------------------------------------------------------------
// Fold interface (slice A implements; slices C and F call)
// ---------------------------------------------------------------------------

/** Projection of a reportFact document that the fold consumes. Pure data. */
export type FoldFact = {
  factId: string;
  sourceDomain: ReportSourceDomain;
  sourceId: string;
  lineId: string;
  factKind: ReportFactKind;
  occurredAt: number;
  recordedAt: number;
  currency: string;
  grossAmountMinor: number;
  netAmountMinor: number;
  taxAmountMinor: number;
  discountAmountMinor: number;
  quantity: number;
  productSkuId?: string;
  unitCostMinor?: number;
  paymentAllocationMinor?: number;
  paymentAllocationCoverage?: "known" | "unknown";
  quarantined: boolean;
};

export type CloseRef = {
  closeId: string;
  acceptedAt: number;
  closeNetSalesMinor: number;
};

export type SkuDayFoldResult = ReportSkuDayMetrics;

export type DayFoldResult = {
  day: ReportDayMetrics & {
    status: Exclude<ReportDayStatus, "open">;
    flags: ReportDayFlags;
    factCount: number;
    lastFactRecordedAt: number;
    closeVarianceMinor?: number;
    postCloseNetSalesDeltaMinor?: number;
    paymentPosture: ReportPaymentPosture;
  };
  /** Keyed by productSkuId. Only SKUs with activity appear. */
  skuDays: Map<string, SkuDayFoldResult>;
};

/** Signature slice A implements. Pure: no ctx, no db, deterministic. */
export type FoldDayFn = (
  storeCurrency: string,
  facts: readonly FoldFact[],
  close?: CloseRef,
) => DayFoldResult;

// ---------------------------------------------------------------------------
// Ingestion interface (slice B1 implements; B2 emitters and F reseed call)
// ---------------------------------------------------------------------------

/** One fact as emitted by a domain mutation. Identity is structural. */
export type NewReportFact = {
  sourceDomain: ReportSourceDomain;
  sourceId: string;
  /** Line discriminator within the source document; "" for header-level facts. */
  lineId: string;
  factKind: ReportFactKind;
  /** Business time — when the event happened (NOT sync/arrival time). */
  occurredAt: number;
  /**
   * Normally omitted — ingestion stamps arrival time itself. The reseed
   * walker passes business time here so re-derived historical facts don't
   * postdate their day's close and wrongly fold every reseeded day as
   * `amended`. Live emitters must NOT set this.
   */
  recordedAt?: number;
  currency: string;
  grossAmountMinor: number;
  netAmountMinor: number;
  taxAmountMinor: number;
  discountAmountMinor: number;
  quantity: number;
  productSkuId?: string;
  unitCostMinor?: number;
  /** Source-proven signed allocation; omitted on legacy payment facts. */
  paymentAllocationMinor?: number;
  paymentAllocationCoverage?: "known" | "unknown";
};

export type ReportSkuTransactionEvidence = {
  sourceDomain: "pos" | "storefront";
  sourceId: string;
  reference: string;
  occurredAt: number;
  status: string;
  quantity: number;
  netSalesMinor: number;
  costMinor: number | null;
  grossProfitMinor: number | null;
  hasRefunds: boolean;
  hasAdjustments: boolean;
};

// ---------------------------------------------------------------------------
// Period keys and rollups
// ---------------------------------------------------------------------------

/** Calendar period keys: "d:2026-07-28" | "w:2026-W31" | "m:2026-07". */
export type ReportPeriodKey = string;

export function dayPeriodKey(operatingDate: string): ReportPeriodKey {
  return `d:${operatingDate}`;
}

export function monthPeriodKey(operatingDate: string): ReportPeriodKey {
  return `m:${operatingDate.slice(0, 7)}`;
}

/** First operating date of the three-calendar-month window ending at anchor. */
export function trailingThreeMonthsStart(anchorDate: string): string {
  const anchor = new Date(`${anchorDate}T00:00:00.000Z`);
  return new Date(
    Date.UTC(anchor.getUTCFullYear(), anchor.getUTCMonth() - 2, 1),
  )
    .toISOString()
    .slice(0, 10);
}

/** First operating date of the six-calendar-month window ending at anchor. */
export function trailingSixMonthsStart(anchorDate: string): string {
  const anchor = new Date(`${anchorDate}T00:00:00.000Z`);
  return new Date(
    Date.UTC(anchor.getUTCFullYear(), anchor.getUTCMonth() - 5, 1),
  )
    .toISOString()
    .slice(0, 10);
}

/**
 * ISO-8601 week key for an operating-date label. Operating dates are calendar
 * labels, so UTC math over the label is correct by construction — no store
 * timezone enters here.
 */
export function weekPeriodKey(operatingDate: string): ReportPeriodKey {
  const d = new Date(`${operatingDate}T00:00:00.000Z`);
  // ISO week: Thursday of the current week determines the week-year.
  const day = d.getUTCDay() === 0 ? 7 : d.getUTCDay();
  d.setUTCDate(d.getUTCDate() + 4 - day);
  const yearStart = Date.UTC(d.getUTCFullYear(), 0, 1);
  const week = Math.ceil(((d.getTime() - yearStart) / 86_400_000 + 1) / 7);
  return `w:${d.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}

export function periodKeysForOperatingDate(
  operatingDate: string,
): ReportPeriodKey[] {
  return [
    dayPeriodKey(operatingDate),
    weekPeriodKey(operatingDate),
    monthPeriodKey(operatingDate),
  ];
}

/** Convex indexes sort ascending; store negated measures for descending top-N. */
export function descendingSortKey(value: number): number {
  return -value;
}

/**
 * Canonical currency-code form used on every fact and day doc. Store config
 * carries codes in mixed case (dev stores have "ghs"); emitters, the fold's
 * store-currency argument, and reseed must ALL normalize through this one
 * helper — a raw comparison silently excludes every fact as foreign currency.
 */
export function normalizeCurrencyCode(currency: string | undefined): string {
  return (currency ?? "").trim().toUpperCase() || "GHS";
}

// ---------------------------------------------------------------------------
// Overview document (slice C materializes; the dashboard subscribes to it ONLY)
// ---------------------------------------------------------------------------

export type ReportPeriodSnapshot = ReportDayMetrics & {
  dayCount: number;
  /** Days in the period still open/provisional (numbers may move). */
  unsettledDayCount: number;
};

export type ReportTrendPoint = {
  operatingDate: string;
  netSalesMinor: number;
  status: ReportDayStatus;
  /** Optional while existing overview documents are refreshed by the sweeper. */
  unitsSold?: number;
  /**
   * Completed POS transactions for the day, read from the register close
   * summary. Absent until the day is closed — an in-progress day has no
   * settled count to report, and deriving one live would cost the overview
   * read budget it exists to protect.
   */
  transactionCount?: number;
};

export type ReportTrustSummary = {
  reconciledDays: number;
  provisionalDays: number;
  amendedDays: number;
  oldestUnreconciledDate?: string;
};

export type ReportOverviewData = {
  updatedAt: number;
  currency: string;
  today: ReportPeriodSnapshot;
  yesterday: ReportPeriodSnapshot;
  weekToDate: ReportPeriodSnapshot;
  priorWeek: ReportPeriodSnapshot;
  trailing30: ReportPeriodSnapshot;
  priorTrailing30: ReportPeriodSnapshot;
  trailing3Months: ReportPeriodSnapshot;
  priorTrailing3Months: ReportPeriodSnapshot;
  trailing6Months: ReportPeriodSnapshot;
  priorTrailing6Months: ReportPeriodSnapshot;
  comparisons: {
    netSalesVsPriorWeekBp: number | null;
    unitsSoldVsPriorWeekBp: number | null;
  };
  /** Last 30 operating days, ascending — the dashboard chart reads this inline. */
  dailyTrend: ReportTrendPoint[];
  trust: ReportTrustSummary;
};

// ---------------------------------------------------------------------------
// Read-query result shapes (slice D implements; slice E consumes)
// ---------------------------------------------------------------------------

export type ReportDayRow = ReportDayMetrics & {
  operatingDate: string;
  status: ReportDayStatus;
  currency: string;
  flags: ReportDayFlags;
  factCount: number;
  /**
   * Exact count of `reportSkuDay` rows the fold wrote for this day.
   *
   * Carried so the days rail can SIZE the SKU-mix read before it is issued
   * (`skuMixSyncRowProbe`). Optional: days folded before U8 carry none, and a
   * missing count means "unknown", never zero — see the probe.
   */
  skuDayRowCount?: number;
  closeVarianceMinor?: number;
  postCloseNetSalesDeltaMinor?: number;
};

/**
 * Enough to tell one SKU from another in a list.
 *
 * Resolved at read time from `productSku` (all fields denormalized there, so
 * one document read per row and no joins). The `sku` code is what actually
 * disambiguates: product names repeat — wigclub has 13 SKUs named "bottle
 * water" identical on every other attribute — while the code is present on
 * every SKU. `size` is carried when set (~86% of SKUs) as a human-readable
 * hint; colour and length are too sparse to be worth a lookup.
 *
 * Absent when the SKU document is gone — a reporting fact outlives its
 * subject, so the id remains the fallback rather than dropping the row.
 */
export type ReportSkuIdentity = {
  displayName: string;
  sku?: string;
  size?: string;
  /** Current catalog net price in the store's minor currency unit, when set. */
  netPriceMinor?: number;
  /** Current catalog unit cost in the store's minor currency unit, when set. */
  unitCostMinor?: number;
  /** Primary SKU image, when one is available. */
  imageUrl?: string;
  /**
   * Owning product, for linking out to the product detail page. Already on
   * the `productSku` document, so it costs no extra read.
   */
  productId?: string;
  quantityAvailable?: number;
};

export type ReportSkuPeriodRow = ReportSkuDayMetrics & {
  productSkuId: string;
  periodKey: ReportPeriodKey;
  identity?: ReportSkuIdentity;
};

export type ReportSkuSortBy = "revenue" | "units";

export type ReportSkuMixRow = {
  key: string;
  productSkuId?: string;
  label: string;
  unitsSold: number;
  shareBasisPoints: number;
  identity?: ReportSkuIdentity;
};

export type ReportSkuMixData = {
  rows: ReportSkuMixRow[];
  totalUnitsSold: number;
  skuCount: number;
};

export type ReportSkuMovementRow = {
  key: string;
  productSkuId: string;
  label: string;
  unitsSold: number;
  unitsReturned: number;
  netUnits: number;
  identity?: ReportSkuIdentity;
};

export type ReportSkuMovementData = {
  rows: ReportSkuMovementRow[];
  totalUnitsSold: number;
  totalUnitsReturned: number;
  netUnits: number;
  skuCount: number;
};

export type ReportRangeStatus = "pending" | "completed" | "failed";

export type ReportRangeSummary = {
  requestKey: string;
  startDate: string;
  endDate: string;
  status: ReportRangeStatus;
  totals?: ReportDayMetrics & { dayCount: number; unsettledDayCount: number };
  topSkus?: ReportSkuPeriodRow[];
  failureReason?: string;
  computedAt?: number;
  expiresAt: number;
};

export const REPORT_RANGE_MAX_DAYS = 366 as const;
export const REPORT_RANGE_TTL_MS = 7 * 24 * 60 * 60 * 1000;
export const REPORT_SKU_PAGE_SIZE = 10 as const;
export const REPORT_RANGE_TOP_SKU_LIMIT = 100 as const;

/**
 * Inclusive-day maximum of a calendar-aligned trailing six-month window.
 *
 * 184, not 183. The window is calendar-month aligned (`trailingSixMonthsStart`
 * through the anchor), so its length is a sum of six real month lengths, not a
 * fixed day count. The four longest six-month runs each contain 184 days:
 *
 *   Mar–Aug: 31 + 30 + 31 + 30 + 31 + 31 = 184
 *   May–Oct: 31 + 30 + 31 + 31 + 30 + 31 = 184
 *   Jul–Dec: 31 + 31 + 30 + 31 + 30 + 31 = 184
 *   Aug–Jan: 31 + 30 + 31 + 30 + 31 + 31 = 184
 *
 * A 183-day ceiling would reject exactly those windows — an intermittent,
 * date-dependent failure that looks random in production. Do not "simplify"
 * this to 183.
 */
export const REPORT_TRAILING_SIX_MONTHS_MAX_DAYS = 184 as const;

/**
 * General drill-down span ceiling (days table, SKU detail, Units moved) now
 * that the trailing six-month window is explorable. Declared in U1, applied
 * in U5/U7: `listDays` and `getSkuDetail` validate and read against it, and
 * `REPORT_MOVEMENT_RANGE_MAX_DAYS` below equals it. The synchronous SKU mix
 * and legacy movement readers deliberately keep their narrower 92-day cap
 * (`RANGE_SYNC_READER_MAX_SPAN_DAYS` in convex/reports/queries.ts).
 */
export const REPORT_DRILLDOWN_RANGE_MAX_DAYS =
  REPORT_TRAILING_SIX_MONTHS_MAX_DAYS;

// ---------------------------------------------------------------------------
// Range request kinds — the shared range-result lifecycle now serves three
// consumers. A stored `reportRangeResult` row WITHOUT a `kind` field is a
// legacy custom-summary request and keeps its exact original semantics
// (including failed-row reuse until TTL and the 366-day span limit).
// ---------------------------------------------------------------------------

export const REPORT_RANGE_KINDS = [
  "custom_summary",
  "sku_movement",
  "sku_mix",
] as const;
export type ReportRangeKind = (typeof REPORT_RANGE_KINDS)[number];

/** Inclusive-day span ceilings, per request kind. */
/**
 * Movement serves the full drill-down span since U7. Its per-day resumable
 * design (one bounded source batch per included day) makes the wider window
 * a matter of more batches, not bigger ones; the pre-admission
 * revision-vector read is bounded by this same constant.
 */
export const REPORT_MOVEMENT_RANGE_MAX_DAYS = REPORT_DRILLDOWN_RANGE_MAX_DAYS;
/** Mix serves the full trailing six-month window (its ambient consumer). */
export const REPORT_MIX_RANGE_MAX_DAYS = REPORT_TRAILING_SIX_MONTHS_MAX_DAYS;
export const REPORT_RANGE_MAX_DAYS_BY_KIND = {
  custom_summary: REPORT_RANGE_MAX_DAYS,
  sku_movement: REPORT_MOVEMENT_RANGE_MAX_DAYS,
  sku_mix: REPORT_MIX_RANGE_MAX_DAYS,
} as const satisfies Record<ReportRangeKind, number>;

/**
 * Span threshold (inclusive days) at or under which SKU mix stays on the
 * synchronous reader permanently. Provably under the cap: the fold bounds
 * `reportSkuDay` at 2,000 rows per operating day (`MAX_SKU_DAY_ROWS_PER_DAY`
 * in convex/reports/sweeper.ts), so a 2-day span reads at most
 * 2 × 2,000 = 4,000 rows — strictly below the 5,000-row synchronous cap
 * (`RANGE_SKU_MIX_ROW_LIMIT` in convex/reports/queries.ts). DECLARED here
 * (U1); U5's span routing applies it.
 */
export const REPORT_SKU_MIX_SYNC_MAX_DAYS = 2 as const;

/**
 * Row budget the SKU-mix probe must clear to route a span synchronously.
 *
 * Deliberately below `RANGE_SKU_MIX_ROW_LIMIT` (5,000). The probe reads day
 * counts folded a moment ago; the mix read happens after. A concurrent fold
 * can add rows in between, so the 1,000-row gap absorbs that drift rather
 * than letting the reader's fail-closed throw reach the operator as "choose a
 * shorter range". Sized against production: wigclub's busiest day folds 88
 * SKU rows, so the gap covers eleven such days landing mid-flight.
 */
export const REPORT_SKU_MIX_SYNC_ROW_BUDGET = 4_000 as const;

/**
 * Size a SKU-mix range from the days rail before paying for it.
 *
 * The span rule this supplements (`REPORT_SKU_MIX_SYNC_MAX_DAYS`) is calibrated
 * to the fold's 2,000-rows-per-day ceiling — a bound real stores sit far below
 * (wigclub's median day: 30 rows), so a 3-day selection was buying an async
 * snapshot to fold a few hundred rows. The days rail already loads one
 * `reportDay` doc per day for the same window and each carries its exact
 * `skuDayRowCount`, so the cost of the mix read is knowable for free.
 *
 * Returns the summed row count when EVERY day of `[startDate, endDate]` is
 * accounted for, or `undefined` when it is not provable — the caller must then
 * fall back to the span rule. Indeterminate cases, all of which must stay
 * indeterminate rather than defaulting to zero:
 *
 *   - `rows` does not span the requested range (the days rail loaded a
 *     narrower window than the mix selection covers), or
 *   - a row inside the range predates the count and carries `undefined`.
 *
 * Absent rows are NOT indeterminate: `reportDay` is sparse, and a day with no
 * document had no activity and therefore no `reportSkuDay` rows. That is why
 * `coverageStartDate`/`coverageEndDate` are required — they prove the reader
 * looked at the range, which row presence alone cannot.
 */
export function skuMixSyncRowProbe({
  coverageEndDate,
  coverageStartDate,
  endDate,
  rows,
  startDate,
}: {
  coverageEndDate: string;
  coverageStartDate: string;
  endDate: string;
  rows: readonly Pick<ReportDayRow, "operatingDate" | "skuDayRowCount">[];
  startDate: string;
}): number | undefined {
  if (coverageStartDate > startDate || coverageEndDate < endDate) {
    return undefined;
  }

  let total = 0;
  for (const row of rows) {
    if (row.operatingDate < startDate || row.operatingDate > endDate) continue;
    if (row.skuDayRowCount === undefined) return undefined;
    total += row.skuDayRowCount;
  }
  return total;
}

/** Rows per movement page — Top movers shows one page, Granular pages by it. */
export const REPORT_MOVEMENT_PAGE_SIZE = 20 as const;

/**
 * Semantic version of the movement snapshot contract (aggregation, ranking,
 * and child-row meaning). Participates in the movement request key, so a
 * contract change can never reuse a snapshot computed under the old meaning.
 */
export const REPORT_MOVEMENT_CONTRACT_VERSION = 1 as const;

/**
 * Explicit sentinel for an included operating day with no `reportDay` row.
 * An absent day is part of the request's identity — "this day had no fold" —
 * not an omission from the revision vector.
 */
export const REPORT_MOVEMENT_EMPTY_DAY_REVISION = "empty" as const;

/**
 * One entry per included operating day. `revision` is the day's certified
 * fold revision (`reportDay.certifiedFoldRevision`) or the empty-day
 * sentinel. Bounded by REPORT_MOVEMENT_RANGE_MAX_DAYS entries.
 */
export type ReportMovementDayRevision = {
  operatingDate: string;
  revision: number | typeof REPORT_MOVEMENT_EMPTY_DAY_REVISION;
};

// ---------------------------------------------------------------------------
// Strict operating-date validation. `queries.ts`'s loose span-only check is
// deliberately NOT reused for movement: malformed labels must fail before
// they participate in a durable request identity.
// ---------------------------------------------------------------------------

const OPERATING_DATE_LABEL_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/** Strict "YYYY-MM-DD" shape AND calendar validity (no 2026-02-30). */
export function isValidOperatingDateLabel(value: string): boolean {
  if (!OPERATING_DATE_LABEL_PATTERN.test(value)) return false;
  const [year, month, day] = value.split("-").map(Number);
  const asDate = new Date(Date.UTC(year, month - 1, day));
  return (
    asDate.getUTCFullYear() === year &&
    asDate.getUTCMonth() === month - 1 &&
    asDate.getUTCDate() === day
  );
}

/** Inclusive day count between two well-formed "YYYY-MM-DD" labels. */
export function inclusiveOperatingDaySpan(
  startDate: string,
  endDate: string,
): number {
  const toUtc = (label: string) => {
    const [year, month, day] = label.split("-").map(Number);
    return Date.UTC(year, month - 1, day);
  };
  return Math.round((toUtc(endDate) - toUtc(startDate)) / 86_400_000) + 1;
}

/**
 * Shared per-kind range validation: strict date labels, ordering, and the
 * kind's own span ceiling. Throws on the first violation.
 */
export function validateReportRangeRequest(
  kind: ReportRangeKind,
  startDate: string,
  endDate: string,
): void {
  if (!isValidOperatingDateLabel(startDate)) {
    throw new Error(`Invalid startDate: "${startDate}".`);
  }
  if (!isValidOperatingDateLabel(endDate)) {
    throw new Error(`Invalid endDate: "${endDate}".`);
  }
  if (startDate > endDate) {
    throw new Error("startDate must be on or before endDate.");
  }
  const maxDays = REPORT_RANGE_MAX_DAYS_BY_KIND[kind];
  const span = inclusiveOperatingDaySpan(startDate, endDate);
  if (span > maxDays) {
    throw new Error(
      `Range spans ${span} days; the maximum is ${maxDays} days.`,
    );
  }
}

// ---------------------------------------------------------------------------
// Movement request identity. Legacy custom-summary keys keep their exact
// original "range:" shape (computed in convex/reports/customRange.ts and
// never including a kind). Movement keys use a distinct prefix AND fold the
// kind, contract/fold versions, and the included-day revision vector into the
// hashed identity, so a summary and a movement request over identical dates
// cannot collide, and a revision change yields a successor request.
// ---------------------------------------------------------------------------

/** Legacy custom-summary keys — shape is frozen; do not reuse for movement. */
export const REPORT_RANGE_SUMMARY_REQUEST_KEY_PREFIX = "range:" as const;
export const REPORT_MOVEMENT_REQUEST_KEY_PREFIX = "movement:" as const;
export const REPORT_MIX_REQUEST_KEY_PREFIX = "mix:" as const;

export type ReportMovementRequestIdentityArgs = {
  storeId: string;
  startDate: string;
  endDate: string;
  foldVersion: number;
  contractVersion: number;
  revisionVector: readonly ReportMovementDayRevision[];
};

/**
 * Canonical (pre-hash) identity string. Fixed field order is part of the
 * contract: changing it bumps REPORT_MOVEMENT_CONTRACT_VERSION.
 */
export function movementRequestKeyIdentity(
  args: ReportMovementRequestIdentityArgs,
): string {
  return JSON.stringify([
    "sku_movement",
    args.storeId,
    args.startDate,
    args.endDate,
    args.foldVersion,
    args.contractVersion,
    args.revisionVector.map((day) => [day.operatingDate, day.revision]),
  ]);
}

/**
 * Deterministic movement request key. The hash function is injected (Convex
 * passes `stableStringHash` from reports/fingerprint.ts) so this shared
 * module stays free of backend imports while the identity ordering — the part
 * that must not drift — lives in one place.
 */
export function computeMovementRequestKey(
  args: ReportMovementRequestIdentityArgs,
  hash: (input: string) => string,
): string {
  return `${REPORT_MOVEMENT_REQUEST_KEY_PREFIX}${hash(
    movementRequestKeyIdentity(args),
  )}`;
}

// ---------------------------------------------------------------------------
// Certified fold revisions — the movement trust boundary. A day (and its SKU
// rows) is admissible movement evidence only when it carries a certified
// revision written by the current fold version. Stamping and history repair
// are U2's job; these helpers define what "admissible" means.
// ---------------------------------------------------------------------------

/**
 * Maps a `reportDay` row (or its absence) to an admissible revision-vector
 * entry, or null when the day cannot be admitted yet:
 * - no row → the explicit empty-day sentinel (admissible: no activity);
 * - a row missing `certifiedFoldRevision` → null (uncertified, repair pending);
 * - a row folded under a stale fold version → null (stale, repair pending).
 */
export function admissibleMovementDayRevision(
  operatingDate: string,
  day: { foldVersion: number; certifiedFoldRevision?: number | null } | null,
): ReportMovementDayRevision | null {
  if (day === null) {
    return { operatingDate, revision: REPORT_MOVEMENT_EMPTY_DAY_REVISION };
  }
  if (
    day.certifiedFoldRevision === undefined ||
    day.certifiedFoldRevision === null
  ) {
    return null;
  }
  if (day.foldVersion !== REPORTS_FOLD_VERSION) return null;
  return { operatingDate, revision: day.certifiedFoldRevision };
}

/**
 * Whether a `reportSkuDay` source row matches its day's expected revision.
 * An empty-sentinel day has no admissible rows; a row missing its own
 * certified revision never matches.
 */
export function movementSourceRowMatchesRevision(
  expected: ReportMovementDayRevision["revision"],
  row: { certifiedFoldRevision?: number | null },
): boolean {
  if (expected === REPORT_MOVEMENT_EMPTY_DAY_REVISION) return false;
  if (
    row.certifiedFoldRevision === undefined ||
    row.certifiedFoldRevision === null
  ) {
    return false;
  }
  return row.certifiedFoldRevision === expected;
}

// ---------------------------------------------------------------------------
// Movement ordering. Convex indexes are ascending-only, so the sort key is
// the NEGATED absolute net movement (matching the reportPeriodSkuRollup
// sort-key convention); the index tie-break is stable SKU identity.
// ---------------------------------------------------------------------------

/** Negated |netUnits|: ascending index order = descending absolute movement. */
export function movementAbsNetUnitsSortKey(netUnits: number): number {
  // `|| 0` normalizes -0 (from -Math.abs(0)) to +0 so a fully-cancelled SKU
  // stores a canonical zero key rather than a sign-of-zero oddity.
  return -Math.abs(netUnits) || 0;
}

// ---------------------------------------------------------------------------
// Movement lifecycle.
//
// Durable phases live on the admitted request header. The PUBLIC lifecycle is
// a separate discriminated union: waiting/backpressure/not-available carry no
// durable row at all (the ensure mutation returns them without writing), and
// no public state ever exposes exception text, cursors, fences, or source
// details.
// ---------------------------------------------------------------------------

export const REPORT_MOVEMENT_REQUEST_PHASES = [
  "queued",
  "aggregating",
  "ranking",
  "retry_wait",
  "completed",
  "terminal_error",
  "cleaning",
] as const;
export type ReportMovementRequestPhase =
  (typeof REPORT_MOVEMENT_REQUEST_PHASES)[number];

/** Authoritative completed totals; written only at rank finalization. */
export type ReportMovementTotals = {
  unitsSold: number;
  unitsReturned: number;
  netUnits: number;
  skuCount: number;
};

export type ReportMovementLifecycle =
  | { state: "waiting"; retryAfterMs: number }
  | { state: "backpressure"; retryAfterMs: number }
  | { state: "not_available" }
  | { state: "queued_pending" }
  | {
      state: "completed";
      totals: ReportMovementTotals;
      completedAt: number;
      pageCount: number;
    }
  | { state: "terminal_error"; errorCode: string; correlationId: string };

/** Number of granular pages a completed snapshot exposes. */
export function movementPageCount(skuCount: number): number {
  return Math.max(1, Math.ceil(skuCount / REPORT_MOVEMENT_PAGE_SIZE));
}

/**
 * Derives the public lifecycle from an admitted movement header.
 *
 * Deliberately conservative: "completed" requires the completed phase AND
 * finalized totals AND a completion time together — a header with partial
 * aggregation/ranking state (or a completed phase missing its totals) can
 * only ever surface as queued/pending. "terminal_error" requires both the
 * sanitized code and the correlation id; internal exception text, cursors,
 * and fences never cross this boundary.
 */
export function deriveMovementRequestLifecycle(header: {
  movementPhase?: ReportMovementRequestPhase;
  movementTotals?: ReportMovementTotals;
  computedAt?: number;
  movementErrorCode?: string;
  movementCorrelationId?: string;
}): Extract<
  ReportMovementLifecycle,
  { state: "queued_pending" | "completed" | "terminal_error" }
> {
  if (
    header.movementPhase === "completed" &&
    header.movementTotals !== undefined &&
    header.computedAt !== undefined
  ) {
    return {
      state: "completed",
      totals: header.movementTotals,
      completedAt: header.computedAt,
      pageCount: movementPageCount(header.movementTotals.skuCount),
    };
  }
  if (
    header.movementPhase === "terminal_error" &&
    header.movementErrorCode !== undefined &&
    header.movementCorrelationId !== undefined
  ) {
    return {
      state: "terminal_error",
      errorCode: header.movementErrorCode,
      correlationId: header.movementCorrelationId,
    };
  }
  return { state: "queued_pending" };
}

// ---------------------------------------------------------------------------
// SKU mix snapshot contract (U4). Mix rides the same kind-generic lifecycle
// rail movement established — the `movement*` header columns are the generic
// phase/fence/totals machinery for any kind (see reportRangeResultSchema) —
// but has NO ranking phase: the surface only ever shows top 5 + Other, so
// child rows carry a descending units-sold sort key and the reader selects
// the top rows through that index at read time. No rank field exists.
// ---------------------------------------------------------------------------

/**
 * Semantic version of the mix snapshot contract (aggregation and child-row
 * meaning). Participates in the mix request key, so a contract change can
 * never reuse a snapshot computed under the old meaning.
 */
export const REPORT_MIX_CONTRACT_VERSION = 1 as const;

/**
 * Visible mix rows before the Other bucket. Must stay equal to the sync
 * reader's `RANGE_SKU_MIX_VISIBLE_LIMIT` (convex/reports/queries.ts) — the
 * two paths present the same contract and U5 routes between them by span.
 */
export const REPORT_MIX_VISIBLE_ROW_LIMIT = 5 as const;

export type ReportMixRequestIdentityArgs = {
  storeId: string;
  startDate: string;
  endDate: string;
  foldVersion: number;
  contractVersion: number;
  revisionVector: readonly ReportMovementDayRevision[];
};

/**
 * Canonical (pre-hash) identity string. Fixed field order is part of the
 * contract: changing it bumps REPORT_MIX_CONTRACT_VERSION. The "sku_mix"
 * kind literal keeps a mix key from ever colliding with a movement key over
 * the same store, dates, and revisions.
 */
export function mixRequestKeyIdentity(
  args: ReportMixRequestIdentityArgs,
): string {
  return JSON.stringify([
    "sku_mix",
    args.storeId,
    args.startDate,
    args.endDate,
    args.foldVersion,
    args.contractVersion,
    args.revisionVector.map((day) => [day.operatingDate, day.revision]),
  ]);
}

/** Deterministic mix request key (hash injected as for movement keys). */
export function computeMixRequestKey(
  args: ReportMixRequestIdentityArgs,
  hash: (input: string) => string,
): string {
  return `${REPORT_MIX_REQUEST_KEY_PREFIX}${hash(
    mixRequestKeyIdentity(args),
  )}`;
}

/**
 * Negated unitsSold: ascending index order = descending units sold. `|| 0`
 * normalizes -0 (from a zero input) to a canonical +0 key, mirroring
 * `movementAbsNetUnitsSortKey` — though mix children are only ever written
 * for accumulated unitsSold > 0.
 */
export function mixUnitsSoldSortKey(unitsSold: number): number {
  return -unitsSold || 0;
}

/**
 * Authoritative completed mix totals: total units sold across the range and
 * the number of distinct SKUs with any units sold. Stored on the header's
 * generic totals rail (`movementTotals`, with `unitsSold`/`netUnits` both
 * carrying the sold total and `unitsReturned` structurally zero — mix counts
 * sold units only), accumulated during aggregation because mix has no
 * ranking pass to accumulate in.
 */
export type ReportMixTotals = {
  totalUnitsSold: number;
  skuCount: number;
};

export type ReportMixLifecycle =
  | { state: "waiting"; retryAfterMs: number }
  | { state: "backpressure"; retryAfterMs: number }
  | { state: "not_available" }
  | { state: "queued_pending" }
  | { state: "completed"; totals: ReportMixTotals; completedAt: number }
  | { state: "terminal_error"; errorCode: string; correlationId: string };

/**
 * Derives the public mix lifecycle from an admitted mix header. Same
 * conservative shape as movement's: "completed" requires the completed phase
 * AND finalized totals AND a completion time together; "terminal_error"
 * requires both the sanitized code and the correlation id. Internal
 * exception text, cursors, and fences never cross this boundary.
 */
export function deriveMixRequestLifecycle(header: {
  movementPhase?: ReportMovementRequestPhase;
  movementTotals?: ReportMovementTotals;
  computedAt?: number;
  movementErrorCode?: string;
  movementCorrelationId?: string;
}): Extract<
  ReportMixLifecycle,
  { state: "queued_pending" | "completed" | "terminal_error" }
> {
  if (
    header.movementPhase === "completed" &&
    header.movementTotals !== undefined &&
    header.computedAt !== undefined
  ) {
    return {
      state: "completed",
      totals: {
        totalUnitsSold: header.movementTotals.unitsSold,
        skuCount: header.movementTotals.skuCount,
      },
      completedAt: header.computedAt,
    };
  }
  if (
    header.movementPhase === "terminal_error" &&
    header.movementErrorCode !== undefined &&
    header.movementCorrelationId !== undefined
  ) {
    return {
      state: "terminal_error",
      errorCode: header.movementErrorCode,
      correlationId: header.movementCorrelationId,
    };
  }
  return { state: "queued_pending" };
}
