import { v } from "convex/values";

export const inventoryImportCostOverlayDecisionValidator = v.union(
  v.literal("selected_missing_cost"),
  v.literal("overwrite_selected"),
  v.literal("not_selected"),
  v.literal("ineligible"),
);

export const inventoryImportCostOverlayCommandDecisionValidator = v.union(
  v.literal("selected_missing_cost"),
  v.literal("overwrite_selected"),
  v.literal("not_selected"),
);

export const inventoryImportCostOverlayEligibilityValidator = v.union(
  v.literal("eligible"),
  v.literal("ineligible"),
);

export const inventoryImportCostOverlayWorkStatusValidator = v.union(
  v.literal("pending"),
  v.literal("applied"),
  v.literal("apply_exception"),
  v.literal("undone"),
  v.literal("undo_exception"),
);

export const inventoryImportCostOverlayCostOutcomeValidator = v.union(
  v.literal("valid"),
  v.literal("missing"),
  v.literal("invalid_syntax"),
  v.literal("negative"),
  v.literal("excess_precision"),
  v.literal("out_of_range"),
);

const inventoryImportCostOverlayFrozenLineageValidator = v.object({
  provisionalSkuId: v.id("inventoryImportProvisionalSku"),
  productSkuId: v.optional(v.id("productSku")),
  status: v.union(
    v.literal("active"),
    v.literal("finalized"),
    v.literal("rejected"),
    v.literal("closed"),
  ),
  updatedAt: v.number(),
});

export const inventoryImportCostOverlayRowInputValidator = v.object({
  rowOrdinal: v.number(),
  sourceRowKey: v.string(),
  sourceRowDigest: v.string(),
  sourceRawValue: v.optional(v.string()),
  productSkuId: v.optional(v.id("productSku")),
  provisionalSkuId: v.optional(v.id("inventoryImportProvisionalSku")),
  productName: v.string(),
  sku: v.optional(v.string()),
  barcode: v.optional(v.string()),
  normalizedCostMinor: v.optional(v.number()),
  costOutcome: inventoryImportCostOverlayCostOutcomeValidator,
  provenanceDigest: v.string(),
  anchorDigest: v.string(),
  currentUnitCostMinor: v.optional(v.number()),
  preInventoryCount: v.number(),
  preQuantityAvailable: v.number(),
  preCostedQuantity: v.number(),
  preUncostedQuantity: v.number(),
  preKnownCostPoolMinor: v.number(),
  preCurrencyCode: v.optional(v.string()),
  preCurrencyMinorUnitScale: v.optional(v.number()),
  preProvisionalUpdatedAt: v.number(),
  frozenLineages: v.array(inventoryImportCostOverlayFrozenLineageValidator),
  frozenLineageDigest: v.string(),
  lifecycle: v.union(v.literal("provisional"), v.literal("trusted")),
  eligibility: inventoryImportCostOverlayEligibilityValidator,
  eligibilityReason: v.optional(v.string()),
  decision: inventoryImportCostOverlayDecisionValidator,
  frozenFingerprint: v.string(),
  prePositionVersion: v.optional(v.number()),
});

export const inventoryImportCostOverlayRowSchema = v.object({
  runId: v.id("inventoryImportCostOverlayRun"),
  storeId: v.id("store"),
  organizationId: v.id("organization"),
  productSkuId: v.optional(v.id("productSku")),
  provisionalSkuId: v.optional(v.id("inventoryImportProvisionalSku")),
  productName: v.string(),
  sku: v.optional(v.string()),
  barcode: v.optional(v.string()),
  rowOrdinal: v.number(),
  sourceRowKey: v.string(),
  sourceRowDigest: v.string(),
  sourceRawValue: v.optional(v.string()),
  normalizedCostMinor: v.optional(v.number()),
  costOutcome: inventoryImportCostOverlayCostOutcomeValidator,
  provenanceDigest: v.string(),
  anchorDigest: v.string(),
  currentUnitCostMinor: v.optional(v.number()),
  preInventoryCount: v.number(),
  preQuantityAvailable: v.number(),
  preCostedQuantity: v.number(),
  preUncostedQuantity: v.number(),
  preKnownCostPoolMinor: v.number(),
  preCurrencyCode: v.optional(v.string()),
  preCurrencyMinorUnitScale: v.optional(v.number()),
  preProvisionalUpdatedAt: v.number(),
  frozenLineages: v.array(inventoryImportCostOverlayFrozenLineageValidator),
  frozenLineageDigest: v.string(),
  lifecycle: v.union(v.literal("provisional"), v.literal("trusted")),
  eligibility: inventoryImportCostOverlayEligibilityValidator,
  eligibilityReason: v.optional(v.string()),
  decision: inventoryImportCostOverlayDecisionValidator,
  decisionRevision: v.number(),
  frozenFingerprint: v.string(),
  prePositionVersion: v.optional(v.number()),
  manifestOrdinal: v.optional(v.number()),
  manifestEntryDigest: v.optional(v.string()),
  workStatus: v.optional(inventoryImportCostOverlayWorkStatusValidator),
  applyExceptionReason: v.optional(v.string()),
  applyCorrectionId: v.optional(v.id("reportingSkuValuationCorrection")),
  applyInventoryEffectId: v.optional(v.id("reportingInventoryEffect")),
  postInventoryCount: v.optional(v.number()),
  postQuantityAvailable: v.optional(v.number()),
  postUnitCostMinor: v.optional(v.number()),
  postCostedQuantity: v.optional(v.number()),
  postUncostedQuantity: v.optional(v.number()),
  postKnownCostPoolMinor: v.optional(v.number()),
  postCurrencyCode: v.optional(v.string()),
  postCurrencyMinorUnitScale: v.optional(v.number()),
  postPositionVersion: v.optional(v.number()),
  postFingerprint: v.optional(v.string()),
  postLineageDigest: v.optional(v.string()),
  appliedAt: v.optional(v.number()),
  undoExceptionReason: v.optional(v.string()),
  undoCorrectionId: v.optional(v.id("reportingSkuValuationCorrection")),
  undoInventoryEffectId: v.optional(v.id("reportingInventoryEffect")),
  undoneAt: v.optional(v.number()),
  createdAt: v.number(),
  updatedAt: v.number(),
});
