import { v } from "convex/values";

const availabilityValidator = v.union(
  v.literal("archived"),
  v.literal("draft"),
  v.literal("live")
);

export const productSkuSearchSchema = v.object({
  attributes: v.optional(
    v.record(
      v.string(),
      v.union(v.string(), v.number(), v.boolean(), v.null())
    )
  ),
  barcode: v.optional(v.string()),
  barcodeAutoGenerated: v.optional(v.boolean()),
  categoryDescription: v.optional(v.string()),
  categoryId: v.optional(v.id("category")),
  categoryName: v.optional(v.string()),
  categorySlug: v.optional(v.string()),
  categoryShowOnStorefront: v.optional(v.boolean()),
  colorHexCode: v.optional(v.string()),
  colorId: v.optional(v.id("color")),
  colorName: v.optional(v.string()),
  currency: v.optional(v.string()),
  images: v.array(v.string()),
  inventoryCount: v.number(),
  isVisible: v.optional(v.boolean()),
  length: v.optional(v.number()),
  netPrice: v.optional(v.number()),
  normalizedBarcode: v.optional(v.string()),
  normalizedSku: v.optional(v.string()),
  price: v.number(),
  productAvailability: availabilityValidator,
  productCategoryId: v.id("category"),
  productDescription: v.optional(v.string()),
  productId: v.id("product"),
  productInventoryCount: v.number(),
  productIsVisible: v.optional(v.boolean()),
  productName: v.string(),
  productProcessingFeesAbsorbed: v.optional(v.boolean()),
  productQuantityAvailable: v.optional(v.number()),
  productSlug: v.optional(v.string()),
  productSkuCreationTime: v.number(),
  productSkuId: v.id("productSku"),
  productSubcategoryId: v.id("subcategory"),
  quantityAvailable: v.number(),
  searchText: v.string(),
  size: v.optional(v.string()),
  sku: v.optional(v.string()),
  storeId: v.id("store"),
  subcategoryDescription: v.optional(v.string()),
  subcategoryId: v.optional(v.id("subcategory")),
  subcategoryName: v.optional(v.string()),
  subcategorySlug: v.optional(v.string()),
  unitCost: v.optional(v.number()),
  weight: v.optional(v.string()),
  sourceUpdatedAt: v.number(),
  updatedAt: v.number(),
});
