import React, {
  createContext,
  useContext,
  useState,
  ReactNode,
  useCallback,
  useEffect,
  useRef,
} from "react";
import { ProductVariant } from "@/components/add-product/ProductStock";
import { ImageFile } from "@/components/ui/image-uploader";
import { ZodError } from "zod";
import useGetActiveProduct from "@/hooks/useGetActiveProduct";
import { Product, ProductSku } from "~/types";
import { productSchema } from "../lib/schemas/product";
import { toast } from "sonner";
import { toDisplayAmount } from "~/convex/lib/currency";
import { useParams } from "@tanstack/react-router";
import { normalizeSkuAttributeValue } from "@/components/add-product/ProductVariantAttributes";

interface ProductContextType {
  activeProductVariant: ProductVariant;
  activeProduct?: Product | null;
  error: ZodError | null;
  images: ImageFile[];
  productData: Partial<Product>;
  productVariants: ProductVariant[];
  setActiveProductVariant: React.Dispatch<React.SetStateAction<ProductVariant>>;
  setError: React.Dispatch<React.SetStateAction<ZodError | null>>;
  updateImages: React.Dispatch<React.SetStateAction<ImageFile[]>>;
  updateProductVariants: React.Dispatch<React.SetStateAction<ProductVariant[]>>;
  didProvideRequiredData: () => boolean;
  removeProductVariant: (id: string) => void;
  revertChanges: () => void;
  updateProductData: (newData: Partial<Product>) => void;
  updateProductVariant: (
    variantId: string,
    attributes: Partial<ProductVariant>,
  ) => void;
  mergeTrustedInventoryFinalization: (
    result: TrustedInventoryFinalizationMerge,
  ) => void;
  isLoading: boolean;
  updateVariantImages: (variantId: string, newImages: ImageFile[]) => void;
  updateAppState: (newState: Partial<AppState>) => void;
  showLoaderForProduct: boolean;

  // actions
  appState: AppState;
}

export type TrustedInventoryFinalizationMerge = {
  product?: {
    inventoryCount?: number;
    quantityAvailable?: number;
    availability?: Product["availability"];
    isVisible?: boolean;
  };
  sku: {
    id: string;
    stock: number;
    quantityAvailable: number;
    cost?: number;
    price?: number;
    netPrice?: number;
    isVisible?: boolean;
  };
};

function valuesMatch(left: unknown, right: unknown) {
  return JSON.stringify(left) === JSON.stringify(right);
}

function stripSkus(product: Product): Partial<Product> {
  return {
    ...product,
    skus: undefined,
  };
}

export const convertSkuToVariant = (sku: ProductSku): ProductVariant => ({
  existsInDB: true,
  id: sku._id,
  isVisible: sku.isVisible,
  sku: sku.sku,
  barcode: sku.barcode || undefined,
  barcodeAutoGenerated: sku.barcodeAutoGenerated,
  barcodePersistedInDb: !!sku.barcode,
  stock: sku.inventoryCount,
  quantityAvailable: sku.quantityAvailable,
  cost: sku.unitCost ? toDisplayAmount(sku.unitCost) : undefined,
  price: toDisplayAmount(sku.price),
  netPrice: sku.netPrice ? toDisplayAmount(sku.netPrice) : undefined,
  size: normalizeSkuAttributeValue(sku.size),
  color: normalizeSkuAttributeValue(sku.color),
  colorName: sku.colorName || undefined,
  length: normalizeSkuAttributeValue(sku.length),
  weight: normalizeSkuAttributeValue(sku.weight),
  images: sku.images.map((imageUrl) => ({
    preview: imageUrl,
    file: undefined,
  })),
});

export function mergeProductDataWithActiveProductRefresh({
  localProductData,
  nextActiveProduct,
  previousActiveProduct,
}: {
  localProductData: Partial<Product>;
  nextActiveProduct: Product;
  previousActiveProduct?: Product | null;
}): Partial<Product> {
  const nextData = stripSkus(nextActiveProduct);
  if (
    !previousActiveProduct ||
    previousActiveProduct._id !== nextActiveProduct._id
  ) {
    return nextData;
  }

  const previousData = stripSkus(previousActiveProduct);
  const merged = { ...nextData } as Record<string, unknown>;

  for (const [key, localValue] of Object.entries(localProductData)) {
    if (key === "skus") continue;
    const previousValue = (previousData as Record<string, unknown>)[key];
    if (!valuesMatch(localValue, previousValue)) {
      merged[key] = localValue;
    }
  }

  return merged as Partial<Product>;
}

export function mergeProductVariantsWithActiveProductRefresh({
  localVariants,
  nextActiveProduct,
  previousActiveProduct,
}: {
  localVariants: ProductVariant[];
  nextActiveProduct: Product;
  previousActiveProduct?: Product | null;
}): ProductVariant[] {
  const nextVariants = nextActiveProduct.skus.map((sku: ProductSku) =>
    convertSkuToVariant(sku),
  );
  if (
    !previousActiveProduct ||
    previousActiveProduct._id !== nextActiveProduct._id
  ) {
    return nextVariants;
  }

  const previousVariantsById = new Map(
    previousActiveProduct.skus.map((sku: ProductSku) => [
      String(sku._id),
      convertSkuToVariant(sku),
    ]),
  );
  const localVariantsById = new Map(
    localVariants.map((variant) => [variant.id, variant]),
  );

  const mergedVariants = nextVariants.map((nextVariant) => {
    const previousVariant = previousVariantsById.get(nextVariant.id);
    const localVariant = localVariantsById.get(nextVariant.id);
    if (!previousVariant || !localVariant) {
      return nextVariant;
    }

    const merged = { ...nextVariant } as Record<string, unknown>;
    for (const [key, localValue] of Object.entries(localVariant)) {
      const previousValue = (previousVariant as Record<string, unknown>)[key];
      if (!valuesMatch(localValue, previousValue)) {
        merged[key] = localValue;
      }
    }
    return merged as ProductVariant;
  });

  const nextVariantIds = new Set(nextVariants.map((variant) => variant.id));
  const unsavedLocalVariants = localVariants.filter(
    (variant) => !nextVariantIds.has(variant.id),
  );

  return [...mergedVariants, ...unsavedLocalVariants];
}

export function mergeTrustedInventoryFinalizationIntoVariants(
  variants: ProductVariant[],
  result: TrustedInventoryFinalizationMerge,
): ProductVariant[] {
  return variants.map((variant) =>
    variant.id === result.sku.id
      ? {
          ...variant,
          stock: result.sku.stock,
          quantityAvailable: result.sku.quantityAvailable,
          cost: result.sku.cost ?? variant.cost,
          price: result.sku.price ?? variant.price,
          netPrice: result.sku.netPrice ?? variant.netPrice,
          isVisible: result.sku.isVisible ?? variant.isVisible,
        }
      : variant,
  );
}

interface AppState {
  isInitialLoad: boolean;
  didRevertChanges: boolean;
}

const ProductContext = createContext<ProductContextType | undefined>(undefined);

export function ProductProvider({
  children,
  includeArchived = false,
}: {
  children: ReactNode;
  includeArchived?: boolean;
}) {
  const [productData, setProductData] = useState<Partial<Product>>({
    availability: "live" as const,
  });

  const [productVariants, updateProductVariants] = useState<ProductVariant[]>([
    {
      id: Date.now().toString(),
      sku: "",
      stock: 0,
      quantityAvailable: 0,
      isVisible: true,
      cost: 0,
      price: 0,
      images: [],
    },
  ]);

  const initialAppState: AppState = {
    isInitialLoad: false,
    didRevertChanges: false,
  };

  const [appState, setAppState] = useState<AppState>(initialAppState);

  const [activeProductVariant, setActiveProductVariant] =
    useState<ProductVariant>(productVariants[0]);

  const [images, updateImages] = useState<ImageFile[]>([]);
  const [error, setError] = useState<ZodError | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const { productSlug } = useParams({ strict: false });

  const { activeProduct } = useGetActiveProduct({ includeArchived });
  const previousActiveProductRef = useRef<Product | null>(null);

  const updateAppState = (newState: Partial<AppState>) => {
    setAppState((prevState) => ({ ...prevState, ...newState }));
  };

  const removeProductVariant = useCallback(
    (id: string) => {
      updateProductVariants((prevVariants) => {
        if (activeProduct) {
          // If there's an active product, mark the variant for deletion
          // Check if the variant exists in the active product
          const variantExistsInActiveProduct = activeProduct.skus.some(
            (variant: ProductSku) => variant._id === id,
          );

          if (variantExistsInActiveProduct) {
            // If the variant exists in the active product, mark it for deletion
            return prevVariants.map((variant) =>
              variant.id === id
                ? { ...variant, markedForDeletion: true }
                : variant,
            );
          } else {
            // If it's a newly added variant during edit, remove it

            const updated = prevVariants.filter((v) => v.id !== id);

            const index = prevVariants.findIndex(
              (v) => v.id == activeProductVariant.id,
            );

            if (index == prevVariants.length - 1) {
              const lastVariant = updated.at(-1);
              if (lastVariant) {
                setActiveProductVariant(lastVariant);
              }
            }

            return updated;
          }
        } else {
          // If there's no active product, remove the variant
          const newVariants = prevVariants.filter((v) => v.id !== id);
          if (activeProductVariant && activeProductVariant.id === id) {
            setActiveProductVariant(newVariants[0] || null);
          }
          return newVariants;
        }
      });
    },
    [activeProduct, activeProductVariant],
  );

  const updateVariantImages = useCallback(
    (variantId: string, newImages: ImageFile[]) => {
      updateProductVariants((prevVariants) =>
        prevVariants.map((variant) =>
          variant.id === variantId
            ? { ...variant, images: newImages }
            : variant,
        ),
      );
    },
    [],
  );

  const updateProductVariant = (
    variantId: string,
    attributes: Partial<ProductVariant>,
  ) => {
    updateProductVariants((prevVariants) =>
      prevVariants.map((variant) =>
        variant.id === variantId ? { ...variant, ...attributes } : variant,
      ),
    );
  };

  const mergeTrustedInventoryFinalization = (
    result: TrustedInventoryFinalizationMerge,
  ) => {
    setProductData((prevData) => ({
      ...prevData,
      ...(result.product?.inventoryCount !== undefined
        ? { inventoryCount: result.product.inventoryCount }
        : {}),
      ...(result.product?.quantityAvailable !== undefined
        ? { quantityAvailable: result.product.quantityAvailable }
        : {}),
      ...(result.product?.availability !== undefined
        ? { availability: result.product.availability }
        : {}),
      ...(result.product?.isVisible !== undefined
        ? { isVisible: result.product.isVisible }
        : {}),
    }));

    updateProductVariants((prevVariants) =>
      mergeTrustedInventoryFinalizationIntoVariants(prevVariants, result),
    );
  };

  const didProvideRequiredData = () => {
    try {
      productSchema.parse({
        ...productData,
        images: images.map((file) => file.file?.path || file.preview),
      });
      return true;
    } catch {
      return false;
    }
  };

  const updateProductData = (newData: Partial<Product>) => {
    setProductData((prevData) => ({ ...prevData, ...newData }));
  };

  const revertChanges = () => {
    if (!activeProduct) return;

    updateAppState({ didRevertChanges: true });

    setProductData({
      ...activeProduct,
      skus: undefined, // Exclude skus from productData
    });

    const variants = activeProduct.skus.map((sku: ProductSku) =>
      convertSkuToVariant(sku),
    );
    updateProductVariants(variants);
    setActiveProductVariant(variants[0] || null);
    previousActiveProductRef.current = activeProduct;

    toast.success("Changes reverted");
  };

  useEffect(() => {
    if (activeProduct) {
      const previousActiveProduct = previousActiveProductRef.current;

      setProductData((prevData) =>
        mergeProductDataWithActiveProductRefresh({
          localProductData: prevData,
          nextActiveProduct: activeProduct,
          previousActiveProduct,
        }),
      );

      updateProductVariants((prevVariants) => {
        const variants = mergeProductVariantsWithActiveProductRefresh({
          localVariants: prevVariants,
          nextActiveProduct: activeProduct,
          previousActiveProduct,
        });
        setActiveProductVariant((prevActiveVariant) =>
          variants.find((variant) => variant.id === prevActiveVariant?.id) ??
          variants[0] ??
          null,
        );
        return variants;
      });

      previousActiveProductRef.current = activeProduct;

      setIsLoading(false);
    } else {
      previousActiveProductRef.current = null;
      setIsLoading(false);
    }
  }, [activeProduct]);

  useEffect(() => {
    if (activeProductVariant) {
      const updatedVariant = productVariants.find(
        (v) => v.id === activeProductVariant.id,
      );
      if (
        updatedVariant &&
        JSON.stringify(updatedVariant) !== JSON.stringify(activeProductVariant)
      ) {
        setActiveProductVariant(updatedVariant);
      }
    }
  }, [productVariants, activeProductVariant]);

  const value = {
    appState,
    activeProduct,
    productData,
    updateProductData,
    activeProductVariant,
    setActiveProductVariant,
    productVariants,
    updateProductVariants,
    images,
    updateImages,
    error,
    setError,
    didProvideRequiredData,
    removeProductVariant,
    revertChanges,
    updateVariantImages,
    updateProductVariant,
    mergeTrustedInventoryFinalization,
    updateAppState,
    isLoading,
    showLoaderForProduct: Boolean(productSlug && activeProduct === undefined),
  };

  return (
    <ProductContext.Provider value={value}>{children}</ProductContext.Provider>
  );
}

export function useProduct() {
  const context = useContext(ProductContext);
  if (context === undefined) {
    throw new Error("useProduct must be used within a ProductProvider");
  }
  return context;
}
